pulumi/ci-mgmt

- provider-ci/lib/steps.js
- provider-ci/lib/workflows.js
- provider-ci/providers/aws/repo/.github/workflows/main.yml
- provider-ci/providers/aws/repo/.github/workflows/master.yml
- provider-ci/providers/aws/repo/.github/workflows/prerelease.yml
- provider-ci/providers/aws/repo/.github/workflows/release.yml
- provider-ci/src/steps.ts
- provider-ci/src/workflows.ts
This is not needed for anything other than the release workflow
and we should not use the ref name - we should calculate it like
we do during build time
Without this change ALL master builds would create a tag and push that tag to the repo - even more - master builds would be being tagged as sdk/master and pushing those tags
> Ensure that ONLY release workflows tag the Go SDK

- .github/workflows/deploy-all-providers.yml
This turns out to generate too much noise, we should perhaps set up a lambda webhook listener to notify our alert channel when a check suite in a repo fails instead.
> Don't automatically add reviewers

- .github/workflows/deploy-all-providers.yml
- .github/workflows/deploy-single-provider.yml
Add a step to deploy-all-providers.yml that will enable automerge via squash on all created prs.  Automerge will only happen if all required checks pass, but it will not time out and will remove our need to run our own automerge job.
related #153 
fixes #144
resolves #155
> Use built in GH automerge

- .github/workflows/update-gh-branch-protection.yml
We should be able to move away from the Branch protection token to a new pulumi bot token
> test new pulumi bot token

- .github/workflows/update-workflows-all-providers.yml
- .github/workflows/update-workflows-single-provider.yml
This change will add removing all existing workflows as a step before we copy in new ones, to ensure cruft is not left behind as we go.
> Remove old automerge action

- provider-ci/providers/azure/config.yaml
- provider-ci/providers/azure/repo/.goreleaser.prerelease.yml
- provider-ci/providers/azure/repo/.goreleaser.yml
This is back porting the changes to the CI Mgmt repo as per our convention
> Bump Azure to be a v5 provider

- provider-ci/package-lock.json
- provider-ci/providers/auth0/config.yaml
- provider-ci/providers/auth0/repo/.github/workflows/update-upstream-provider.yml
Not sure if this is the correct place for this PR, but [it seems like auth0 is taking official ownership of their terraform plugin](https://github.com/auth0/terraform-provider-auth0/).
This should update the upstream provider to reflect that and pickup the latest release.
> change auth0 provider from 'alexkappa' to 'auth0'

- native-provider-ci/providers/aws-native/repo/.github/workflows/build.yml
- native-provider-ci/providers/aws-native/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/aws-native/repo/.github/workflows/release.yml
- native-provider-ci/providers/aws-native/repo/.github/workflows/run-acceptance-tests.yml
- native-provider-ci/providers/azure-native/repo/.github/workflows/build.yml
- native-provider-ci/providers/azure-native/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/azure-native/repo/.github/workflows/release.yml
- native-provider-ci/providers/azure-native/repo/.github/workflows/run-acceptance-tests.yml
- native-provider-ci/providers/command/repo/.github/workflows/build.yml
- native-provider-ci/providers/command/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/command/repo/.github/workflows/release.yml
- native-provider-ci/providers/command/repo/.github/workflows/run-acceptance-tests.yml
- native-provider-ci/providers/google-native/repo/.github/workflows/build.yml
- native-provider-ci/providers/google-native/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/google-native/repo/.github/workflows/release.yml
- native-provider-ci/providers/google-native/repo/.github/workflows/run-acceptance-tests.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/build.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/release.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/run-acceptance-tests.yml
- native-provider-ci/src/workflows.ts
part of https://github.com/pulumi/home/issues/2055  
Notes:
fix important issue in release.yml so that release doesn't call the prerelease command
add notify functionality for build_sdks and test steps (formerly not present consistently in native providers)
use macos runner for azure-native dotnet sdk builds
> update release.yml and restore notify for build_sdk and test steps

- .github/workflows/rollout-native-provider-workflows.yml
- native-provider-ci/providers/aws-native/repo/.github/workflows/nightly-sdk-generation.yml
- native-provider-ci/providers/aws-native/repo/.github/workflows/weekly-pulumi-update.yml
- native-provider-ci/providers/azure-native/repo/.github/workflows/nightly-sdk-generation.yml
- native-provider-ci/providers/azure-native/repo/.github/workflows/weekly-pulumi-update.yml
- native-provider-ci/providers/command/repo/.github/workflows/weekly-pulumi-update.yml
- native-provider-ci/providers/google-native/repo/.github/workflows/nightly-sdk-generation.yml
- native-provider-ci/providers/google-native/repo/.github/workflows/weekly-pulumi-update.yml
- native-provider-ci/src/workflows.ts
We are experiencing some unpredictable and not as intended automerges in native-providers, pausing the use of the feature for now.
> Pause automerge in native-providers

- native-provider-ci/src/steps.ts
Using `gotestfmt` appears to be more trouble than it's worth -- see https://github.com/pulumi/pulumi-kubernetes/actions/runs/3490648026/jobs/5842448567 for example, where there are a number of apparent failures for tests that actually passed (note the X by "TestRetry", then search for "PASS: TestRetry"). When I removed gotestfmt from the test command, the tests are represented as passing:  https://github.com/pulumi/pulumi-kubernetes/pull/2239.
This is a conservative change to remove its use just for the pulumi-kubernetes provider. If it's causing problems elsewhere too, we can make a more sweeping change.
> Remove the use of gotestfmt for pulumi-kubernetes

- native-provider-ci/providers/kubernetes/repo/.github/workflows/build.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/release.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/run-acceptance-tests.yml
- native-provider-ci/src/steps.ts
After #288, this regenerates the cached files -- since that PR targeted only pulumi-kubernetes, only those files change here.
> Regenerate pulumi-kubernetes build/workflow files

- infra/providers/index.ts
Following https://github.com/pulumi/ci-mgmt/pull/301 , this locks GitHub branch protection to not auto-merge until all the important jobs have passed.
Pondering rollout order here. Perhaps before merging, we need to make sure that all the providers have been upgraded with the results of 301? If we merge this does send some providers into a state where no PRs can't merge until they catch up with 301?
> Update required steps for automerge workflow

- provider-ci/providers/keycloak/config.yaml
- provider-ci/providers/keycloak/repo/.github/workflows/command-dispatch.yml
- provider-ci/providers/keycloak/repo/.github/workflows/main.yml
- provider-ci/providers/keycloak/repo/.github/workflows/master.yml
- provider-ci/providers/keycloak/repo/.github/workflows/prerelease.yml
- provider-ci/providers/keycloak/repo/.github/workflows/pull-request.yml
- provider-ci/providers/keycloak/repo/.github/workflows/release.yml
- provider-ci/providers/keycloak/repo/.github/workflows/resync-build.yml
- provider-ci/providers/keycloak/repo/.github/workflows/run-acceptance-tests.yml
- provider-ci/providers/keycloak/repo/.github/workflows/update-upstream-provider.yml
Update KeyCloak for major version 4 update (see https://github.com/pulumi/pulumi-keycloak/pull/162).
> Update keycloak URL for 4.1.0 (major version)

- tools/sourcemigrator/index.ts
Some of our repositories are on Go 1.14 or some such. This contributes to broken build/test issues. This source migration detects go.mod and makes sure it's 1.19. It does not touch go.mod generated by pulumi/pkg such as sdk/python/go.mod that are installed as placeholders (those are not real go modules). For every go module it updates, it runs `go mod tidy` to re-sync `go.sum`.
To make this work, trigger Actions as needed, they will stand up PRs that apply the migrations as part of the PR.
> Source migrator to upgrade go to 1.19

- provider-ci/providers/docker/config.yaml
- provider-ci/providers/docker/repo/Makefile
- provider-ci/providers/fastly/repo/.goreleaser.prerelease.yml
- provider-ci/providers/fastly/repo/.goreleaser.yml
- provider-ci/providers/fastly/repo/Makefile
- provider-ci/src/config.ts
- provider-ci/src/make-bridged-provider.ts
Hybrid providers are terraform-bridged Pulumi providers that have native resources added to them.
Our currently only example of this is the [Pulumi Docker Provider](https://github.com/pulumi/pulumi-docker).
All native resources need to generate their own documentation, and this PR encodes the process into any hybrid
provider Makefile.
The provider's `config.yaml` will need to contain the `docsCmd` field as well as the `hybrid` field in order to
generate a Makefile with a `docs` target.
See also: https://github.com/pulumi/pulumi-docker/pull/479
- Add logic to add a `docs` Makefile target
- generalize approach to denote a hybrid provider rather than docekr specifically
- Generate all providers. Updates major version for Fastly but does not add any extra targets to non-hybrid providers, as …
> Add docs gen Makefile target for hybrid providers

- .github/workflows/update-gh-branch-protection.yml
The workflow has been failing, presumably because it cannot auth to GH when executing BranchProtection changes.
> Need auth on the GH BranchProtection managing stack

- .github/workflows/update-workflows-bridged-providers.yml
Idea: Don't automerge for the providers team. We'll always review changes coming down which reduces the need for us to review ongoing work.
This is just to demonstrate the intended output ... might be better ways to implement! Also, need to check all other workflows.
> Exclude providers team repos from automerge

- provider-ci/providers/docker/config.yaml
- provider-ci/providers/docker/repo/.github/workflows/command-dispatch.yml
- provider-ci/providers/docker/repo/.github/workflows/main.yml
- provider-ci/providers/docker/repo/.github/workflows/master.yml
- provider-ci/providers/docker/repo/.github/workflows/prerelease.yml
- provider-ci/providers/docker/repo/.github/workflows/pull-request.yml
- provider-ci/providers/docker/repo/.github/workflows/release.yml
- provider-ci/providers/docker/repo/.github/workflows/resync-build.yml
- provider-ci/providers/docker/repo/.github/workflows/run-acceptance-tests.yml
- provider-ci/providers/docker/repo/.github/workflows/update-upstream-provider.yml
This is a necessary prerequisite for pulumi/pulumi-docker#510.
CI needs access to the Dockerhub credentials.
> Read in dockerhub password

- provider-ci/providers/cloudflare/config.yaml
- provider-ci/providers/cloudflare/repo/.goreleaser.prerelease.yml
- provider-ci/providers/cloudflare/repo/.goreleaser.yml
- provider-ci/providers/cloudflare/repo/Makefile
Looks like pulumi-cloudflare is on v5 now but ci-mgmt conflicts with it and tries to auto-update to v4.
> Use v5 major version on cloudflare

- .github/workflows/update-workflows-ecosystem-providers.yml
I've noticed that running this workflow can be very expensive and take resources away from other CI jobs folks are running during the day. Suggest preferring a nightly run to manual triggers.
> Nightly trigger for update-workflows-ecosystem-providers

- .github/workflows/update-workflows-ecosystem-providers.yml
Noticing a lot of unmerged PRs that pass tests. Stood up nightly. This should make them auto-merge hopefully.
> Make automerge the default for update-workflows-ecosystem-providers

- .github/workflows/update-workflows-ecosystem-providers.yml
- .github/workflows/update-workflows-single-bridged-provider.yml
Jobs in this repo open 'Update GitHub Actions workflows' PRs, and we have a lot of them. Usually only the last one is relevant. Add some code to scan open PRs for this title and auto-close them before opening a new one.
Fixes https://github.com/pulumi/ci-mgmt/issues/398
> Auto-close stale Update GitHub Actions workflows PRs before opening a new one

- native-provider-ci/providers/kubernetes/repo/.github/workflows/build.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/release.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/run-acceptance-tests.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/weekly-pulumi-update.yml
- native-provider-ci/src/workflows.ts
The pulumi-kubernetes repo now includes a `v4` branch to stage breaking changes that will be included in the 4.0 release. Enable testing on the branch as well.
> Add pulumi-kubernetes/v4 branch to CI workflow

- provider-ci/providers/gitlab/config.yaml
- provider-ci/providers/gitlab/repo/Makefile
Currently repository is already using 0.9.3 but automated PRs try to downgrade it.
> Ensure gitlab does not downgrade from Java 0.9.3

- .github/workflows/update-bridge-ecosystem-providers.yml
The github action we use in `ci-mgmt` to send a dispatch to each providers `upgrade-bridge` workflow, https://github.com/marketplace/actions/workflow-dispatch, requires `ref` to be set if it differs from the calling repo branch (which is `master` for this repo, `ci-mgmt`.
This changes it to first attempt to use `master`, and then continue if the ref is not found and to use `main` instead. We should still consider moving all provider default branches from `master` -> `main` eventually.
> Fix `upgrade-bridge-ecosystem-providers.yml`

- provider-ci/providers/cloudamqp/config.yaml
Fixes ineffectual integration tests on pulumi-cloudamqp
> Add Cloudamqp API key to provider config

- provider-ci/providers/artifactory/config.yaml
- provider-ci/providers/artifactory/repo/Makefile
This was manually implemented as part of https://github.com/pulumi/pulumi-artifactory/pull/370. This makes it permanent.
> Add time provider during install

- provider-ci/providers/gcp/config.yaml
- provider-ci/providers/gcp/repo/Makefile
Avoid test failures on upgrades such as https://github.com/pulumi/pulumi-gcp/pull/1145
> Add `time` dependency for pulumi-gcp

- provider-ci/providers/archive/config.yaml
- provider-ci/providers/external/config.yaml
- provider-ci/providers/http/config.yaml
- provider-ci/providers/local/config.yaml
- provider-ci/providers/null/config.yaml
Fixes #491 
Error in CI:
```
Traceback (most recent call last):
File "/home/runner/work/ci-mgmt/ci-mgmt/scripts/generate_providers_list.py", line 24, in <module>
raise Exception(f"Provider {p} is lacking team: assignment in config.yaml")
Exception: Provider archive is lacking team: assignment in config.yaml
```
It looks like the most recently added providers are missing `team: ecosystem` in the `config.yaml`. This adds the missing field to match other similar providers.
Ideally, if this is a required field, we should fail the PR workflow (but we don't have any PR workflow).
> Add missing team in config

- provider-ci/providers/signalfx/config.yaml
- provider-ci/providers/signalfx/repo/.goreleaser.prerelease.yml
- provider-ci/providers/signalfx/repo/.goreleaser.yml
- provider-ci/providers/signalfx/repo/Makefile
CI updates have been failing since the provider's major version update last week.
> Update Signalfx major version

- tools/sourcemigrator/index.ts
We should be targeting `1.20` now, so workflow updates such as https://github.com/pulumi/pulumi-aws-native/pull/1014 don't attempt to downgrade the go version
> Update go version to update to from `1.19` to `1.20`

- provider-ci/internal/pkg/templates/bridged-provider/.goreleaser.prerelease.yml
- provider-ci/internal/pkg/templates/bridged-provider/.goreleaser.yml
- provider-ci/providers/azure/config.yaml
- provider-ci/providers/azure/repo/.goreleaser.prerelease.yml
- provider-ci/providers/azure/repo/.goreleaser.yml
This is causing publish failures in pulumi-azure (they only place where this is enabled) because it duplicates hooks. We now do this by default, so there is no observable change in working CI.
> Remove cleanCacheBetweenBuilds option

- .github/workflows/update-workflows-ecosystem-providers.yml
Fixes https://github.com/pulumi/ci-mgmt/issues/503
Some providers have an upstream submodule that must be initialized first before modifying the provider's dependencies/ go.mod
> Initialize provider submodule before attempting source code migration

- provider-ci/providers/wavefront/config.yaml
- provider-ci/providers/wavefront/repo/.goreleaser.prerelease.yml
- provider-ci/providers/wavefront/repo/.goreleaser.yml
- provider-ci/providers/wavefront/repo/Makefile
This also bumps the java version.
Needs to wait for https://github.com/pulumi/pulumi-wavefront/issues/178 to land.
> Bump wavefront major version

- provider-ci/providers/pagerduty/config.yaml
- provider-ci/providers/pagerduty/repo/Makefile
- Bumps the `pulumi-java` version to v0.9.5.
- Depends on `pulumi-time` at v0.0.15.
> Reflect https://github.com/pulumi/pulumi-pagerduty/pull/244

- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/run-acceptance-tests.yml
- provider-ci/providers/docker/config.yaml
- provider-ci/providers/docker/repo/.github/workflows/run-acceptance-tests.yml
This is the second ci-mgmt PR to enable pulumi/pulumi-docker#707. It adds a CI step to provision a required SSH key to DigitalOcean.
> Upload DigitalOcean SSH key if it exists

- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/main.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/master.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/nightly-test.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/prerelease.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/release.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/run-acceptance-tests.yml
- provider-ci/providers/docker/config.yaml
- provider-ci/providers/docker/repo/.github/workflows/main.yml
- provider-ci/providers/docker/repo/.github/workflows/master.yml
- provider-ci/providers/docker/repo/.github/workflows/prerelease.yml
- provider-ci/providers/docker/repo/.github/workflows/release.yml
Generalize `digitalOceanSshKey` to a `actions.preTest`. This makes room to allow pulumi-aws to include `Configure AWS Credentials`.
> Add `actions.preTest`

- provider-ci/internal/pkg/templates/bridged-provider.config.yaml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/command-dispatch.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/community-moderation.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/main.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/master.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/nightly-test.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/prerelease.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/pull-request.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/release.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/resync-build.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/run-acceptance-tests.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/update-bridge.yml
This is needed by https://github.com/pulumi/pulumi-aws/pull/2708.
For an example of what it looks like when `checkoutSubmodules: true`, see https://github.com/pulumi/ci-mgmt/pull/528/commits/be431ea8c5314c34162aac226ba8b176d9f0375f.
> Allow checking out submodules as part of repo checkout

- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/nightly-test.yml
- provider-ci/providers/azure/repo/.github/workflows/nightly-test.yml
- provider-ci/providers/azuread/repo/.github/workflows/nightly-test.yml
- provider-ci/providers/gcp/repo/.github/workflows/nightly-test.yml
We missed updating this when we removed `.Config.actionVersions.setupGo` to `.Config.actions.setupGo`. These workflows were broken, and this fixes them.
> Fix nightly workflow

- .github/workflows/update-native-provider-workflows.yml
- scripts/generate_native_providers_list.py
We recently got aws-native back in sync with ci-mgmt; this will help us keep it in sync.
> Create a daily workflow to update native-providers that are opted into ci-mgmt

- native-provider-ci/providers/aws-native/repo/.github/workflows/build.yml
- native-provider-ci/providers/aws-native/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/aws-native/repo/.github/workflows/release.yml
- native-provider-ci/providers/aws-native/repo/.github/workflows/run-acceptance-tests.yml
- native-provider-ci/providers/azure-native/repo/.github/workflows/build.yml
- native-provider-ci/providers/azure-native/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/azure-native/repo/.github/workflows/release.yml
- native-provider-ci/providers/azure-native/repo/.github/workflows/run-acceptance-tests.yml
- native-provider-ci/providers/command/repo/.github/workflows/build.yml
- native-provider-ci/providers/command/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/command/repo/.github/workflows/release.yml
- native-provider-ci/providers/command/repo/.github/workflows/run-acceptance-tests.yml
- native-provider-ci/providers/google-native/repo/.github/workflows/build.yml
- native-provider-ci/providers/google-native/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/google-native/repo/.github/workflows/release.yml
- native-provider-ci/providers/google-native/repo/.github/workflows/run-acceptance-tests.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/build.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/release.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/run-acceptance-tests.yml
- native-provider-ci/src/action-versions.ts
- native-provider-ci/src/steps.ts
- native-provider-ci/src/workflows.ts
Adds a step to native providers workflows that sends coverage reports to codecov
Tested on aws-native here: https://github.com/pulumi/pulumi-aws-native/pull/1058
> Native providers: Add codecov upload step after running provider tests

- native-provider-ci/providers/kubernetes/config.yaml
- native-provider-ci/providers/kubernetes/repo/.goreleaser.prerelease.yml
- native-provider-ci/providers/kubernetes/repo/.goreleaser.yml
A test PR (https://github.com/pulumi/pulumi-kubernetes/pull/2548) showed that Kubernetes workflows are almost in sync with ci-mgmt, with the two exceptions:
- major version number
- version of actions/upload-artifact
This PR addresses the former.
> Set the right major version for Kubernetes

- native-provider-ci/providers/aws-native/repo/.github/workflows/build.yml
- native-provider-ci/providers/aws-native/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/aws-native/repo/.github/workflows/release.yml
- native-provider-ci/providers/aws-native/repo/.github/workflows/run-acceptance-tests.yml
- native-provider-ci/providers/azure-native/repo/.github/workflows/build.yml
- native-provider-ci/providers/azure-native/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/azure-native/repo/.github/workflows/release.yml
- native-provider-ci/providers/azure-native/repo/.github/workflows/run-acceptance-tests.yml
- native-provider-ci/providers/command/repo/.github/workflows/build.yml
- native-provider-ci/providers/command/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/command/repo/.github/workflows/release.yml
- native-provider-ci/providers/command/repo/.github/workflows/run-acceptance-tests.yml
- native-provider-ci/providers/google-native/repo/.github/workflows/build.yml
- native-provider-ci/providers/google-native/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/google-native/repo/.github/workflows/release.yml
- native-provider-ci/providers/google-native/repo/.github/workflows/run-acceptance-tests.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/build.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/release.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/run-acceptance-tests.yml
- native-provider-ci/src/action-versions.ts
A test PR (https://github.com/pulumi/pulumi-kubernetes/pull/2548) showed that Kubernetes workflows are almost in sync with ci-mgmt, with the two exceptions:
- major version number
- version of actions/upload-artifact
This PR addresses the latter.
> Bump action/upload-artifact to v3 for native providers

- provider-ci/providers/aiven/config.yaml
- provider-ci/providers/aiven/repo/Makefile
This reflects the change from https://github.com/pulumi/pulumi-aiven/commit/c6772dd188ce82ba4601a8d732a5cc6ce1ef0435.
> Update aiven's java version to reflect what is in-repo

- native-provider-ci/providers/aws-native/repo/.github/workflows/build.yml
- native-provider-ci/providers/aws-native/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/aws-native/repo/.github/workflows/release.yml
- native-provider-ci/providers/aws-native/repo/.github/workflows/run-acceptance-tests.yml
- native-provider-ci/providers/command/repo/.github/workflows/build.yml
- native-provider-ci/providers/command/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/command/repo/.github/workflows/release.yml
- native-provider-ci/providers/command/repo/.github/workflows/run-acceptance-tests.yml
- native-provider-ci/providers/google-native/repo/.github/workflows/build.yml
- native-provider-ci/providers/google-native/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/google-native/repo/.github/workflows/release.yml
- native-provider-ci/providers/google-native/repo/.github/workflows/run-acceptance-tests.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/build.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/release.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/run-acceptance-tests.yml
- native-provider-ci/src/workflows.ts
Workaround https://github.com/pulumi/ci-mgmt/issues/554 fallout for native providers. Some of these have drifted from ci-mgmt but I notice that pulumi-aws-native is very close so it could definitely benefit it.
> Build sdks on larger runner

- native-provider-ci/providers/aws-native/repo/.github/workflows/build.yml
- native-provider-ci/providers/aws-native/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/aws-native/repo/.github/workflows/release.yml
- native-provider-ci/providers/azure-native/repo/.github/workflows/build.yml
- native-provider-ci/providers/azure-native/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/azure-native/repo/.github/workflows/release.yml
- native-provider-ci/providers/command/repo/.github/workflows/build.yml
- native-provider-ci/providers/command/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/command/repo/.github/workflows/release.yml
- native-provider-ci/providers/google-native/repo/.github/workflows/build.yml
- native-provider-ci/providers/google-native/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/google-native/repo/.github/workflows/release.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/build.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/release.yml
- native-provider-ci/src/steps.ts
Noticing that some native providers like k8s are laudably close to being cleanly managed by ci-mgmt; so I need to upstream this change here to reduce drift in their local scripts.
> Get compatible with pushing wheels to PyPI

- provider-ci/internal/pkg/templates/bridged-provider.config.yaml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/main.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/master.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/nightly-test.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/prerelease.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/release.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/run-acceptance-tests.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/update-bridge.yml
- provider-ci/providers/aws/config.yaml
- provider-ci/providers/aws/repo/.github/workflows/main.yml
- provider-ci/providers/aws/repo/.github/workflows/master.yml
- provider-ci/providers/aws/repo/.github/workflows/nightly-test.yml
- provider-ci/providers/aws/repo/.github/workflows/prerelease.yml
- provider-ci/providers/aws/repo/.github/workflows/release.yml
- provider-ci/providers/aws/repo/.github/workflows/run-acceptance-tests.yml
- provider-ci/providers/aws/repo/.github/workflows/update-bridge.yml
- provider-ci/providers/azure/config.yaml
- provider-ci/providers/azure/repo/.github/workflows/main.yml
- provider-ci/providers/azure/repo/.github/workflows/master.yml
- provider-ci/providers/azure/repo/.github/workflows/nightly-test.yml
- provider-ci/providers/azure/repo/.github/workflows/prerelease.yml
- provider-ci/providers/azure/repo/.github/workflows/release.yml
- provider-ci/providers/azure/repo/.github/workflows/run-acceptance-tests.yml
- provider-ci/providers/azure/repo/.github/workflows/update-bridge.yml
Fixes part of #554 
Extend the `runner` config option to include `buildSdk`. Follow up commits set `runner.buildSdk` to `pulumi-ubuntu-8core` for `aws` and `azure`.
> Parameterize by the runner used when building SDKs

- scripts/set-merge-commit-message-to-pr-title-and-body.sh
Per our discussion in ideation, I used this script to update the default squash/merge commit message settings to PR title+body. I was able to update most of the repositories we own except for these ones (which I apparently don't have permissions to update):
- pulumi/pulumi-awsx
- pulumi/pulumi-eks
- pulumi/action-test-provider-downstream
- pulumi/arm2pulumi
- pulumi/kube2pulumi
- pulumi/pulumi-aws-apigateway
- pulumi/pulumi-component-provider-py-boilerplate
- pulumi/pulumi-component-provider-ts-boilerplate
- pulumi/pulumi-provider-boilerplate
- pulumi/pulumictl
> Add script to update commit message settings

- provider-ci/Makefile
- provider-ci/actionlint.yml
Without this runner listed as a possibility in the Makefile the actions no longer pass actionlint.
> Permit custom self-hosted runner

- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/main.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/master.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/nightly-test.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/prerelease.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/release.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/run-acceptance-tests.yml
- provider-ci/providers/aws/repo/.github/workflows/main.yml
- provider-ci/providers/aws/repo/.github/workflows/master.yml
- provider-ci/providers/aws/repo/.github/workflows/nightly-test.yml
- provider-ci/providers/aws/repo/.github/workflows/prerelease.yml
- provider-ci/providers/aws/repo/.github/workflows/release.yml
- provider-ci/providers/aws/repo/.github/workflows/run-acceptance-tests.yml
- provider-ci/providers/azure/repo/.github/workflows/main.yml
- provider-ci/providers/azure/repo/.github/workflows/master.yml
- provider-ci/providers/azure/repo/.github/workflows/nightly-test.yml
- provider-ci/providers/azure/repo/.github/workflows/prerelease.yml
- provider-ci/providers/azure/repo/.github/workflows/release.yml
- provider-ci/providers/azure/repo/.github/workflows/run-acceptance-tests.yml
Looking at recent AWS PR failure, the test job is running out of disk space just as the build job does. Apply the same workaround by scheduling it on a more powerful runner.
https://github.com/pulumi/pulumi-aws/pull/2791
> Test providers on selfhosted runner

- provider-ci/providers/nomad/config.yaml
- provider-ci/providers/nomad/repo/.goreleaser.prerelease.yml
- provider-ci/providers/nomad/repo/.goreleaser.yml
- provider-ci/providers/nomad/repo/Makefile
Major version was bumped in https://github.com/pulumi/pulumi-nomad/pull/113. This brings the ci-mgmt files in line with the new version.
> Update for nomad major version bump

- provider-ci/internal/pkg/templates/bridged-provider/.goreleaser.prerelease.yml
- provider-ci/internal/pkg/templates/bridged-provider/.goreleaser.yml
- provider-ci/providers/gcp/config.yaml
- provider-ci/providers/gcp/repo/.goreleaser.prerelease.yml
- provider-ci/providers/gcp/repo/.goreleaser.yml
Fixes: https://github.com/pulumi/pulumi-gcp/issues/1161 via ci-mgmt so changes to the config files persist.
This is done by adding a new config to our goreleaser templates.
> Disable GoReleaser posthooks for GCP

- provider-ci/providers/tls/config.yaml
- provider-ci/providers/tls/repo/.goreleaser.prerelease.yml
- provider-ci/providers/tls/repo/.goreleaser.yml
- provider-ci/providers/tls/repo/Makefile
This reflects changes done to pulumi-tls repo today. These need to be in ci-mgmt so that nightly job does not roll them back.
> We now have TLS going back to 4.x

- provider-ci/providers/akamai/config.yaml
- provider-ci/providers/akamai/repo/.github/workflows/main.yml
- provider-ci/providers/akamai/repo/.github/workflows/master.yml
- provider-ci/providers/akamai/repo/.github/workflows/prerelease.yml
- provider-ci/providers/akamai/repo/.github/workflows/release.yml
- provider-ci/providers/akamai/repo/.github/workflows/run-acceptance-tests.yml
- provider-ci/providers/akamai/repo/.github/workflows/update-bridge.yml
- provider-ci/providers/datadog/config.yaml
- provider-ci/providers/datadog/repo/.github/workflows/main.yml
- provider-ci/providers/datadog/repo/.github/workflows/master.yml
- provider-ci/providers/datadog/repo/.github/workflows/prerelease.yml
- provider-ci/providers/datadog/repo/.github/workflows/release.yml
- provider-ci/providers/datadog/repo/.github/workflows/run-acceptance-tests.yml
- provider-ci/providers/datadog/repo/.github/workflows/update-bridge.yml
Followup for https://github.com/pulumi/pulumi-datadog/pull/330 and https://github.com/pulumi/pulumi-akamai/pull/271.
> DataDog and Akamai providers fail to build go sdk on default runners

- README.md
This was extremely helpful to have on hand while updating providers, so I thought I'd add it to the README.
> Add note for copying generated workflows into a locally checked out provider

- .github/workflows/update-bridge-ecosystem-providers.yml
- .github/workflows/update-bridge-single-ecosystem-provider.yml
Previous to this change, when the `upgrade-on-main` step failed, we would call `upgrade-on-master` every time, because the `if` condition on that step never made sense. 
But for providers where default branch is set to `main`, this would result in an overall failure, because `upgrade-on-master` does not specify `continue-on-error: true`. 
With this change, the `upgrade-on-master` step should no longer run at all for providers whose default branch is `main`. 
Note that using `github.event.repository.default_branch` is not available to us here, as that would detect the originating repo's (ci-mgmt's) default branch.
Furthermore, this PR adds a Workflow to update a single ecosystem provider, so we can optionally do gradual/test rollouts of updates.
Final note: There are a lot of "bridge …
> Fix default branch logic for Workflow dispatch of bridge upgrade

- .github/workflows/update-workflows.yml
Following up on https://github.com/pulumi/ci-mgmt/pull/610
There's a small block I've missed.  IN the case when patched upstream restoration is needed, current migration code would not work to automatically roll out Python wheels. This bit got lost when factoring out update-workflows.yml but I found it necessary for repos like pulumi-gcp and pulumi-aws. Adding it back. Ignoring errors so that repositories without a patched upstream are not affected.
> Init upstream if present before rebuilding Python SDK

- provider-ci/providers/signalfx/config.yaml
- provider-ci/providers/signalfx/repo/.goreleaser.prerelease.yml
- provider-ci/providers/signalfx/repo/.goreleaser.yml
- provider-ci/providers/signalfx/repo/Makefile
This should unblock automated workflow updates for it.
Applied in https://github.com/pulumi/pulumi-signalfx/pull/303
This fixes https://github.com/pulumi/ci-mgmt/issues/622
I've logged https://github.com/pulumi/upgrade-provider/issues/165 - there's some kind of process/sync failure that left signalfx in this unexpected state.
> Signalfx is now at v7

- .github/workflows/lint-ecosystem-providers.yml
Follow up on https://github.com/pulumi/ci-mgmt/pull/621 to get back to green.
We were getting a lot of lint errors when linting the bash produced by makefiles b/c pulumictl was not able to determine a version.
I added a tag to ci-mgmt, and added the steps to install pulumictl and to get a clone with tags and that seems to have been enough to get back to green.
> Fix lint job

- provider-ci/providers/confluentcloud/config.yaml
- provider-ci/providers/confluentcloud/repo/Makefile
The downstream Makefile was [manually edited to this version](https://github.com/pulumi/pulumi-confluentcloud/commit/4441db356984909297342397545a5a03f6ea6002), so now ci-mgmt cannot sync with this repo as CI fails with dirty worktree.
> Sync confluentcloud Java version with manually edited Makefile

- .github/workflows/update-workflows.yml
Storing .ci-mgmt.yaml in the provider's repository will enable single PR upgrades of:
- The java version
- Major provider version
- Everything else controlled by the config file
> Migrate config.yaml from ci-mgmt to the provider repo

- provider-ci/Makefile
- provider-ci/internal/pkg/templates/bridged-provider/Makefile
- provider-ci/test-workflows/aws/repo/Makefile
- provider-ci/test-workflows/cloudflare/repo/Makefile
- provider-ci/test-workflows/docker/repo/Makefile
This makes it easier to author PRs such as https://github.com/pulumi/pulumi-azuread/pull/490.
> Add a convenience target to locally regenerate workflow files

- provider-ci/internal/pkg/templates/bridged-provider/.upgrade-config.yml
- provider-ci/test-workflows/aws/.upgrade-config.yml
- provider-ci/test-workflows/cloudflare/.upgrade-config.yml
- provider-ci/test-workflows/docker/.upgrade-config.yml
We should specify the version we want. This is a step towards automatic java upgrades.
> upgrade-provider now allows users to target java versions

- .github/workflows/update-native-provider-workflows.yml
Only aws-native (and soon kubernetes(https://github.com/pulumi/ci-mgmt/pull/634)) get these updates, but if they build successfully, we should just let the bot merge them to reduce drift
> Enable automerge on the nightly workflow updates for native providers

- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/main.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/nightly-test.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/prerelease.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/release.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/run-acceptance-tests.yml
- provider-ci/internal/pkg/templates/bridged-provider/Makefile
- provider-ci/test-workflows/aws/.github/workflows/master.yml
- provider-ci/test-workflows/aws/.github/workflows/nightly-test.yml
- provider-ci/test-workflows/aws/.github/workflows/prerelease.yml
- provider-ci/test-workflows/aws/.github/workflows/release.yml
- provider-ci/test-workflows/aws/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-workflows/aws/Makefile
- provider-ci/test-workflows/cloudflare/.github/workflows/master.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/prerelease.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/release.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-workflows/cloudflare/Makefile
- provider-ci/test-workflows/docker/.github/workflows/master.yml
- provider-ci/test-workflows/docker/.github/workflows/prerelease.yml
- provider-ci/test-workflows/docker/.github/workflows/release.yml
- provider-ci/test-workflows/docker/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-workflows/docker/Makefile
Fixes https://github.com/pulumi/ci-mgmt/issues/661
The reason I'm working on this now is that I'd like to really move upgrade tests out of examples and under provider/ in AWS (and soon GCP). https://github.com/pulumi/pulumi-aws/pull/2855
> Add unit testing to the provider

- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/upgrade-bridge.yml
- provider-ci/test-workflows/aws/.github/workflows/upgrade-bridge.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/upgrade-bridge.yml
- provider-ci/test-workflows/docker/.github/workflows/upgrade-bridge.yml
Tested this PR and https://github.com/pulumi/ci-mgmt/tree/iwahbe/specify-identity-for-upgrade-provider on pulumi-databricks:
Automerge checked -> automerge is [workflow](https://github.com/pulumi/pulumi-databricks/actions/runs/6473730034/job/17577082331) ([PR](https://github.com/pulumi/pulumi-databricks/pull/217)).
Automerge not checked -> not auto merge is [workflow](https://github.com/pulumi/pulumi-databricks/actions/runs/6473158307/job/17575278570) ([PR](https://github.com/pulumi/pulumi-databricks/pull/216)).
> Allow automerge for bridge updates

- provider-ci/internal/pkg/templates/bridged-provider.config.yaml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/main.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/nightly-test.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/prerelease.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/release.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/run-acceptance-tests.yml
- provider-ci/providers/azure/config.yaml
This PR adds a new parameterized runner for the `prerequisite` job of each bridged CI workflow. The default is for this runner is still `ubuntu-latest`, but `pulumi-ubuntu-8core` is used for pulumi-azure to unblock the out of disk space issue.
> Use pulumi-ubuntu-8core runner for Azure prerequisites CI step

- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/main.yml
#671 incorrectly used `.Config.runner.prerequisites` for the `generate_coverage_data` job. This PR fixes the template.
> Fix: swap runner config for main.yaml template

- .github/workflows/update-workflows.yml
Since https://github.com/pulumi/ci-mgmt/pull/672, we no longer keep these files in the repo, so this migration will always fail. Also, they will no longer be invoked, since we have migrated all of our providers.
> Remove config migration

- .github/workflows/pull-request.yml
- .github/workflows/update-bridge-all-providers.yml
- .github/workflows/update-bridge-ecosystem-providers.yml
- .github/workflows/update-bridge-single-provider.yml
- .github/workflows/update-native-provider-workflows.yml
- .github/workflows/update-workflows-ecosystem-providers.yml
- .github/workflows/update-workflows.yml
We use actionlint to check our generated actions, but we don't employ it for our hand-written actions. This PR applies actionlint to the workflows used by this repo.
> Enable actionlint for ci-mgmt's workflows

- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/upgrade-bridge.yml
- provider-ci/test-workflows/aws/.github/workflows/upgrade-bridge.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/upgrade-bridge.yml
- provider-ci/test-workflows/docker/.github/workflows/upgrade-bridge.yml
When testing cross-repo dispatch where an action in pulumi-terraform-bridge is supposed to call and start an action in pulumi-aiven, I noticed that the dispatch event is quietly being lost. I think the piece edited here is the missing configuration to get this working.
This is now tested per https://github.com/pulumi/pulumi-terraform-bridge/pull/1442 and aiven.
> Permit x-repo triggers

- provider-ci/internal/pkg/templates/bridged-provider/Makefile
- provider-ci/test-workflows/aws/Makefile
Check adds TODOs to `replacements.json`. As of https://github.com/pulumi/pulumi-aws/pull/2886, it no longer works, since the `replacements.json` file has moved.
> Remove aws's Check (mirroring pulumi-aws)

- provider-ci/internal/pkg/templates/bridged-provider/.upgrade-config.yml
- provider-ci/test-workflows/aws/.upgrade-config.yml
- provider-ci/test-workflows/cloudflare/.upgrade-config.yml
- provider-ci/test-workflows/docker/.upgrade-config.yml
As of #705, Luke no longer needs to perform BUSL checks on upgrade PRs. This removes him from notifications.
Since I am temporarily running updates, I thought the team would appreciate not getting pinged on PRs that they don't need to address.
> Remove pulumi/Providers,lukehuban; add iwahbe as upgrade reviewer

- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-workflows/aws/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-workflows/docker/.github/workflows/run-acceptance-tests.yml
This PR should add a concurrency group for all providers' acceptance test workflows. This means that only a single workflow of that type can run per PR.  
Tested here:
https://github.com/pulumi/pulumi-aws/pull/2972
https://github.com/pulumi/pulumi-aws/actions/runs/6852384520 got canceled by https://github.com/pulumi/pulumi-aws/actions/runs/6852393776
> Acceptance tests concurrency group

- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-workflows/aws/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-workflows/docker/.github/workflows/run-acceptance-tests.yml
In context of https://github.com/pulumi/pulumi-aws/pull/3025 it would be great to be able to maintain multiple "main" branches, such as "v5" branch in AWS, and have tests qualify this branch and PRs targeting it. This change specifically enables testing PRs that target feature-* or v* branches.
> Test PRs targeting branches other than master

- .github/workflows/close-pulumi-bot-prs.yml
- scripts/close_outdated_bridge_prs.py
pulumi-bot opens lots of PRs. Because of the number of repos we maintain, all PRs that pulumi-bot opens that we want to merge are set to auto-merge. Other PRs are opened for test purposes, but we don't intend to merge these. We want to close these PRs after a couple of days to avoid them cluttering up the repo.
This adds a script (invoked every night on a cron) that cleans up PRs by `pulumi-bot` that are not set to auto-merge and that are older then 3 days old.
> Close outdated pulumi-bot PRs automatically

- scripts/close_outdated_bridge_prs.py
If labels have been applied to a PR, then assume a human will address it and don't close it. All upstream upgrade PRs have a `needs-release/{minor,patch}` label. Other upgrade PRs have `auto-merge` set (already handled).
> Don't close upgrade PRs

- provider-ci/internal/pkg/templates/bridged-provider.config.yaml
- provider-ci/test-workflows/docker/.github/workflows/master.yml
- provider-ci/test-workflows/docker/.github/workflows/prerelease.yml
- provider-ci/test-workflows/docker/.github/workflows/release.yml
- provider-ci/test-workflows/docker/.github/workflows/run-acceptance-tests.yml
We are getting [error annotations](https://github.com/pulumi/pulumi-docker/actions/runs/7094535875) on our workflow runs warning us of deprecation:
```
test (python)
The v0 series of google-github-actions/auth is no longer maintained. It will not receive updates, improvements, or security patches. Please upgrade to the latest supported versions: 
https://github.com/google-github-actions/auth
```
The main caveat is this update requires Node 20.0+. We have this set in the same config file so I don't anticipate an issue.
> Use updated google auth action

- provider-ci/internal/pkg/templates/bridged-provider/.gitattributes
- provider-ci/test-workflows/aws/.gitattributes
- provider-ci/test-workflows/cloudflare/.gitattributes
- provider-ci/test-workflows/docker/.gitattributes
This will help make PRs marginally easier to review by hiding some of the autogenerated noise.
See the [GitHub docs](https://docs.github.com/en/repositories/working-with-files/managing-files/customizing-how-changed-files-appear-on-github) for details.
> Automatically collapse generated SDKs in code review

- native-provider-ci/providers/aws-native/repo/.github/workflows/build.yml
- native-provider-ci/providers/aws-native/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/aws-native/repo/.github/workflows/release.yml
- native-provider-ci/providers/aws-native/repo/.github/workflows/run-acceptance-tests.yml
- native-provider-ci/providers/azure-native/repo/.github/workflows/build.yml
- native-provider-ci/providers/azure-native/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/azure-native/repo/.github/workflows/release.yml
- native-provider-ci/providers/azure-native/repo/.github/workflows/run-acceptance-tests.yml
- native-provider-ci/providers/google-native/repo/.github/workflows/build.yml
- native-provider-ci/providers/google-native/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/google-native/repo/.github/workflows/release.yml
- native-provider-ci/providers/google-native/repo/.github/workflows/run-acceptance-tests.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/build.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/release.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/run-acceptance-tests.yml
- native-provider-ci/src/steps.ts
The new version of schema-tools already presents a header, so no need to insert it again in the GitHub comment.
Example duplicate heading: https://github.com/pulumi/pulumi-kubernetes/pull/2697#issuecomment-1847777644
> Remove duplicate schema check headings in GH comment

- native-provider-ci/providers/kubernetes/config.yaml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/build.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/command-dispatch.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/pull-request.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/release.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/run-acceptance-tests.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/weekly-pulumi-update.yml
Replicates https://github.com/pulumi/pulumi-kubernetes/pull/2694 in [pulumi/ci-mgmt](https://github.com/pulumi/ci-mgmt)
> Update golangci-lint to v1.55.2 for Kubernetes

- provider-ci/internal/pkg/templates/bridged-provider/Makefile
- provider-ci/test-workflows/aws/Makefile
- provider-ci/test-workflows/cloudflare/Makefile
- provider-ci/test-workflows/docker/Makefile
When we `make` our provider, we compute the pulumi version from the go.mod file and write it to a `.pulumi` folder, so we can install pulumi there.
But when we then actually install pulumi in this folder, at least when run locally, it turns out that `$(cat .pulumi/version)` is not actually reading anything, even if the file exists. 
Instead, the latest pulumi version is used. This is probably mostly fine in practice, but obviously non-deterministic in nature.
A [quick check to a GA run](https://github.com/pulumi/pulumi-aws/actions/runs/7169609015/job/19520393449#step:10:36) shows that this is not working correctly in Actions, either. 
Locally, for me, `$(shell cat .pulumi/version)` works instead. This PR adds that change.
> Correctly read Pulumi version from  folder when installing pulumi

- scripts/close_outdated_bridge_prs.py
Fixes https://github.com/pulumi/ci-mgmt/issues/743
In #730, @iwahbe added logic  to avoid closing PRs that have a label on them b/c this probably indicates a human is working on that PR.
Unfortunately, python throws a `KeyError` rather than returning `None` when it can't find a key in a dict, so this broke ci for issues that don't have labels.
This change should fix the code to match the intent.
> Fix KeyError in close_outdated_bridge_prs.py

- native-provider-ci/providers/kubernetes/repo/.github/workflows/build.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/release.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/run-acceptance-tests.yml
- native-provider-ci/src/steps.ts
Our CI cluster will (soon) be pinned to Kubernetes v1.28. To prevent skew between the API server and kubectl client version, this PR pins the installed kubectl to v1.28.
> Pin kubectl to v1.28

- provider-ci/internal/pkg/templates/bridged-provider.config.yaml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/upgrade-bridge.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/upgrade-provider.yml
- provider-ci/internal/pkg/templates/bridged-provider/.upgrade-config.yml
- provider-ci/internal/pkg/templates/bridged-provider/Makefile
- provider-ci/providers/aws/config.yaml
- provider-ci/providers/docker/config.yaml
- provider-ci/test-workflows/aws/.github/workflows/upgrade-bridge.yml
- provider-ci/test-workflows/aws/.github/workflows/upgrade-provider.yml
- provider-ci/test-workflows/aws/.upgrade-config.yml
- provider-ci/test-workflows/aws/Makefile
- provider-ci/test-workflows/cloudflare/.github/workflows/upgrade-bridge.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/upgrade-provider.yml
- provider-ci/test-workflows/cloudflare/Makefile
- provider-ci/test-workflows/docker/.github/workflows/upgrade-bridge.yml
- provider-ci/test-workflows/docker/.github/workflows/upgrade-provider.yml
- provider-ci/test-workflows/docker/.upgrade-config.yml
- provider-ci/test-workflows/docker/Makefile
As part of https://github.com/pulumi/ci-mgmt/issues/506, we are setting the Java version in a provider-level version file, acting as our "lockfile". 
This PR mainly updates the provider Makefiles to be in sync with the changes propagated with the latest  (and hopefully last) bulk Java upgrade. [Sample update here](https://github.com/pulumi/pulumi-civo/pull/348). The rollout has been a bit messy; there are currently failing updates in a few providers. They should clear up as soon as this change is merged.
> Update Makefile detection of java version

- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/upgrade-provider.yml
- provider-ci/test-workflows/aws/.github/workflows/upgrade-provider.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/upgrade-provider.yml
- provider-ci/test-workflows/docker/.github/workflows/upgrade-provider.yml
This avoids accidental upgrades such as those caused by https://github.com/pulumi/pulumi-aws/issues/3160.
--- 
I will test before merging:
- Does not fire on user (non `Pulumi-bot` issues): https://github.com/pulumi/pulumi-linode/actions/runs/7279564493
- Does fire on `Pulumi-bot` issues: https://github.com/pulumi/pulumi-linode/actions/runs/7279555195
> Only fire upgrades on pulumi bot issues

- provider-ci/internal/pkg/templates/bridged-provider.config.yaml
- provider-ci/providers/aws/config.yaml
- provider-ci/providers/cloudflare/config.yaml
- provider-ci/providers/docker/config.yaml
- provider-ci/test-workflows/aws/.github/workflows/master.yml
- provider-ci/test-workflows/aws/.github/workflows/nightly-test.yml
- provider-ci/test-workflows/aws/.github/workflows/prerelease.yml
- provider-ci/test-workflows/aws/.github/workflows/release.yml
- provider-ci/test-workflows/aws/.github/workflows/resync-build.yml
- provider-ci/test-workflows/aws/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/master.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/prerelease.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/release.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/resync-build.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-workflows/docker/.github/workflows/master.yml
- provider-ci/test-workflows/docker/.github/workflows/prerelease.yml
- provider-ci/test-workflows/docker/.github/workflows/release.yml
- provider-ci/test-workflows/docker/.github/workflows/resync-build.yml
- provider-ci/test-workflows/docker/.github/workflows/run-acceptance-tests.yml
Noticing that AWS was testing against outdated CLI v3.77.1. This is unfortunate. 
This change gets it back to floating as all the other providers. All the other providers are updated to use the latest recommended GitHub action.
I have slight preference for pinned and weekly updating but that's more setup, for now floating is better than pinned indefinitely in the past.
> Fix setup pulumi pin

- scripts/ensure_release_labels.py
I used this script to systemically set up `needs-release/*` labels in all our providers. I'm checking it in to avoid duplication of work for future label changes.
> Add deploy release labels script

- .github/workflows/merge-dependabot.yml
This gives us the ability to retry individually failed jobs, which is important since this script fails when GH has left stale dependabot PRs in a repo (for example: https://github.com/pulumi/pulumi-null/pull/1).
> Merge Dependabot PRs: Put each provider into it's own job

- provider-ci/internal/pkg/templates/bridged-provider.config.yaml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/main.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/prerelease.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/release.yml
- provider-ci/test-workflows/aws/.github/workflows/master.yml
- provider-ci/test-workflows/aws/.github/workflows/prerelease.yml
- provider-ci/test-workflows/aws/.github/workflows/release.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/master.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/prerelease.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/release.yml
- provider-ci/test-workflows/docker/.github/workflows/master.yml
- provider-ci/test-workflows/docker/.github/workflows/prerelease.yml
- provider-ci/test-workflows/docker/.github/workflows/release.yml
This allows each repo to opt in or out of publishing different SDKs.
This is necessary for pulumi-local, since we are unable to publish the `pulumi-local` python SDK.
> Upgrade publish workflow to v0.0.13

- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/main.yml
- provider-ci/test-workflows/aws/.github/workflows/master.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/master.yml
- provider-ci/test-workflows/docker/.github/workflows/master.yml
We run this during upgrade workflows so they should run during normal CI.
Should prevent errors like https://github.com/pulumi/pulumi-keycloak/issues/355
> Error on missing docs during tfgen

- provider-ci/internal/pkg/templates/bridged-provider.config.yaml
- provider-ci/internal/pkg/templates/bridged-provider/.upgrade-config.yml
- provider-ci/providers/docker/config.yaml
- provider-ci/test-workflows/docker/.upgrade-config.yml
Part of https://github.com/pulumi/upgrade-provider/issues/221 - refer to issue for details.
Explicitly telling our upgrade machinery the upstream org name allows us to reliably detect upstream upgrades every time.
> Option to set upstream provider org in upgrade config

- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/upgrade-bridge.yml
- provider-ci/test-workflows/aws/.github/workflows/upgrade-bridge.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/upgrade-bridge.yml
- provider-ci/test-workflows/docker/.github/workflows/upgrade-bridge.yml
Part of https://github.com/pulumi/pulumi/issues/15140
This parameterizes the kind run on upgrade-provider to enable downstream codegen tests to only upgrade pulumi (they currently may upgrade the bridge which could cause the bridge to block pulumi/pulumi releases).
We could copy the job as well to an `upgrade-pulumi.yml`, but I'm unfamiliar with the repository so I'm unsure of the consequences of such an approach.
> Parameterize upgrade-bridge job kind

- provider-ci/internal/pkg/templates/bridged-provider/.golangci.yml
- provider-ci/internal/pkg/templates/bridged-provider/Makefile
- provider-ci/test-workflows/aws/.golangci.yml
- provider-ci/test-workflows/aws/Makefile
- provider-ci/test-workflows/cloudflare/.golangci.yml
- provider-ci/test-workflows/cloudflare/Makefile
- provider-ci/test-workflows/docker/.golangci.yml
- provider-ci/test-workflows/docker/Makefile
This PR adds the [gci linter](https://github.com/daixiang0/gci) to the enabled Go linters. Additionally adds a `lint_provider.fix` Make target that maintainers may run locally to help fix linting errors.
The custom order for the import blocks is defined as follows:
- standard library imports
- blank imports
- default imports
- pulumi/* imports
- local imports (i.e. within the provider repo itself.
A typical import section in `resources.go` would look like this:
```
package cloudinit
import (
"fmt"
"path/filepath"
"unicode"
// embed is used to store bridge-metadata.json in the compiled binary
_ "embed"
"github.com/hashicorp/terraform-provider-cloudinit/shim"
pf "github.com/pulumi/pulumi-terraform-bridge/pf/tfbridge"
"github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge"
tfbridgetokens …
```
> Enable `gci` linter to sort and group imports

- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/upgrade-bridge.yml
- provider-ci/test-workflows/aws/.github/workflows/upgrade-bridge.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/upgrade-bridge.yml
- provider-ci/test-workflows/docker/.github/workflows/upgrade-bridge.yml
After https://github.com/pulumi/ci-mgmt/pull/775 the downstream checks are no longer working for testing the bridge because it invokes upgrade-provider with `kind=""`. Note that `inputs` are not defined when processing `repository_dispatch`, so the code has to work around that.
> Fix upgrade-bridge job

- native-provider-ci/providers/aws-native/repo/.github/workflows/build.yml
- native-provider-ci/providers/aws-native/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/aws-native/repo/.github/workflows/release.yml
- native-provider-ci/providers/azure-native/repo/.github/workflows/build.yml
- native-provider-ci/providers/azure-native/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/azure-native/repo/.github/workflows/release.yml
- native-provider-ci/providers/command/repo/.github/workflows/build.yml
- native-provider-ci/providers/command/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/command/repo/.github/workflows/release.yml
- native-provider-ci/providers/google-native/repo/.github/workflows/build.yml
- native-provider-ci/providers/google-native/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/google-native/repo/.github/workflows/release.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/build.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/release.yml
- native-provider-ci/src/action-versions.ts
We have a number of security alerts like [this one](https://github.com/pulumi/pulumi-aws-native/security/dependabot/54) that have been open for ~9 months.
Un-pinning the affected action should resolve the issue.
> Resolve security alerts due to old gradle-build-action

- native-provider-ci/providers/aws-native/repo/.github/workflows/weekly-pulumi-update.yml
- native-provider-ci/providers/azure-native/repo/.github/workflows/weekly-pulumi-update.yml
- native-provider-ci/providers/command/repo/.github/workflows/weekly-pulumi-update.yml
- native-provider-ci/providers/google-native/repo/.github/workflows/weekly-pulumi-update.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/weekly-pulumi-update.yml
- native-provider-ci/src/steps.ts
- native-provider-ci/src/workflows.ts
Our automation around pu/pu bumps doesn't catch every directory, e.g. `examples/go.mod` is often stale.
This is a source of dependabot noise. Updating pu/pu often has a side-effect of resolving security issues (since pu/pu is constantly bumping minimum revs). For the directories that don't bump pu/pu we end up needing followup from dependabot.
Re: special casing for p/kubernetes, AFAICT there's no behavioral difference with what we have right now. p/kubernetes skips the `go mod download` step, but `go mod tidy` does this automatically; it also runs `make ensure` at the end, but that just runs `go mod tidy`.
> Upgrade all pu/pu dependencies

- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-workflows/aws/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-workflows/docker/.github/workflows/run-acceptance-tests.yml
I found it surprising when trying to [stack](https://stacking.dev) some PRs that we don't run tests unless the PR is explicitly against master. This is [awkward](https://github.com/pulumi/pulumi-docker/pull/948#issuecomment-1897531359) to work with.
This PR changes our workflow to trigger for PRs against any branch. I might be missing some context around #723 and why we chose to opt-in only some patterns, but if there are automated flows that shouldn't run tests I recommend we opt those out explicitly.
> Run acceptance tests on all branch targets

- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/license.yml
- provider-ci/test-workflows/aws/.github/workflows/license.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/license.yml
- provider-ci/test-workflows/docker/.github/workflows/license.yml
[github.com/in-toto/in-toto-golang](https://github.com/in-toto/in-toto-golang) has an [Apache 2.0 license](https://github.com/in-toto/in-toto-golang/blob/v0.5.0/LICENSE) and is a dependency of newer [github.com/docker/buildx](https://github.com/docker/buildx) releases, but it's incorrectly flagged by the license check action.
This PR adds it to our ignore list.
Refs https://github.com/pulumi/license-check-action/issues/2
Unblocks https://github.com/pulumi/pulumi-docker/pull/898
```
❯ go mod graph | grep in-toto
github.com/pulumi/pulumi-docker/provider/v4 github.com/in-toto/in-toto-golang@v0.5.0
github.com/docker/buildx@v0.12.0 github.com/in-toto/in-toto-golang@v0.5.0
github.com/in-toto/in-toto-golang@v0.5.0 github.com/google/go-cmp@v0.5.9
github.com/in-toto/in-toto-golang@v0.5.0 …
```
> Add github.com/in-toto/in-toto-golang to license check ignore

- README.md
Updates the instructions for adding a new bridged provider to our internal automation ecosystem.
This pull request falls short of adding full documentation for possible config settings, which is more involved and needs a follow-up, but it corrects out of date information.
> Update provider onboarding instructions

- provider-ci/Makefile
- provider-ci/internal/pkg/templates/bridged-provider/Makefile
- provider-ci/test-workflows/aws/Makefile
- provider-ci/test-workflows/cloudflare/Makefile
- provider-ci/test-workflows/docker/Makefile
The Makefile uses a trick to get a Pulumi CLI version that matches the provider/go.mod dependency on pkg. However since we did not explain to Make that reading go.mod is literally a dependency here, @guineveresaenger machine got into a state where `make` locally was using an out-of-date Pulumi CLI compared to CI. This is probably benign just yet, but with turning on example conversion via Pulumi CLI we can easily get this to produce discrepancies in generated examples between local and CI.
> Add gomod Make dependency

- native-provider-ci/providers/aws-native/repo/.github/workflows/nightly-sdk-generation.yml
- native-provider-ci/providers/aws-native/repo/.github/workflows/run-acceptance-tests.yml
- native-provider-ci/providers/aws-native/repo/.github/workflows/weekly-pulumi-update.yml
- native-provider-ci/providers/azure-native/repo/.github/workflows/nightly-sdk-generation.yml
- native-provider-ci/providers/azure-native/repo/.github/workflows/run-acceptance-tests.yml
- native-provider-ci/providers/azure-native/repo/.github/workflows/weekly-pulumi-update.yml
- native-provider-ci/providers/command/repo/.github/workflows/run-acceptance-tests.yml
- native-provider-ci/providers/command/repo/.github/workflows/weekly-pulumi-update.yml
- native-provider-ci/providers/google-native/repo/.github/workflows/run-acceptance-tests.yml
- native-provider-ci/providers/google-native/repo/.github/workflows/weekly-pulumi-update.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/build.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/release.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/run-acceptance-tests.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/weekly-pulumi-update.yml
- native-provider-ci/src/steps.ts
This is a followup to my previous PR here: https://github.com/pulumi/pulumi-aws-native/pull/1283
Based on @mjeffryes's helpful direction there, this PR updates the usage of `::set-output` to `"$GITHUB_OUTPUT"` format for all provider workflow files. [The former command is deprecated by GitHub](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/).
Instructions for envvar usage from GitHub docs:
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter
> Update set-output command references in the generator for all providers to $GITHUB_OUTPUT

- .github/workflows/pull-request.yml
- native-provider-ci/providers/aws-native/repo/.github/workflows/build.yml
- native-provider-ci/providers/aws-native/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/aws-native/repo/.github/workflows/release.yml
- native-provider-ci/providers/azure-native/repo/.github/workflows/build.yml
- native-provider-ci/providers/azure-native/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/azure-native/repo/.github/workflows/release.yml
- native-provider-ci/providers/command/repo/.github/workflows/build.yml
- native-provider-ci/providers/command/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/command/repo/.github/workflows/release.yml
- native-provider-ci/providers/google-native/repo/.github/workflows/build.yml
- native-provider-ci/providers/google-native/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/google-native/repo/.github/workflows/release.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/build.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/release.yml
- native-provider-ci/src/action-versions.ts
As noted in https://github.com/pulumi/pulumi-kubernetes/pull/2795#issuecomment-1919552728, we need to bump the version used here for repositories that are managed under ci-mgmt/native-provider-ci
> Update gradle-build-action version for native providers

- native-provider-ci/providers/command/repo/.github/workflows/build.yml
- native-provider-ci/providers/command/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/command/repo/.github/workflows/release.yml
- native-provider-ci/providers/command/repo/.github/workflows/run-acceptance-tests.yml
- native-provider-ci/src/workflows.ts
- scripts/generate_native_providers_list.py
I tested updating pulumi-command's workflows in https://github.com/pulumi/pulumi-command/pull/329/files and it showed very little drift from the current state of ci-mgmt, so I think it should be safe to turn on automated PRs for the repo.
The only change I made was to keep runners on ubuntu-latest instead of 8core.
> Enable ci-mgmt for pulumi-command

- provider-ci/internal/pkg/templates/bridged-provider/Makefile
- provider-ci/test-workflows/aws/Makefile
- provider-ci/test-workflows/cloudflare/Makefile
- provider-ci/test-workflows/docker/Makefile
This seems to be an omission that's needed to rollout the converter. Without it I noticed in https://github.com/pulumi/pulumi-azure/pull/1377 that only Java examples are changing.
> Propagate pulumi convert setting to tfgen

- provider-ci/internal/pkg/templates/bridged-provider/scripts/upstream.sh
- provider-ci/test-workflows/aws/scripts/upstream.sh
- provider-ci/test-workflows/cloudflare/scripts/upstream.sh
- provider-ci/test-workflows/docker/scripts/upstream.sh
When calling make upstream that fails on applying a patch, I would love too see immediately which patch failed. This helps fix that one.
> Show which patch failed

- provider-ci/internal/pkg/templates/bridged-provider.config.yaml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/main.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/nightly-test.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/prerelease.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/prerequisites.splice
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/release.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/resync-build.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-workflows/aws/.github/workflows/master.yml
- provider-ci/test-workflows/aws/.github/workflows/nightly-test.yml
- provider-ci/test-workflows/aws/.github/workflows/prerelease.yml
- provider-ci/test-workflows/aws/.github/workflows/release.yml
- provider-ci/test-workflows/aws/.github/workflows/resync-build.yml
- provider-ci/test-workflows/aws/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/master.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/prerelease.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/release.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/resync-build.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-workflows/docker/.github/workflows/master.yml
- provider-ci/test-workflows/docker/.github/workflows/prerelease.yml
- provider-ci/test-workflows/docker/.github/workflows/release.yml
- provider-ci/test-workflows/docker/.github/workflows/resync-build.yml
- provider-ci/test-workflows/docker/.github/workflows/run-acceptance-tests.yml
Use a specific tag for pulumiCtl. This speed up installing it and avoids putting pressure on the API rate limits for determining the latest release of a dependency in our builds such as https://github.com/pulumi/pulumi-azuredevops/pull/292
> Pin pulumictl

- provider-ci/internal/pkg/templates/bridged-provider.config.yaml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/main.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/nightly-test.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/prerelease.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/prerequisites.splice
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/release.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-workflows/aws/.github/workflows/master.yml
- provider-ci/test-workflows/aws/.github/workflows/nightly-test.yml
- provider-ci/test-workflows/aws/.github/workflows/prerelease.yml
- provider-ci/test-workflows/aws/.github/workflows/release.yml
- provider-ci/test-workflows/aws/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/master.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/prerelease.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/release.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-workflows/docker/.github/workflows/master.yml
- provider-ci/test-workflows/docker/.github/workflows/prerelease.yml
- provider-ci/test-workflows/docker/.github/workflows/release.yml
- provider-ci/test-workflows/docker/.github/workflows/run-acceptance-tests.yml
This is a slow-moving legacy dependency, I'm hoping that pinning it can help actions/checkout to be better at caching or not failing around exhausting GH tokens as in:
FAILED https://github.com/pulumi/pulumi-azuredevops/pull/293
FAILED https://github.com/pulumi/pulumi-azuredevops/pull/292
> Pin pulumi/scripts checkout

- provider-ci/internal/pkg/templates/bridged-provider/scripts/upstream.sh
- provider-ci/test-workflows/aws/scripts/upstream.sh
- provider-ci/test-workflows/cloudflare/scripts/upstream.sh
- provider-ci/test-workflows/docker/scripts/upstream.sh
The command assumes you've already committed the upstream subrepo with the new commit.  
This makes it quite confusing if you haven't since `upstream.sh` will reset the subrepo.  
Specifying `TO` doesn't assume that.
> Clarify command for rebase

- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/lint.yml
- provider-ci/test-workflows/aws/.github/workflows/lint.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/lint.yml
- provider-ci/test-workflows/docker/.github/workflows/lint.yml
This was necessary to unblock the [azure provider
upgrade](https://github.com/pulumi/pulumi-azure/actions/runs/7892457062/job/21538972574?pr=1711).
> Upgrade golangci-lint version

- native-provider-ci/src/action-versions.ts
- provider-ci/internal/pkg/templates/bridged-provider.config.yaml
- provider-ci/test-workflows/aws/.github/workflows/master.yml
- provider-ci/test-workflows/aws/.github/workflows/prerelease.yml
- provider-ci/test-workflows/aws/.github/workflows/release.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/master.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/prerelease.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/release.yml
- provider-ci/test-workflows/docker/.github/workflows/master.yml
- provider-ci/test-workflows/docker/.github/workflows/prerelease.yml
- provider-ci/test-workflows/docker/.github/workflows/release.yml
Upgrades to https://github.com/pulumi/pulumi-package-publisher/releases/tag/v0.0.14, fixing the problem introduced in #818.
> Consume pulumi-package-publisher@v0.0.14

- provider-ci/internal/pkg/templates/bridged-provider.config.yaml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-workflows/aws/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-workflows/docker/.github/workflows/run-acceptance-tests.yml
This change adds a new optional flag `testPulumiExamples` that can be set in .ci-mgmt.yaml. When set, the acceptance tests in pulumi/examples will be run as part of the test suite.
The goal is to increase test coverage in provider PRs or releases. `pulumi/examples` has a rich set of realistic programs that can be used for this via ProgramTest.
Providers don't necessarily need to gate PRs on these tests, they can be informational only.
This requires that the provider's test suite in `examples/` is enabled for this. See pulumi/pulumi-azure#1717 for an example. It's not enough to just run the test suite in pulumi/examples because we want to use or inject the locally built provider and SDKs of the current PR.
I chose the approach using the test job's matrix because the new pulumi/examples …
> Allow running the acceptance tests in pulumi/examples as part of the test suite

- provider-ci/internal/pkg/templates/bridged-provider/Makefile
- provider-ci/test-workflows/aws/Makefile
- provider-ci/test-workflows/cloudflare/Makefile
- provider-ci/test-workflows/docker/Makefile
This save some disk space and allows AWS to run on normal runners.
Tested in https://github.com/pulumi/pulumi-aws/pull/3469
> Clean go sdk build artifacts

- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/main.yml
- provider-ci/test-workflows/aws/.github/workflows/master.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/master.yml
- provider-ci/test-workflows/docker/.github/workflows/master.yml
We saw some failures in AWS: https://github.com/pulumi/pulumi-aws/actions/runs/8076447038/job/22065470841
tested in https://github.com/pulumi/pulumi-aws/actions/runs/8079968659/job/22075523684?pr=3507
> Clean up disk space for coverage job

- provider-ci/internal/pkg/templates/bridged-provider/Makefile
- provider-ci/test-workflows/aws/Makefile
- provider-ci/test-workflows/cloudflare/Makefile
- provider-ci/test-workflows/docker/Makefile
In provider makefiles, the `test` target doesn't seem to work because the examples cannot find the built provider.  The fix is simply to add the provider build directory to the path. That's what the CI script does when running the tests (see [code](https://github.com/pulumi/ci-mgmt/blob/1971f54d81598729424c636745ba961ee6432783/provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/run-acceptance-tests.yml#L271-L272)).
> Add provider bin to PATH for test target

- provider-ci/internal/pkg/templates/bridged-provider/Makefile
- provider-ci/test-workflows/aws/Makefile
- provider-ci/test-workflows/cloudflare/Makefile
- provider-ci/test-workflows/docker/Makefile
This PR updates the provider makefile to use a localized plugin directory (and the localized Pulumi installation) for all code generation tasks.
Note that the other tasks (e.g. `install_sdks`, `test`) do not use the localized Pulumi installation or plugin directory.
Closes #832
> Localize plugin set

- provider-ci/internal/pkg/templates/bridged-provider.config.yaml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/upgrade-bridge.yml
- provider-ci/test-workflows/aws/.github/workflows/upgrade-bridge.yml
- provider-ci/test-workflows/aws/.github/workflows/upgrade-provider.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/upgrade-bridge.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/upgrade-provider.yml
- provider-ci/test-workflows/docker/.github/workflows/upgrade-bridge.yml
- provider-ci/test-workflows/docker/.github/workflows/upgrade-provider.yml
Propagate https://github.com/pulumi/pulumi-upgrade-provider-action/pull/25 and https://github.com/pulumi/upgrade-provider/pull/252 to ci-mgmt.
Only pu/pu (and bridge) left...
> Propagate title prefix arg to ci-mgmt

- native-provider-ci/providers/aws-native/repo/.github/workflows/build.yml
- native-provider-ci/providers/aws-native/repo/.github/workflows/cf2pulumi-release.yml
- native-provider-ci/providers/aws-native/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/aws-native/repo/.github/workflows/release.yml
- native-provider-ci/providers/azure-native/repo/.github/workflows/arm2pulumi-release.yml
- native-provider-ci/providers/azure-native/repo/.github/workflows/build.yml
- native-provider-ci/providers/azure-native/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/azure-native/repo/.github/workflows/release.yml
- native-provider-ci/providers/command/repo/.github/workflows/build.yml
- native-provider-ci/providers/command/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/command/repo/.github/workflows/release.yml
- native-provider-ci/providers/google-native/repo/.github/workflows/build.yml
- native-provider-ci/providers/google-native/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/google-native/repo/.github/workflows/release.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/build.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/release.yml
- native-provider-ci/src/action-versions.ts
- native-provider-ci/src/steps.ts
- native-provider-ci/src/workflows.ts
The Kubernetes builds recently started running out of disk during publish. Hoping that this will fix the problem.
Also address some deprecation warnings from goreleaser.
Fixes: https://github.com/pulumi/pulumi-kubernetes/issues/2867
> Reclaim some disk space in release jobs

- native-provider-ci/providers/aws-native/repo/.github/workflows/build.yml
- native-provider-ci/providers/aws-native/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/aws-native/repo/.github/workflows/release.yml
- native-provider-ci/providers/azure-native/repo/.github/workflows/build.yml
- native-provider-ci/providers/azure-native/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/azure-native/repo/.github/workflows/release.yml
- native-provider-ci/providers/command/repo/.github/workflows/build.yml
- native-provider-ci/providers/command/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/command/repo/.github/workflows/release.yml
- native-provider-ci/providers/google-native/repo/.github/workflows/build.yml
- native-provider-ci/providers/google-native/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/google-native/repo/.github/workflows/release.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/build.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/release.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/run-acceptance-tests.yml
- native-provider-ci/src/action-versions.ts
- native-provider-ci/src/steps.ts
- native-provider-ci/src/workflows.ts
Replicates changes in:
- https://github.com/pulumi/pulumi-kubernetes/pull/2875
- https://github.com/pulumi/pulumi-kubernetes/pull/2831
Fixes: https://github.com/pulumi/pulumi-kubernetes/issues/2878
> Update pulumi-kubernetes workflows to use kind and free up disk space

- provider-ci/internal/pkg/templates/bridged-provider/Makefile
- provider-ci/test-workflows/aws/Makefile
- provider-ci/test-workflows/cloudflare/Makefile
- provider-ci/test-workflows/docker/Makefile
This PR adds two commands to make debugging `tfgen` for bridged providers easier.
1. `tfgen_build_only`: Only builds to `tfgen` binary, doesn't run generate. When debugging if you need to rebuild tfgen, you don't need to re-run all the other stuff too.
2. `debug_tfgen`: Starts `tfgen` as a debug server. Instructions on how to debug `tfgen` are being added to the docs in https://github.com/pulumi/pulumi-hugo/pull/4067
> chore: add commands for debugging tfgen

- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/upgrade-bridge.yml
- provider-ci/test-workflows/aws/.github/workflows/upgrade-bridge.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/upgrade-bridge.yml
- provider-ci/test-workflows/docker/.github/workflows/upgrade-bridge.yml
When you trigger a workflow via a repository_dispatch, you have to specify a custom `type`. This type appears in the workflow_run webhook event so it can be used to filter different types of runs.
I'm adding a new type `upgrade-bridge-test` which can be used by the downstream test workflows. This will allow us to [filter out those workflow runs](https://github.com/pulumi/home/pull/3359) from creating p1 tickets.
re https://github.com/pulumi/ci-mgmt/issues/815
> chore: add `upgrade-bridge-test` as possible repository_dispatch type

- native-provider-ci/providers/kubernetes/repo/.github/workflows/build.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/run-acceptance-tests.yml
- native-provider-ci/src/steps.ts
- native-provider-ci/src/workflows.ts
We default to [`lint: true`](https://github.com/pulumi/ci-mgmt/blob/master/native-provider-ci/src/workflows.ts#L19), which is good, but then we only add a lint job for the Kubernetes provider.
This PR fixes the lint job to be added whenever `opts.lint` is `true`, and it changes the job's working directory to just `provider`. This is backwards-compatible with the kubernetes provider's current usage and doesn't require new providers to have an unidiomatic `pkg` directory.
(A directory that exists only to hold other packages is a potential design smell -- as [Dave Cheney](https://dave.cheney.net/2019/10/06/use-internal-packages-to-reduce-your-public-api-surface) puts it.)
> Fix lint step for new providers

- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/prerequisites.splice
- provider-ci/test-workflows/aws/.github/workflows/master.yml
- provider-ci/test-workflows/aws/.github/workflows/nightly-test.yml
- provider-ci/test-workflows/aws/.github/workflows/prerelease.yml
- provider-ci/test-workflows/aws/.github/workflows/release.yml
- provider-ci/test-workflows/aws/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/master.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/prerelease.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/release.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-workflows/docker/.github/workflows/master.yml
- provider-ci/test-workflows/docker/.github/workflows/prerelease.yml
- provider-ci/test-workflows/docker/.github/workflows/release.yml
- provider-ci/test-workflows/docker/.github/workflows/run-acceptance-tests.yml
fixes https://github.com/pulumi/pulumi-terraform-bridge/issues/1585
This PR adds a check in bridged provider CI for configuration options in README.md.
CI will now comment on PRs if any configuration options are missing in the README.md
Tested in https://github.com/pulumi/pulumi-github/pull/615 and https://github.com/pulumi/pulumi-xyz/pull/31
> Add a config section check for bridged providers

- .github/workflows/update-workflows.yml
Seems like in https://github.com/pulumi/ci-mgmt/pull/855 we regressed and update PRs are now called `falseUpdate GitHub Actions workflows.`
example: https://github.com/pulumi/pulumi-gcp/pull/1878
this should fix it and correctly return them to `Update GitHub Actions workflows.`
> Fix update workflows PRs title

- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/prerequisites.splice
- provider-ci/internal/pkg/templates/bridged-provider/Makefile
- provider-ci/test-workflows/aws/.github/workflows/master.yml
- provider-ci/test-workflows/aws/.github/workflows/nightly-test.yml
- provider-ci/test-workflows/aws/.github/workflows/prerelease.yml
- provider-ci/test-workflows/aws/.github/workflows/release.yml
- provider-ci/test-workflows/aws/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-workflows/aws/Makefile
- provider-ci/test-workflows/cloudflare/.github/workflows/master.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/prerelease.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/release.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-workflows/cloudflare/Makefile
- provider-ci/test-workflows/docker/.github/workflows/master.yml
- provider-ci/test-workflows/docker/.github/workflows/prerelease.yml
- provider-ci/test-workflows/docker/.github/workflows/release.yml
- provider-ci/test-workflows/docker/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-workflows/docker/Makefile
It appears helpful to split out individual activities related to `make tfgen` into separate GitHub Action steps so we can see how much time they take and peruse their logs individually.
> Split out tfgen steps in CI

- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/prerequisites.splice
- provider-ci/test-workflows/aws/.github/workflows/master.yml
- provider-ci/test-workflows/aws/.github/workflows/nightly-test.yml
- provider-ci/test-workflows/aws/.github/workflows/prerelease.yml
- provider-ci/test-workflows/aws/.github/workflows/release.yml
- provider-ci/test-workflows/aws/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/master.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/prerelease.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/release.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-workflows/docker/.github/workflows/master.yml
- provider-ci/test-workflows/docker/.github/workflows/prerelease.yml
- provider-ci/test-workflows/docker/.github/workflows/release.yml
- provider-ci/test-workflows/docker/.github/workflows/run-acceptance-tests.yml
Running some experiments in pulumi-aws I found that for simple PRs that edit tests or resources.go it's really nice to have accurate Go cache. Specifically prerequisites job cache should be keyed on upstream/go.sum and provider/go.sum; if that is done than cache hits mean no additional go package downloading is happening, greatly speeding up builds (I got ranges from 3min to 20min, with 3 min on hot caches). 
I think some of the prior thinking here was that using an approximate cache key would allow to reuse some of the cache even when bridge or upstream upgrades are happening. However when inaccurate cache is downloaded, Go proceeds to download the actual dependences, which in AWS case are significant, causing us to run out of disk space. To compensate, we installed a disk space cleaner …
> Accurate go cache for prerequisites

- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/prerequisites.splice
- provider-ci/test-workflows/aws/.github/workflows/master.yml
- provider-ci/test-workflows/aws/.github/workflows/nightly-test.yml
- provider-ci/test-workflows/aws/.github/workflows/prerelease.yml
- provider-ci/test-workflows/aws/.github/workflows/release.yml
- provider-ci/test-workflows/aws/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/master.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/prerelease.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/release.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-workflows/docker/.github/workflows/master.yml
- provider-ci/test-workflows/docker/.github/workflows/prerelease.yml
- provider-ci/test-workflows/docker/.github/workflows/release.yml
- provider-ci/test-workflows/docker/.github/workflows/run-acceptance-tests.yml
My jq syntax in https://github.com/pulumi/ci-mgmt/pull/862 was off yielding 0s and 1s for some providers:
https://github.com/pulumi/pulumi-azure/pull/1917#pullrequestreview-1963315541
The issue was that their schema had a defaults section in the config block.
This PR fixes the jq syntax to correctly ignore that bit.
> Fix array indices in config check

- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/build_sdk.splice
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/prerequisites.splice
- provider-ci/internal/pkg/templates/bridged-provider/Makefile
- provider-ci/test-workflows/aws/.github/workflows/master.yml
- provider-ci/test-workflows/aws/.github/workflows/nightly-test.yml
- provider-ci/test-workflows/aws/.github/workflows/prerelease.yml
- provider-ci/test-workflows/aws/.github/workflows/release.yml
- provider-ci/test-workflows/aws/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-workflows/aws/Makefile
- provider-ci/test-workflows/cloudflare/.github/workflows/master.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/prerelease.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/release.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-workflows/cloudflare/Makefile
- provider-ci/test-workflows/docker/.github/workflows/master.yml
- provider-ci/test-workflows/docker/.github/workflows/prerelease.yml
- provider-ci/test-workflows/docker/.github/workflows/release.yml
- provider-ci/test-workflows/docker/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-workflows/docker/Makefile
This should unlock some speedups especially in large providers like pulumi-aws by reusing available results for the examples generation pass and reducing the wait time on pulumi-converter-terraform.
Generalized form of https://github.com/pulumi/pulumi-aws/pull/3550
> Introduce examples cache 

- native-provider-ci/providers/command/config.yaml
- native-provider-ci/providers/command/repo/.github/workflows/build.yml
- native-provider-ci/providers/command/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/command/repo/.github/workflows/release.yml
- native-provider-ci/providers/command/repo/.github/workflows/run-acceptance-tests.yml
- native-provider-ci/src/steps.ts
- native-provider-ci/src/workflows.ts
I merged https://github.com/pulumi/pulumi-command/pull/391, but wasn't aware that ci-mgmt needed to accommodate the new shape of the provider.
This change accommodates https://github.com/pulumi/pulumi-command/pull/391. In light of https://github.com/pulumi/pulumi-command/pull/395, it turns linting back on.
> Allow no gen binary for pulumi-command

- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/prerequisites.splice
- provider-ci/test-workflows/aws/.github/workflows/master.yml
- provider-ci/test-workflows/aws/.github/workflows/nightly-test.yml
- provider-ci/test-workflows/aws/.github/workflows/prerelease.yml
- provider-ci/test-workflows/aws/.github/workflows/release.yml
- provider-ci/test-workflows/aws/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/master.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/prerelease.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/release.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-workflows/docker/.github/workflows/master.yml
- provider-ci/test-workflows/docker/.github/workflows/prerelease.yml
- provider-ci/test-workflows/docker/.github/workflows/release.yml
- provider-ci/test-workflows/docker/.github/workflows/run-acceptance-tests.yml
Our schema comparison comments annoyingly have two headers:
Example in aws: https://github.com/pulumi/pulumi-aws/pull/3758#issuecomment-2027664224
Example in cloudflare: https://github.com/pulumi/pulumi-cloudflare/pull/713#issuecomment-2033452175
This is because they are defined both in CI jobs and in schema-tools [here](https://github.com/pulumi/schema-tools/blob/bc3dae99a9ab5d2ad52f4c1029f35b65248a0118/internal/cmd/compare.go#L302). This PR removes the duplication.
> Remove duplicated 'Does the PR'

- native-provider-ci/providers/aws-native/config.yaml
- native-provider-ci/providers/aws-native/repo/.goreleaser.prerelease.yml
- native-provider-ci/providers/aws-native/repo/.goreleaser.yml
- native-provider-ci/src/goreleaser.ts
- native-provider-ci/src/provider.ts
This has already been enabled for bridged providers and I want to get this working for the `aws-native` provider.
> feat: enable goreleaser automatic changelog generation for native providers

- provider-ci/internal/pkg/templates/bridged-provider/scripts/upstream.sh
- provider-ci/test-workflows/aws/scripts/upstream.sh
- provider-ci/test-workflows/cloudflare/scripts/upstream.sh
- provider-ci/test-workflows/docker/scripts/upstream.sh
Currently the patch files are generated with subjects that contain the patch number (i.e. `Subject: [PATCH 02/52] Add S3 legacy bucket to resources`). This makes diffs too verbose since everytime I add or remove a patch I have a diff on _every_ one of the patches.
The patches have the patch number in the name of the file already so the number in the subject is redundant.
> chore: create upstream patch files with `--no-numbered`

- native-provider-ci/providers/aws-native/repo/.goreleaser.prerelease.yml
- native-provider-ci/src/goreleaser.ts
This is a follow up to #883. Prereleases do not actually create a release so changelog generation will fail.
re https://github.com/pulumi/pulumi-aws-native/issues/1485
> fix(native): don't enable changelog on prerelease

- native-provider-ci/providers/docker-build/config.yaml
- native-provider-ci/providers/docker-build/repo/.goreleaser.prerelease.yml
- native-provider-ci/providers/docker-build/repo/.goreleaser.yml
The provider currently emits this warning:
> warning: resource plugin dockerbuild is expected to have version >=0.0.1-alpha.2, but has ; the wrong version may be on your path, or this may be a bug in the plugin
The version is set correctly on all builds _until_ the goreleaser step, which uses its own ldflags specified here. It assumes a non-idiomatic `pkg` directory which we don't use in pulumi-docker.
> docker-build: fix missing version

- provider-ci/internal/pkg/templates/bridged-provider/Makefile
- provider-ci/test-workflows/aws/Makefile
- provider-ci/test-workflows/cloudflare/Makefile
- provider-ci/test-workflows/docker/Makefile
Ensure that javadoc runs cleanly
Fixes https://github.com/pulumi/pulumi-gcp/issues/1950
Needs to merge **after** https://github.com/pulumi/pulumi-terraform-bridge/pull/1902.
> Ensure that java docs build

- native-provider-ci/providers/docker-build/config.yaml
- native-provider-ci/providers/docker-build/repo/.github/workflows/weekly-pulumi-update.yml
- native-provider-ci/src/provider.ts
- native-provider-ci/src/steps.ts
- native-provider-ci/src/workflows.ts
We already had a "provider-default-branch" config, but it wasn't being respected by the weekly pu/pu upgrade workflow.
Glued everything together so the workflow now respects the repo's default branch.
> [native] Suport "main" as a default branch

- provider-ci/Makefile
- provider-ci/internal/pkg/templates/bridged-provider.config.yaml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/release.yml
- Add option `publish.goSdk.usePush` which can be set to `true` to push a standalone commit for the Go SDK.
- Add options for underlying action properties to control where the SDK is pushed to.
This is disabled for the initial roll-out resulting in no change, but can be enabled on a per-provider basis as we also enable embedding the provider version number in the generated SDK.
Uses https://github.com/pulumi/publish-go-sdk-action for Go SDK publishing
> Add option to enable go-sdk push publishing

- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/lint.yml
- provider-ci/test-workflows/aws/.github/workflows/lint.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/lint.yml
- provider-ci/test-workflows/docker/.github/workflows/lint.yml
This is necessary to merge https://github.com/pulumi/pulumi-tailscale/pull/408, since
before we were seeing spurious lint errors:
```
Running [/home/runner/golangci-lint-1.55.2-linux-amd64/golangci-lint run --out-format=github-actions --path-prefix=provider] in [/home/runner/work/pulumi-tailscale/pulumi-tailscale/provider] ...
Error: cannot range over addrs.Len() (value of type int) (typecheck)
Error: cannot range over rr.Len() (value of type int) (typecheck)
Error: cannot range over rr.Len() (value of type int) (typecheck)
Error: cannot range over in.Len() (value of type int) (typecheck)
Error: issues found
```
https://github.com/pulumi/pulumi-tailscale/actions/runs/8946537237/job/24577325007?pr=408
shows that this change runs as expected.
> Update golangci-lint version

- provider-ci/internal/pkg/templates/bridged-provider.config.yaml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/build_sdk.splice
- Default to having no effect.
- This is needed as we start to onboard providers into embedding version numbers in SDKs.
> Add worktreeAllowedChanges config option

- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/lint.yml
- provider-ci/test-workflows/aws/.github/workflows/lint.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/lint.yml
- provider-ci/test-workflows/docker/.github/workflows/lint.yml
Motivated by a failure of the [lint step of the pulumi-azure build](https://github.com/pulumi/pulumi-azure/actions/runs/8980005852/job/24662960390?pr=2007).
> level=error msg=“Running error: can’t run linter goanalysis_metalinter\nbuildir: failed to load package integration: could not load export data: no export data for \“[github.com/pulumi/pulumi/pkg/v3/testing/integration](http://github.com/pulumi/pulumi/pkg/v3/testing/integration)\“”
This error message can have several causes. One of them is issues with the Go module cache. golangci/golangci-lint-action and  actions/setup-go compete in their default settings for which one is going to be installing the dependencies, potentially causing a "cache race". 
However, [v5 of golangci-lint-action](https://github.com/golangci/golangci-lint-actio …
> Upgrade golangci-lint-action to latest v6

- provider-ci/providers.json
Towards https://github.com/pulumi/home/issues/3395
Brings the pulumi-ise provider repository under ci-mgmt so we can maintain it with the rest of the bridged provider fleet.
> Add ise provider to ci-mgmt 

- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/prerequisites.splice
- provider-ci/test-workflows/aws/.github/workflows/master.yml
- provider-ci/test-workflows/aws/.github/workflows/nightly-test.yml
- provider-ci/test-workflows/aws/.github/workflows/prerelease.yml
- provider-ci/test-workflows/aws/.github/workflows/release.yml
- provider-ci/test-workflows/aws/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/master.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/prerelease.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/release.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-workflows/docker/.github/workflows/master.yml
- provider-ci/test-workflows/docker/.github/workflows/prerelease.yml
- provider-ci/test-workflows/docker/.github/workflows/release.yml
- provider-ci/test-workflows/docker/.github/workflows/run-acceptance-tests.yml
Flag the check added in https://github.com/pulumi/ci-mgmt/pull/862 to only run for providers which have enabled it.
We should fix the warnings for a provider and then enable the check to guard against regressions.
> Flag config check

- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/release.yml
- Ensure we have the SDK with the latest version number included before publishing.
> Download & restore Go SDK before pushing

- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/prerelease.yml
This makes pre-releases usable for Go users - with the correct provider version.
> Enable Go SDK push prerelease

- provider-ci/providers.json
Towards https://github.com/pulumi/home/issues/3396
Brings the pulumi-meraki provider repository under ci-mgmt so we can maintain it with the rest of the bridged provider fleet.
> Add pulumi-meraki to ci-mgmt

- provider-ci/internal/pkg/templates/bridged-provider.config.yaml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/prerelease.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/release.yml
- provider-ci/test-workflows/aws/.github/workflows/master.yml
- provider-ci/test-workflows/aws/.github/workflows/nightly-test.yml
- provider-ci/test-workflows/aws/.github/workflows/prerelease.yml
- provider-ci/test-workflows/aws/.github/workflows/release.yml
- provider-ci/test-workflows/aws/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/master.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/prerelease.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/release.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-workflows/docker/.github/workflows/master.yml
- provider-ci/test-workflows/docker/.github/workflows/prerelease.yml
- provider-ci/test-workflows/docker/.github/workflows/release.yml
- provider-ci/test-workflows/docker/.github/workflows/run-acceptance-tests.yml
- tools/sourcemigrator/index.ts
- tools/sourcemigrator/package-lock.json
- tools/sourcemigrator/package.json
- tools/sourcemigrator/respectSchemaVersion.patch
1. Change default config to use push-based Go SDK publishing
2. Use gopatch to enable RespectSchemaVersion in all languages
3. Rebuild SDKs if we've updated the resources.go file
Related to https://github.com/pulumi/ci-mgmt/issues/915 and https://github.com/pulumi/home/issues/3372
> Embed SDK version

- provider-ci/internal/pkg/templates/bridged-provider/Makefile
- provider-ci/test-workflows/aws/Makefile
- provider-ci/test-workflows/cloudflare/Makefile
- provider-ci/test-workflows/docker/Makefile
The versions are already present as they are now generated by codegen (via tfgen) now that the `respectSchemaVersion` has been set everywhere, and so special placeholders are not needed to be replaced at build time.
> Remove old method of version injection

- native-provider-ci/providers/aws-native/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/command/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/docker-build/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/google-native/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/kubernetes-cert-manager/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/prerelease.yml
- native-provider-ci/src/workflows.ts
This brings native providers in-line with bridged providers which publish tagged Go SDKs for pre-releases.
> Publish native provider prerelease Go SDKs

- native-provider-ci/providers/aws-native/repo/.github/workflows/build.yml
- native-provider-ci/providers/aws-native/repo/.github/workflows/cf2pulumi-release.yml
- native-provider-ci/providers/aws-native/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/aws-native/repo/.github/workflows/release.yml
- native-provider-ci/providers/command/repo/.github/workflows/build.yml
- native-provider-ci/providers/command/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/command/repo/.github/workflows/release.yml
- native-provider-ci/providers/docker-build/repo/.github/workflows/build.yml
- native-provider-ci/providers/docker-build/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/docker-build/repo/.github/workflows/release.yml
- native-provider-ci/providers/google-native/repo/.github/workflows/build.yml
- native-provider-ci/providers/google-native/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/google-native/repo/.github/workflows/release.yml
- native-provider-ci/providers/kubernetes-cert-manager/repo/.github/workflows/build.yml
- native-provider-ci/providers/kubernetes-cert-manager/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/kubernetes-cert-manager/repo/.github/workflows/release.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/build.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/release.yml
- native-provider-ci/src/steps.ts
- native-provider-ci/src/workflows.ts
- Fix Publish Go Sdk dependency - typo between underscore and hyphen.
- Fix Java publish by using the consistent version rather than calling `pulumictl get version`.
- Fix cf2pulumi Chocolatey version - use consistent version rather than calling `pulumictl get version`.
- Remove unused steps and workflows.
> Fix native Java & Go SDK publish

- native-provider-ci/providers/aws-native/repo/.github/workflows/weekly-pulumi-update.yml
- native-provider-ci/providers/command/repo/.github/workflows/weekly-pulumi-update.yml
- native-provider-ci/providers/docker-build/repo/.github/workflows/weekly-pulumi-update.yml
- native-provider-ci/providers/google-native/repo/.github/workflows/weekly-pulumi-update.yml
- native-provider-ci/providers/kubernetes-cert-manager/repo/.github/workflows/weekly-pulumi-update.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/weekly-pulumi-update.yml
- native-provider-ci/src/steps.ts
Fixes #940
This doesn't yet apply to bridged providers because they still have to build their own TF Gen binary for now until https://github.com/pulumi/pulumi/issues/16099 is fixed.
> Auto-update local pulumi cli version

- provider-ci/internal/cmd/generate.go
- provider-ci/internal/pkg/config.go
- provider-ci/internal/pkg/generate.go
Related to https://github.com/pulumi/ci-mgmt/issues/936 - this is a pre-cursor to building out composable templates.
We need to parse the config before calling generate.
Make the 4 required arguments to `provider-ci` optional:
```
Usage:
provider-ci generate [flags]
Flags:
-c, --config string     local config file to use (default ".ci-mgmt.yaml")
-h, --help              help for generate
-n, --name string       repository name to generate (default "{config.repository}" or otherwise "pulumi/pulumi-{config.provider}")
-o, --out string        directory to write generate files to (default ".")
-t, --template string   template name to generate (default "{config.template}" or otherwise "bridged-provider")
```
This avoids the need to generate a makefile template to make it easier to run the tool …
> Make generate cli arguments optional

- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-workflows/aws/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-workflows/docker/.github/workflows/run-acceptance-tests.yml
Write an explicit status check called "Sentinel" which will only pass if this code really runs. Once rolled out, we can make this the only required check for PRs, then remove the old conditionals on this job and remove the previous step.
This is a follow-up to the conversation https://github.com/pulumi/ci-mgmt/pull/942#issuecomment-2137523033 where we debated the merits of a single required check if we could simplify the current sentinel logic to make it more reliable.
Here's the test run in the xyz provider: https://github.com/pulumi/pulumi-xyz/actions/runs/9292939832?pr=145
Here's the old and new sentinel checks shown on the [test PR](https://github.com/pulumi/pulumi-xyz/pull/145):
> Implement new explicit sentinel check

- provider-ci/internal/pkg/templates/bridged-provider/scripts/upstream.sh
- provider-ci/test-workflows/aws/scripts/upstream.sh
- provider-ci/test-workflows/cloudflare/scripts/upstream.sh
- provider-ci/test-workflows/docker/scripts/upstream.sh
In effect `make upstream` (`apply` in `upstream.sh`) is called as the final step in `make upstream.finalize`. Because `make upstream` resets the upstream submodule to the currently staged commit, if `TO` is set to any value that is not HEAD it will be ignored (but look like it worked).
> Fix `make upstream.rebase` documentation

- infra/providers/index.ts
The `github` provider knows how to look up the default branch for a repository. This avoids creating 2 branch protection rules for every repo.
> Remove the redundant branch protection

- infra/providers/index.ts
Followup on #949: Remove redundant branch protections from native providers.
> Cleanup branch protection aliases for bridged providers

- provider-ci/internal/pkg/templates/bridged-provider/.github/ISSUE_TEMPLATE/bug.yaml
- provider-ci/test-workflows/aws/.github/ISSUE_TEMPLATE/bug.yaml
- provider-ci/test-workflows/cloudflare/.github/ISSUE_TEMPLATE/bug.yaml
- provider-ci/test-workflows/docker/.github/ISSUE_TEMPLATE/bug.yaml
This PR adds an `ISSUE_TEMPLATE/bug.yaml` to each bridged provider repo that will override the [org-wide default](https://github.com/pulumi/.github/blob/main/.github/ISSUE_TEMPLATE/bug.yaml).
Of note:
- Asks for resources affected
- Asks for console output snippet
- Asks for repro and explains why it's needed
- Asks for logs
Concerns I'd like the reviewer to consider:
- Is this the log output we'll want? Do we want GRPC-level logs instead?
- Should we acknowledge that sometimes a complete repro we can run on our end may be impossible?
- Any wording tweaks
Fixes https://github.com/pulumi/platform-providers-team/issues/157.
> Add an issue template override to all bridged providers

- provider-ci/internal/pkg/templates/bridged-provider.config.yaml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/upgrade-bridge.yml
- provider-ci/test-workflows/aws/.github/workflows/master.yml
- provider-ci/test-workflows/aws/.github/workflows/prerelease.yml
- provider-ci/test-workflows/aws/.github/workflows/release.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/master.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/prerelease.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/release.yml
- provider-ci/test-workflows/docker/.github/workflows/master.yml
- provider-ci/test-workflows/docker/.github/workflows/prerelease.yml
- provider-ci/test-workflows/docker/.github/workflows/release.yml
propagates https://github.com/pulumi/pulumi-package-publisher/pull/26 to ci-mgmt.
We should now catch dotnet publishing failures correctly.
The changes were tested in https://github.com/pulumi/pulumi-random/pull/960
> Bump package publisher

- provider-ci/internal/pkg/templates/bridged-provider.config.yaml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/main.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/prerelease.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/release.yml
- provider-ci/test-workflows/aws/.github/workflows/master.yml
- provider-ci/test-workflows/aws/.github/workflows/prerelease.yml
- provider-ci/test-workflows/aws/.github/workflows/release.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/master.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/prerelease.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/release.yml
- provider-ci/test-workflows/docker/.github/workflows/master.yml
- provider-ci/test-workflows/docker/.github/workflows/prerelease.yml
- provider-ci/test-workflows/docker/.github/workflows/release.yml
Part of #961.
We can close #961 when all Workflows have updated to this publisher.
> Bump package publisher version and update inputs

- infra/providers/index.ts
Depends on #944 and #946 being fully rolled out before this is run.
Once this is deployed, we will be free to restructure workflow jobs without needing to worry about breaking the required checks.
> Only require new sentinel check

- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-workflows/aws/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-workflows/docker/.github/workflows/run-acceptance-tests.yml
Depends on #947 being merged and deployed.
- Remove complex conditionals. These were previously required to avoid the issue of this job being skipped due to failures in previous jobs but a skip being considered as the required check completed.
- The "Sentinel" check will only be considered as success if it's explicitly run which can naturally only happen if this step actually runs.
> Simplify sentinel check

- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/release.yml
- provider-ci/test-workflows/aws/.github/workflows/release.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/release.yml
- provider-ci/test-workflows/docker/.github/workflows/release.yml
This pull request removes the dependency on `pulumictl` for the bridged provider registry docs dispatch.
Currently, the [Create Docs Build](https://github.com/pulumi/ci-mgmt/blob/master/provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/release.yml#L24) step in the Release Workflow calls into a [Pulumictl command](https://github.com/pulumi/pulumictl/blob/master/cmd/pulumictl/create/docs-build/cli.go) that triggers the [Publish Provider Update](https://github.com/pulumi/registry/blob/master/.github/workflows/publish-provider-update.yml) Workflow, building metadata, in pulumi/registry.
`publish.yml`(provider) -> `pulumictl`(bespoke command) -> `publish-provider-update`(registry)
Use `peter-evans/repository-dispatch@v3` to dispatch the `resource-provider` event that …
> Refactor: Use GHA native dispatch for registry metadata build kickoff

- provider-ci/internal/pkg/templates/bridged-provider.config.yaml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/prerequisites.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/run-acceptance-tests.yml
- provider-ci/providers/aws/config.yaml
- provider-ci/test-workflows/aws/.github/workflows/prerequisites.yml
- provider-ci/test-workflows/aws/.github/workflows/run-acceptance-tests.yml
Stacked on top of #942 
- Provide dedicated option instead of relying on providers to use custom steps which are run after tool installs.
- Run as first step so we don't delete things that have just been installed.
- Default to off to maintain existing behaviour. This can take around 3 minutes to run, so we should only run it if we're having issues.
```yaml
freeDiskSpaceBeforeBuild: false
freeDiskSpaceBeforeTest: false
```
This fixes oddities in Azure and AWS where we've added steps in the `preBuild` and `preTest` to clear disk space but then have to install tools (e.g. dotnet) a second time as they get deleted.
> Add option for freeing disk space

- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/main.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/nightly-test.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/prerelease.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/release.yml
- provider-ci/test-workflows/aws/.github/workflows/master.yml
- provider-ci/test-workflows/aws/.github/workflows/nightly-test.yml
- provider-ci/test-workflows/aws/.github/workflows/prerelease.yml
- provider-ci/test-workflows/aws/.github/workflows/release.yml
We should honour `freeDiskSpaceBeforeTest` anywhere we previously allowed `actions.preTest` to be used.
Follow-up to #964
Found while testing simplifying AWS's config using the latest changes.
> Apply `freeDiskSpaceBeforeTest` to other workflows

- provider-ci/internal/pkg/templates/bridged-provider/.github/actions/setup-tools/action.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/build_sdk.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/prerequisites.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-workflows/aws/.github/actions/setup-tools/action.yml
- provider-ci/test-workflows/aws/.github/workflows/build_sdk.yml
- provider-ci/test-workflows/aws/.github/workflows/prerequisites.yml
- provider-ci/test-workflows/aws/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-workflows/cloudflare/.github/actions/setup-tools/action.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/build_sdk.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/prerequisites.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-workflows/docker/.github/actions/setup-tools/action.yml
- provider-ci/test-workflows/docker/.github/workflows/build_sdk.yml
- provider-ci/test-workflows/docker/.github/workflows/prerequisites.yml
- provider-ci/test-workflows/docker/.github/workflows/run-acceptance-tests.yml
Stacked on top of https://github.com/pulumi/ci-mgmt/pull/942
Primary benefit is to reduce duplication within templates. This was not possible when using splices because splices cannot reference splices.
Additionally, we want to make installing our standard versions of our tools available for use from custom test jobs as used in AWS and other providers so they don't have to hard code their own install actions.
- Go was not previously explicitly installed during the build_sdk job but is used when running `make build_go`, so this adds it to ensure we're using a consistent version.
> Encapsulate tool setup into a composite action

- provider-ci/internal/pkg/templates/bridged-provider.config.yaml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/build_sdk.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-workflows/aws/.github/actions/setup-tools/action.yml
- provider-ci/test-workflows/aws/.github/workflows/build_sdk.yml
- provider-ci/test-workflows/aws/.github/workflows/master.yml
- provider-ci/test-workflows/aws/.github/workflows/nightly-test.yml
- provider-ci/test-workflows/aws/.github/workflows/prerelease.yml
- provider-ci/test-workflows/aws/.github/workflows/release.yml
- provider-ci/test-workflows/aws/.github/workflows/resync-build.yml
- provider-ci/test-workflows/aws/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-workflows/cloudflare/.github/actions/setup-tools/action.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/build_sdk.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/master.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/prerelease.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/release.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/resync-build.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-workflows/docker/.github/actions/setup-tools/action.yml
- provider-ci/test-workflows/docker/.github/workflows/build_sdk.yml
- provider-ci/test-workflows/docker/.github/workflows/master.yml
- provider-ci/test-workflows/docker/.github/workflows/prerelease.yml
- provider-ci/test-workflows/docker/.github/workflows/release.yml
- provider-ci/test-workflows/docker/.github/workflows/resync-build.yml
- provider-ci/test-workflows/docker/.github/workflows/run-acceptance-tests.yml
We were not actually installing the CLI and just using the ambient GHA version = (
setup-tools expects pulumicli as a string: https://github.com/pulumi/pulumi-github/blob/43b283d3734a435d5c714723ab8c1ddefc2be3c3/.github/actions/setup-tools/action.yml#L38
We also now install the dev version
> Install pulumi cli in jobs

- infra/providers/index.ts
This PR adds a label to each bridged provider repo: `awaiting/bridge`.
We can use this to better track provider bugs that should be fixed in the bridge.
> Add `awaiting/bridge` as a label to brided provider repos.

- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/build_sdk.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/prerequisites.yml
- provider-ci/test-workflows/aws/.github/workflows/build_sdk.yml
- provider-ci/test-workflows/aws/.github/workflows/prerequisites.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/build_sdk.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/prerequisites.yml
- provider-ci/test-workflows/docker/.github/workflows/build_sdk.yml
- provider-ci/test-workflows/docker/.github/workflows/prerequisites.yml
Explicitly generate the env for re-usable workflows.
> Any environment variables set in an env context defined at the workflow level in the caller workflow are not propagated to the called workflow.
See: https://docs.github.com/en/actions/using-workflows/reusing-workflows#limitations
This was causing GCP's rollout to fail because it uses environment variables during its unit testing.
[Example failure](https://github.com/pulumi/pulumi-gcp/actions/runs/9477202631/job/26111336756#step:14:312)
> Add env for build_sdk and prerequisites

- native-provider-ci/providers/docker-build/config.yaml
- native-provider-ci/providers/docker-build/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/docker-build/repo/.github/workflows/release.yml
- native-provider-ci/src/steps.ts
- native-provider-ci/src/workflows.ts
This persists the fix in https://github.com/pulumi/pulumi-docker-build/pull/106.
This also makes it possible to eventually not need a separate `go.mod` under the `sdk` directory at all.
> Configurable SDK module directory

- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/build_sdk.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/main.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/nightly-test.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/prerelease.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/prerequisites.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/release.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-workflows/aws/.github/workflows/build_sdk.yml
- provider-ci/test-workflows/aws/.github/workflows/master.yml
- provider-ci/test-workflows/aws/.github/workflows/nightly-test.yml
- provider-ci/test-workflows/aws/.github/workflows/prerelease.yml
- provider-ci/test-workflows/aws/.github/workflows/prerequisites.yml
- provider-ci/test-workflows/aws/.github/workflows/release.yml
- provider-ci/test-workflows/aws/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/build_sdk.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/master.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/prerelease.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/prerequisites.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/release.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-workflows/docker/.github/workflows/build_sdk.yml
- provider-ci/test-workflows/docker/.github/workflows/master.yml
- provider-ci/test-workflows/docker/.github/workflows/prerelease.yml
- provider-ci/test-workflows/docker/.github/workflows/prerequisites.yml
- provider-ci/test-workflows/docker/.github/workflows/release.yml
- provider-ci/test-workflows/docker/.github/workflows/run-acceptance-tests.yml
This ensures that the version is always consistent between different jobs within the workflow even if external dependencies change (e.g. a new release goes out half way through).
This is also required for us to be able to call a new re-usable workflow which requires the version to be available as a job output.
Tidy up the job ordering so prerequisites is the first job in the workflow (as it's the first to run).
> Only calculate version once in prerequisites

- provider-ci/internal/pkg/templates/bridged-provider.config.yaml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/prerelease.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/release.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/verify-release.yml
- provider-ci/test-workflows/aws/.github/workflows/prerelease.yml
- provider-ci/test-workflows/aws/.github/workflows/release.yml
- provider-ci/test-workflows/aws/.github/workflows/verify-release.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/prerelease.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/release.yml
- provider-ci/test-workflows/cloudflare/.github/workflows/verify-release.yml
- provider-ci/test-workflows/docker/.github/workflows/prerelease.yml
- provider-ci/test-workflows/docker/.github/workflows/release.yml
- provider-ci/test-workflows/docker/.github/workflows/verify-release.yml
Add new job in our release workflows to verify that our released SDKs and provider are usable.
This will have to be configured into each provider as we will need a program specified in the local repo for each runtime we want to verify. Ideally this will include: nodejs, python, dotnet and Go. Without configuration, the job will not do any verification. There's an example of the available configuration as documentation in the `bridged-provider.config.yaml`.
The verify-release workflow is also runnable directly if we want to do a one-off verification. See the [pulumi/verify-provider-release](https://github.com/pulumi/verify-provider-release) action for the underlying implementation.
Fixes #972 
[Example run without configuration](https://github.com/pulumi/pulumi-xyz/actions/runs/9604446619) …
> Verify release action

- provider-ci/internal/pkg/templates/bridged-provider/scripts/upstream.sh
- provider-ci/test-workflows/aws/scripts/upstream.sh
- provider-ci/test-workflows/cloudflare/scripts/upstream.sh
- provider-ci/test-workflows/docker/scripts/upstream.sh
This pull request allows us to have an empty patch file in such cases as https://github.com/pulumi/pulumi-pagerduty/pull/543, where all we need the submodule for is to make up for a lack of proper Go module versioning in an upstream provider.
This change is a minimal change to the script and setup, and we won't have to add additinal logic to ci-mgmt.yaml configs.
- **Allow empty patch for upstream apply**
- **Make test workflows**
> Allow empty patch in upstream script

- provider-ci/internal/pkg/templates/bridged-provider/scripts/upstream.sh
- provider-ci/test-workflows/aws/scripts/upstream.sh
- provider-ci/test-workflows/cloudflare/scripts/upstream.sh
- provider-ci/test-workflows/docker/scripts/upstream.sh
This reverts commit 13b894e0e3ea580291d037ee7dbd563fb57b67df.
This introduced a regression that caused `make upstream.rebase` to fail in AWS, GCP and other providers.
E.g. AWS:
```
Applying ../patches/0001-Add-TagsSchemaTrulyComputed-definition.patch
fatal: Resolve operation not in progress, we are not resuming
```
E.g. GCP:
```
Applying ../patches/0001-Allow-disabling-the-partner-name.patch
fatal: Resolve operation not in progress, we are not resuming.
```
> Revert "Allow empty patch in upstream script (#983)"

- provider-ci/internal/pkg/generate.go
Separate the concept of a template package from the template directories it's going to render.
A template is formed of one or more directories. Each template directory be rendered into the same output directory.
This forms part of https://github.com/pulumi/ci-mgmt/issues/936 where we want to be able to share some parts of the current bridged provider template with non-bridged provider repos.
> Allow composable templates

- provider-ci/providers.json
with [Update build and package names · pulumi-harness/59](https://github.com/pulumi/pulumi-harness/pull/59), the harness provider should be ready to add to the fleet.
> Add pulumi-harness to providers.json

- .github/workflows/lint-actions.yml
- .github/workflows/test-provider-ci.yml
#993 refactored the Required "Run actionlint and shellcheck" job, limiting it to top-level `.github` paths.
This caused #995 and #996 to hang indefinitely.
This pull request re-enables this check to run on every pull request.
> hotfix: run lint-actions.yml on all pull requests to master

- provider-ci/internal/pkg/templates/bridged-provider/scripts/upstream.sh
- provider-ci/test-providers/aws/scripts/upstream.sh
- provider-ci/test-providers/cloudflare/scripts/upstream.sh
- provider-ci/test-providers/docker/scripts/upstream.sh
Fixes #991.
Previously, https://github.com/pulumi/ci-mgmt/pull/983 attempted to fix this behavior; however, the `--allow-empty` was erroneously appended to the `git am` command, not the `git apply` command, as it [should have been](https://github.com/pulumi/pulumi-vault/blob/master/scripts/upstream.sh#L141).
[Git documentation for `git apply --allow-empty`](https://git-scm.com/docs/git-apply#Documentation/git-apply.txt---allow-empty) is the behavior we want.
> Allow empty patch in git apply

- native-provider-ci/providers/aws-native/repo/.github/workflows/build.yml
- native-provider-ci/providers/aws-native/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/aws-native/repo/.github/workflows/release.yml
- native-provider-ci/providers/command/repo/.github/workflows/build.yml
- native-provider-ci/providers/command/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/command/repo/.github/workflows/release.yml
- native-provider-ci/providers/docker-build/repo/.github/workflows/build.yml
- native-provider-ci/providers/docker-build/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/docker-build/repo/.github/workflows/release.yml
- native-provider-ci/providers/google-native/repo/.github/workflows/build.yml
- native-provider-ci/providers/google-native/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/google-native/repo/.github/workflows/release.yml
- native-provider-ci/providers/kubernetes-cert-manager/repo/.github/workflows/build.yml
- native-provider-ci/providers/kubernetes-cert-manager/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/kubernetes-cert-manager/repo/.github/workflows/release.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/build.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/release.yml
- native-provider-ci/src/steps.ts
- provider-ci/internal/pkg/templates/bridged-provider/Makefile
- provider-ci/test-providers/aws/Makefile
- provider-ci/test-providers/cloudflare/Makefile
- provider-ci/test-providers/docker/Makefile
Pins `twine` and `build` to known-working versions for native and bridged providers, respectively.
Removes `pip` from the native install step as that was a no-op ("requirement already satisfied").
Refs https://github.com/pypa/twine/issues/1125
> Pin python release dependencies

- native-provider-ci/providers/aws-native/repo/.github/workflows/build.yml
- native-provider-ci/providers/aws-native/repo/.github/workflows/cf2pulumi-release.yml
- native-provider-ci/providers/aws-native/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/aws-native/repo/.github/workflows/release.yml
- native-provider-ci/src/workflows.ts
GitHub is deprecating macos-11. Not sure if we need a specific version so updating to macos-latest.
https://github.blog/changelog/2024-05-20-actions-upcoming-changes-to-github-hosted-macos-runners/
> Update macos runners to macos-latest

- native-provider-ci/providers/aws-native/repo/.github/workflows/nightly-sdk-generation.yml
- native-provider-ci/providers/aws-native/repo/.github/workflows/weekly-pulumi-update.yml
- native-provider-ci/providers/command/repo/.github/workflows/weekly-pulumi-update.yml
- native-provider-ci/providers/docker-build/repo/.github/workflows/weekly-pulumi-update.yml
- native-provider-ci/providers/google-native/repo/.github/workflows/nightly-sdk-generation.yml
- native-provider-ci/providers/google-native/repo/.github/workflows/weekly-pulumi-update.yml
- native-provider-ci/providers/kubernetes-cert-manager/repo/.github/workflows/weekly-pulumi-update.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/weekly-pulumi-update.yml
- native-provider-ci/src/workflows.ts
This PR stops the checked out SDK version in Git from drifting between the dev and tentative versions.
Fixes: #1009
> Do not calculate version for native provider nightly/weekly jobs

- provider-ci/internal/pkg/templates/bridged-provider.config.yaml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/build_sdk.yml
This is not needed to be overridden now the rollout is complete.
Only use of override is also no longer needed: https://github.com/search?q=org%3Apulumi+path%3A.ci-mgmt.yaml+%22worktreeAllowedChanges%3A%22&type=code
PR to remove dangling use: https://github.com/pulumi/pulumi-kafka/pull/459
> Inline worktreeAllowedChanges

- provider-ci/Makefile
We were operating in the directory above the actual repo and actionlint just exited with no error.
I've now tested this by breaking a template to ensure this flags the failure.
> Fix test-provider actionlinting

- provider-ci/internal/pkg/templates/bridged-provider.config.yaml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/prerelease.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/release.yml
These are never actually overridden so can be inlined to reduce complexity of possible conditons.
Single reference to goSdk was in pulumi-kafka which had no effect. PR to remove: https://github.com/pulumi/pulumi-kafka/pull/459
Stacked on top of:
- https://github.com/pulumi/ci-mgmt/pull/1003
> Remove unused publish.goSdk config

- provider-ci/internal/pkg/templates/bridged-provider.config.yaml
Add more context to the env settings so we can simplify them at some point
> Document env

- provider-ci/internal/pkg/templates/bridged-provider.config.yaml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/main.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/prerelease.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/release.yml
- provider-ci/test-providers/aws/.github/workflows/master.yml
- provider-ci/test-providers/aws/.github/workflows/prerelease.yml
- provider-ci/test-providers/aws/.github/workflows/release.yml
- provider-ci/test-providers/cloudflare/.github/workflows/master.yml
- provider-ci/test-providers/cloudflare/.github/workflows/prerelease.yml
- provider-ci/test-providers/cloudflare/.github/workflows/release.yml
- provider-ci/test-providers/docker/.github/workflows/master.yml
- provider-ci/test-providers/docker/.github/workflows/prerelease.yml
- provider-ci/test-providers/docker/.github/workflows/release.yml
Re-use our own tool setups which can include additional options for caching rather than duplicating the setup logic into the publishing action.
This depends on first merging:
- https://github.com/pulumi/pulumi-package-publisher/pull/32
- https://github.com/pulumi/ci-mgmt/pull/1003
This PR assumes that `pulumi/pulumi-package-publisher` will then be published as `v0.0.19` (the next version).
> Install tools package publishing

- provider-ci/internal/pkg/templates/bridged-provider.config.yaml
This field was missing in the config.yaml docs.
Real-world example: https://github.com/pulumi/pulumi-alicloud/blob/34d9dd0891282f9e0c4eb4d284ac1e560e2ea678/.ci-mgmt.yaml#L24
> Add documentation for license check ignore option

- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/build_provider.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/run-acceptance-tests.yml
- provider-ci/internal/pkg/templates/bridged-provider/Makefile
- provider-ci/test-providers/aws/.github/workflows/build_provider.yml
- provider-ci/test-providers/aws/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-providers/aws/Makefile
- provider-ci/test-providers/cloudflare/.github/workflows/build_provider.yml
- provider-ci/test-providers/cloudflare/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-providers/cloudflare/Makefile
- provider-ci/test-providers/docker/.github/workflows/build_provider.yml
- provider-ci/test-providers/docker/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-providers/docker/Makefile
Around 20 providers don't generate a `schema-embed.json` (e.g. because the schema is not massive). This causes 2 issues:
1. A named artifact download fails if not found.
2. The makefile target will fail if a dependency does not exist.
Example: https://github.com/pulumi/pulumi-azuredevops/pull/438
Note: this failed the PR builds for providers without the schema-embed.json file, but still got auto-merged by GitHub.
To make the `schema-embed.json` file optional we can:
1. Make the artifact download use a pattern which can validly match zero paths.
2. Remove the makefile target dependency.
This change has been manually tested via a PR to p-azuredevops: https://github.com/pulumi/pulumi-azuredevops/pull/440
> Fix new provider build when missing schema-embed

- provider-ci/internal/pkg/templates/provider/.github/ISSUE_TEMPLATE/bug.yaml
- provider-ci/test-providers/aws/.github/ISSUE_TEMPLATE/bug.yaml
- provider-ci/test-providers/cloudflare/.github/ISSUE_TEMPLATE/bug.yaml
- provider-ci/test-providers/docker/.github/ISSUE_TEMPLATE/bug.yaml
We don't need log outputs if a clear repro is given for an issue, so it's unnecessary to require that. It raises the barrier to reporting an issue, possibly costing us bug reports.
I haven't seen a pulumi engineer add logs when reporting an issue, except when that's meaningful, so we shouldn't expect outside contributors to do that.
> Make log outputs optional in the issue template

- provider-ci/internal/pkg/templates/provider/.github/workflows/license.yml
- provider-ci/test-providers/aws/.github/workflows/license.yml
- provider-ci/test-providers/cloudflare/.github/workflows/license.yml
- provider-ci/test-providers/docker/.github/workflows/license.yml
- This is a left-over from the old acceptance test setup - this ENV variable is no longer set in this context.
- Just use the default checkout behaviour.
- Reformat YAML (add indent on list items & remove duplicate line breaks). See [diff ignoring whitespace](https://github.com/pulumi/ci-mgmt/pull/1036/files?w=1)
> Remove missing PR_COMMIT_SHA from license check

- provider-ci/internal/pkg/templates/bridged-provider/Makefile
- provider-ci/internal/pkg/templates/bridged-provider/upstream.sh
- provider-ci/test-providers/aws/Makefile
- provider-ci/test-providers/aws/upstream.sh
- provider-ci/test-providers/cloudflare/Makefile
- provider-ci/test-providers/cloudflare/upstream.sh
- provider-ci/test-providers/docker/Makefile
- provider-ci/test-providers/docker/upstream.sh
When `upstream` locally gets out of sync with the current default branch tip, any run of `make upstream` will exit 1 on `assert_upstream`tracked` in the `upstream.sh` script, because it will have been detected as modified. 
This happens whenever anyone pulls in upstream changes to work on a feature or bug fix. The instructions [provided](https://github.com/pulumi/ci-mgmt/blob/master/provider-ci/internal/pkg/templates/bridged-provider/upstream.sh#L96) do not work.
This pull request defaults to pass `-f` to the `init` command run via `make upstream`.
Since the [upgrade provider tool](https://github.com/pulumi/upgrade-provider/blob/main/upgrade/steps.go#L163) always force resets the submodule as well, this should be a safe change.
It is dubious why we'd need the non-force option at all, and …
> Force initialize the submodule on `make upstream`

- provider-ci/internal/pkg/templates/bridged-provider/Makefile
- provider-ci/test-providers/aws/Makefile
- provider-ci/test-providers/cloudflare/Makefile
- provider-ci/test-providers/docker/Makefile
Currently, we re-download the Pulumi CLI whenever `provider/go.mod` changes. This is wasteful in general, but especially punishing to contributors who don't have a strong connection.
This PR adds a local check of the installed version before we download a new version of the CLI.
> Only download the Pulumi CLI when the version doesn't match

- provider-ci/internal/pkg/templates/bridged-provider.config.yaml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/main.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/nightly-test.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/prerelease.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/release.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-providers/aws/.github/workflows/master.yml
- provider-ci/test-providers/aws/.github/workflows/prerelease.yml
- provider-ci/test-providers/aws/.github/workflows/release.yml
- provider-ci/test-providers/aws/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-providers/cloudflare/.github/workflows/master.yml
- provider-ci/test-providers/cloudflare/.github/workflows/prerelease.yml
- provider-ci/test-providers/cloudflare/.github/workflows/release.yml
- provider-ci/test-providers/cloudflare/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-providers/docker/.github/workflows/master.yml
- provider-ci/test-providers/docker/.github/workflows/prerelease.yml
- provider-ci/test-providers/docker/.github/workflows/release.yml
- provider-ci/test-providers/docker/.github/workflows/run-acceptance-tests.yml
This will allow us to remove all of our `preTest` hooks in provider ci-mgmt configs - which we'd like to get rid of to avoid arbitary code injection into workflows which make them fragile and hard to refactor. See also https://github.com/pulumi/ci-mgmt/pull/1037
Related to https://github.com/pulumi/ci-mgmt/issues/936
Set `integrationTestProvider: true` to run `go test [...] -tags=${{ matrix.language }}` in the `provider` directory.
Example of existing preTest usage: https://github.com/pulumi/pulumi-gcp/blob/92b64b51bfb05fc0d2d7b9c1cbcafe7de8a6f7f3/.ci-mgmt.yaml#L43
This step is safe to run, as we already do before the Go build steps elsewhere. The upstream target is always there but might be a no-op.
Set `sshPrivateKey: ${{ secrets.PRIVATE_SSH_KEY_FOR_DIGITALOCEAN }}` to set up SSH for …
> Prepare to remove actions hooks

- provider-ci/internal/pkg/templates/bridged-provider/Makefile
- provider-ci/internal/pkg/templates/bridged-provider/upstream.sh
- provider-ci/test-providers/aws/Makefile
- provider-ci/test-providers/aws/upstream.sh
- provider-ci/test-providers/cloudflare/Makefile
- provider-ci/test-providers/cloudflare/upstream.sh
- provider-ci/test-providers/docker/Makefile
- provider-ci/test-providers/docker/upstream.sh
- Recommend adding `-f` rather than custom git checkout commands.
- Hide the `format_patches` command as `check_in` is a much less confusing version of the command.
- Don't use the force option from the makefile as we don't want to wipe out any uncommitted work by accident.
- Relax validation for running 'init' and 'checkout' without the force option. Only require upstream to not be checked out on the 'pulumi/patch-checkout' branch, but don't require it to be tracked in git. This allows the unforced init to be used after pulling changes but not having yet updated the submodule.
- Assert we're not mid-rebase if force not provided (avoids accidentally loosing progress if switched to our own branch).
- Clean up old branches and rebases when using the force option with either init or …
> Provide better instructions when upstream is modified

- native-provider-ci/providers/aws-native/repo/.github/workflows/run-acceptance-tests.yml
- native-provider-ci/providers/command/repo/.github/workflows/run-acceptance-tests.yml
- native-provider-ci/providers/docker-build/repo/.github/workflows/run-acceptance-tests.yml
- native-provider-ci/providers/google-native/repo/.github/workflows/run-acceptance-tests.yml
- native-provider-ci/providers/kubernetes-cert-manager/repo/.github/workflows/run-acceptance-tests.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/run-acceptance-tests.yml
- native-provider-ci/src/workflows.ts
This brings us to parity with bridged providers:
https://github.com/pulumi/ci-mgmt/blob/2d9cb9ebea04c3061453e60961ff347146fbdc26/provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/run-acceptance-tests.yml#L234-L238
> Always run tests on native provider PRs

- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/publish.yml
- provider-ci/test-providers/aws/.github/workflows/publish.yml
- provider-ci/test-providers/cloudflare/.github/workflows/publish.yml
- provider-ci/test-providers/docker/.github/workflows/publish.yml
The publish job currently fails if there are no stable GH releases for the repo yet, which breaks any brand new provider. This change leaves the release notes empty for the first release which should allow the publish job to complete.
> Try to fix first releases

- provider-ci/internal/pkg/templates/bridged-provider/upstream.sh
- provider-ci/test-providers/aws/upstream.sh
- provider-ci/test-providers/cloudflare/upstream.sh
- provider-ci/test-providers/docker/upstream.sh
This was motivated by an hour I spent tracking down a persistent diff between CI and my laptop when there was an un-tracked `website` folder in `upstream` that wasn't present in CI.
> This prevents upstream from carrying un-tracked changes past `init`

- provider-ci/providers.json
Adds the new bridged provider for Juniper Mist to ci-mgmt.
> Add pulumi-junipermist to ci-mgmt

- provider-ci/internal/pkg/templates/bridged-provider.config.yaml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/build_provider.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/main.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/nightly-test.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/prerelease.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/prerequisites.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/release.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/run-acceptance-tests.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/upgrade-provider.yml
- provider-ci/test-providers/aws/.github/workflows/upgrade-provider.yml
This adds the `free-disk-space` action to the upgrade-provider workflow to prevent running out of disk space during compilation. It uses the existing `freeDiskSpaceBeforeBuild` config flag for controlling this.
Additionally this centralizes the config for the version of the `free-disk-space` action to use.
> Add free-disk-space action to upgrade provider workflow

- native-provider-ci/providers/aws-native/repo/.github/workflows/weekly-pulumi-update.yml
- native-provider-ci/providers/command/repo/.github/workflows/weekly-pulumi-update.yml
- native-provider-ci/providers/docker-build/repo/.github/workflows/weekly-pulumi-update.yml
- native-provider-ci/providers/google-native/repo/.github/workflows/weekly-pulumi-update.yml
- native-provider-ci/providers/kubernetes-cert-manager/repo/.github/workflows/weekly-pulumi-update.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/weekly-pulumi-update.yml
- native-provider-ci/src/steps.ts
Here is an example of a PR created by the `weekly-pulumi-update` automation that includes the changes suggseted here:
https://github.com/pulumi/pulumi-aws-native/pull/1670
For comparison, here is the PR created by the automation before the changes:
https://github.com/pulumi/pulumi-aws-native/pull/1668
Note that Pulumi version is made prominent in the PR title.
And it uses the word "bump" inspired by Dependabot PRs.
It also removes repo-sync/pull-request@v2.6.2 dependency as this project is now archived.
> Teach weekly-pulumi-update to create PRs with Pulumi version in the title

- provider-ci/internal/pkg/templates/bridged-provider.config.yaml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/build_sdk.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/upgrade-bridge.yml
- provider-ci/test-providers/aws/.ci-mgmt.yaml
- provider-ci/test-providers/aws/.github/workflows/build_sdk.yml
- provider-ci/test-providers/aws/.github/workflows/upgrade-bridge.yml
Some of the workflows on larger providers like aws started failing because they're running out of disk space (again.. sigh). Examples are:
- https://github.com/pulumi/pulumi-aws/issues/4379
- https://github.com/pulumi/pulumi-aws/actions/runs/10421649189/job/28864324845
This change adds a new configuration parameter (`freeDiskSpaceBeforeSdkBuild`) to free the disk space before SDK builds. Additionally it also adds the disk space cleaning to the upgrade-bridge workflow.
We should also explore using bigger runners, but this might be cost prohibitive (AWS alone had ~1.1k build hours within the last month, which would amount to ~1k$ for a larger runner).
> Add option for freeing disk space to sdk build and bridge upgrade

- provider-ci/internal/pkg/templates/provider/.github/workflows/lint.yml
- provider-ci/test-providers/aws/.github/workflows/lint.yml
- provider-ci/test-providers/cloudflare/.github/workflows/lint.yml
- provider-ci/test-providers/docker/.github/workflows/lint.yml
This is necessary to accommodate providers who require go1.23, since previous versions of golangci-lint do not support go1.23.
> Upgrade golangci-lint to v1.60

- .github/workflows/update-workflows.yml
Custom workflows like aws-run-upstream-tests.yml should not be managed centrally.
> Permit bridged providers to have custom workflows

- provider-ci/internal/pkg/templates/provider/.github/ISSUE_TEMPLATE/epic.md
- provider-ci/test-providers/aws/.github/ISSUE_TEMPLATE/epic.md
- provider-ci/test-providers/cloudflare/.github/ISSUE_TEMPLATE/epic.md
- provider-ci/test-providers/docker/.github/ISSUE_TEMPLATE/epic.md
As a first step toward propagating the issue template to more of our repos, add it to our templates for bridged providers
> Add Epic template to bridged providers

- provider-ci/internal/pkg/templates/provider/.golangci.yml
- provider-ci/test-providers/aws/.golangci.yml
- provider-ci/test-providers/cloudflare/.golangci.yml
- provider-ci/test-providers/docker/.golangci.yml
- Upgrade golangci-lint to v1.60 (#1062) surfaced new warnings about deprecations.
- The configuration option `run.skip-files` is deprecated, please use `issues.exclude-files`.
- The linter named "megacheck" is deprecated. It has been split into: gosimple, staticcheck, unused.
> Fix golangci-lint warnings

- provider-ci/internal/pkg/templates/bridged-provider/Makefile
- provider-ci/test-providers/aws/Makefile
- provider-ci/test-providers/cloudflare/Makefile
- provider-ci/test-providers/docker/Makefile
This generates lint errors that look like this:
```
provider/resources.go:144:25: printf: non-constant format string in call to fmt.Errorf (govet)
return "", fmt.Errorf("Expected base64 property to be a string" + c)
^
```
Instead of like this:
```
resources.go:144:25: printf: non-constant format string in call to fmt.Errorf (govet)
return "", fmt.Errorf("Expected base64 property to be a string" + c)
^
```
Having the prefixed `provider` allows IDEs to understand where `resources.go` is located.
> Set `--path-prefix` in `lint_provider`

- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/check-upstream-upgrade.yml
- provider-ci/test-providers/aws/.github/workflows/check-upstream-upgrade.yml
- provider-ci/test-providers/cloudflare/.github/workflows/check-upstream-upgrade.yml
- provider-ci/test-providers/docker/.github/workflows/check-upstream-upgrade.yml
Based on https://github.com/pulumi/upgrade-provider/pull/276
This should skip git pull and submodule resolution
Should fix https://github.com/pulumi/pulumi-aws/issues/4427
> Fix upstream detection

- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/check-upstream-upgrade.yml
- provider-ci/test-providers/aws/.github/workflows/check-upstream-upgrade.yml
- provider-ci/test-providers/cloudflare/.github/workflows/check-upstream-upgrade.yml
- provider-ci/test-providers/docker/.github/workflows/check-upstream-upgrade.yml
Fixes issues in most providers with check-upstream-upgrade.
Ex. https://github.com/pulumi/pulumi-gcp/issues/2370
This reverts commit 8ebca7df53ed65258b4c2cf72e64228d65109d6c.
> Revert "Fix upstream detection (#1067)"

- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/resync-build.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/upgrade-bridge.yml
- provider-ci/internal/pkg/templates/provider/.github/workflows/verify-release.yml
- provider-ci/test-providers/aws/.github/workflows/resync-build.yml
- provider-ci/test-providers/aws/.github/workflows/upgrade-bridge.yml
- provider-ci/test-providers/aws/.github/workflows/verify-release.yml
- provider-ci/test-providers/cloudflare/.github/workflows/resync-build.yml
- provider-ci/test-providers/cloudflare/.github/workflows/upgrade-bridge.yml
- provider-ci/test-providers/cloudflare/.github/workflows/verify-release.yml
- provider-ci/test-providers/docker/.github/workflows/resync-build.yml
- provider-ci/test-providers/docker/.github/workflows/upgrade-bridge.yml
- provider-ci/test-providers/docker/.github/workflows/verify-release.yml
In `setup-tools`, the language `node` was renamed to `nodejs` for consistency. We missed it in 3 spots.
It should fix the failing `verify-release` in downstream `pulumi-xyz` provider:
* https://github.com/pulumi/pulumi-xyz/actions/runs/10789722716/job/29924862046
* https://github.com/pulumi/pulumi-xyz/actions/runs/10789596609/job/29923455243
> Use configured `languages` for tool installation

- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-providers/aws/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-providers/cloudflare/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-providers/docker/.github/workflows/run-acceptance-tests.yml
Follow-up to #1063
The nuget command fails if dotnet wasn't installed.
Example failure: https://github.com/pulumi/pulumi-azure/actions/runs/10815039270/job/30003728480?pr=2387
This only affects providers which have enabled `freeDiskSpaceBeforeTest` because they will have a default version of dotnet available, and therefore also wasn't caught by the downstream tests.
For the sake of consistency, we'll also only configure the pip virtualenv if we're atually running python tests.
> Only add nuget source for dotnet tests

- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/main.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/nightly-test.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/prerelease.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/release.yml
- provider-ci/test-providers/aws/.github/workflows/master.yml
- provider-ci/test-providers/aws/.github/workflows/nightly-test.yml
- provider-ci/test-providers/aws/.github/workflows/prerelease.yml
- provider-ci/test-providers/aws/.github/workflows/release.yml
- provider-ci/test-providers/cloudflare/.github/workflows/master.yml
- provider-ci/test-providers/cloudflare/.github/workflows/prerelease.yml
- provider-ci/test-providers/cloudflare/.github/workflows/release.yml
- provider-ci/test-providers/docker/.github/workflows/master.yml
- provider-ci/test-providers/docker/.github/workflows/prerelease.yml
- provider-ci/test-providers/docker/.github/workflows/release.yml
Mirror the fix for #1079 into the nightly, main, prerelease and release jobs.
Test is the only core part of our workflow which has not been deduplicated and so we have to copy fixes into all the different workflows.
Spotted from issue https://github.com/pulumi/pulumi-azure/issues/2393
> Fix test tool setup

- provider-ci/internal/pkg/templates/bridged-provider/Makefile
- provider-ci/test-providers/acme/Makefile
- provider-ci/test-providers/aws/Makefile
- provider-ci/test-providers/cloudflare/Makefile
- provider-ci/test-providers/docker/Makefile
We introduced a notion of provider-custom workflow files, such as:
aws-upstream-tests.yml
Currently CI knows to not delete them, but `make ci-mgmt` target still does. This PR fixes this so that `make ci-mgmt`
target matches the behavior of CI workflows.
> Do not delete provider custom workflows in make ci-mgmt

- tools/sourcemigrator/index.ts
- tools/sourcemigrator/removeExplicitSDKdependency.patch
This adds a migration for providers to remove the explicit SDK dependencies for python and javascript.
this should solve https://github.com/pulumi/ci-mgmt/issues/1091 for tier 2+ providers
I've tested this on pulumi-cloudflare and pulumi-random. I've also tested it doesn't do anything the second time around.
> Migration to remove explicit SDK dependencies for python and JS

- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/build_sdk.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/main.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/publish.yml
- provider-ci/test-providers/acme/.github/workflows/build_sdk.yml
- provider-ci/test-providers/acme/.github/workflows/main.yml
- provider-ci/test-providers/acme/.github/workflows/publish.yml
- provider-ci/test-providers/aws/.github/workflows/build_sdk.yml
- provider-ci/test-providers/aws/.github/workflows/master.yml
- provider-ci/test-providers/aws/.github/workflows/publish.yml
- provider-ci/test-providers/cloudflare/.github/workflows/build_sdk.yml
- provider-ci/test-providers/cloudflare/.github/workflows/master.yml
- provider-ci/test-providers/cloudflare/.github/workflows/publish.yml
- provider-ci/test-providers/docker/.github/workflows/build_sdk.yml
- provider-ci/test-providers/docker/.github/workflows/master.yml
- provider-ci/test-providers/docker/.github/workflows/publish.yml
Summary of changes:
* Thirdparty providers do not have the Pulumi Bot active. Any workflow step making use of it should be skipped if no such endpoint has been defined.
* Providers need the `--repository` option set for `schema-tools` to fetch the schema in the correct Github organization
> Disable triggering a release based on issue/pr labels

- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/build_provider.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/build_sdk.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/main.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/nightly-test.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/prerelease.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/prerequisites.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/release.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/upgrade-bridge.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/upgrade-provider.yml
- provider-ci/internal/pkg/templates/pulumi-provider/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-providers/acme/.github/workflows/upgrade-provider.yml
- provider-ci/test-providers/aws/.github/workflows/build_provider.yml
- provider-ci/test-providers/aws/.github/workflows/build_sdk.yml
- provider-ci/test-providers/aws/.github/workflows/master.yml
- provider-ci/test-providers/aws/.github/workflows/nightly-test.yml
- provider-ci/test-providers/aws/.github/workflows/prerelease.yml
- provider-ci/test-providers/aws/.github/workflows/prerequisites.yml
- provider-ci/test-providers/aws/.github/workflows/release.yml
- provider-ci/test-providers/aws/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-providers/aws/.github/workflows/upgrade-bridge.yml
- provider-ci/test-providers/aws/.github/workflows/upgrade-provider.yml
- provider-ci/test-providers/cloudflare/.github/workflows/upgrade-provider.yml
- provider-ci/test-providers/docker/.github/workflows/upgrade-provider.yml
Call setup-tools in upgrade-provider 
- Ensure we're using our consistent set of tool versions when performing an upgrade.
- Fixes #1095 where we deleted dotnet during disk cleaning.
Never delete the dotnet runtime 
- We actually use this and it should speed up the subsequent tool setup step.
> Fix upgrade-provider tools & disk cleanup

- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/upgrade-provider.yml
- provider-ci/test-providers/acme/.github/workflows/upgrade-provider.yml
- provider-ci/test-providers/aws/.github/workflows/upgrade-provider.yml
- provider-ci/test-providers/cloudflare/.github/workflows/upgrade-provider.yml
- provider-ci/test-providers/docker/.github/workflows/upgrade-provider.yml
This action was originally failing due to missing dotnet if we run the disk clean-up action first. Then when trying to install dotnet using the setup-tools action, it was failing because the repo wasn't yet checked out, however, the `pulumi-upgrade-provider-action` does it's own checkout action, so it would have required removing the checkout from that action, creating a new version, then upgrading the version via ci-mgmt. At this point the `pulumi-upgrade-provider-action` would only contain the install and execution of the upgrade-provider CLI tool.
- Go direct to the `upgrade-provider` program instead of via the `pulumi-upgrade-provider-action` wrapper action.
- Enables us to use the shared setup-tools action for tool consistency.
- Existing wrapper action: …
> Inline upgrade provider action

- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/main.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/prerelease.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/publish.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/release.yml
- provider-ci/test-providers/acme/.github/workflows/main.yml
- provider-ci/test-providers/acme/.github/workflows/prerelease.yml
- provider-ci/test-providers/acme/.github/workflows/publish.yml
- provider-ci/test-providers/acme/.github/workflows/release.yml
- provider-ci/test-providers/aws/.github/workflows/master.yml
- provider-ci/test-providers/aws/.github/workflows/prerelease.yml
- provider-ci/test-providers/aws/.github/workflows/publish.yml
- provider-ci/test-providers/aws/.github/workflows/release.yml
- provider-ci/test-providers/cloudflare/.github/workflows/master.yml
- provider-ci/test-providers/cloudflare/.github/workflows/prerelease.yml
- provider-ci/test-providers/cloudflare/.github/workflows/publish.yml
- provider-ci/test-providers/cloudflare/.github/workflows/release.yml
- provider-ci/test-providers/docker/.github/workflows/master.yml
- provider-ci/test-providers/docker/.github/workflows/prerelease.yml
- provider-ci/test-providers/docker/.github/workflows/publish.yml
- provider-ci/test-providers/docker/.github/workflows/release.yml
Relates to: #1053, #1087
Moving from a central `PULUMI_BOT_TOKEN` to the Github Actions permissions block makes the workflows reusable for third party providers. The generated `GITHUB_TOKEN` secret in each workflow instance will receive elevated permissions based on the permissions configuration block. To limit the blast radius of a possible error, this PR focuses on the `main|master` and `(pre)release` workflows for now. Similar changes for other workflows will come in subsequent pull requests.
Besides making the workflows more reusable for third-party providers, it also improves on the situation for rate limits tied to the central `PULUMI_BOT_TOKEN`. The generated `GITHUB_TOKEN` has [much higher API rate limits](https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest- …
> Use the standard Github generated token with elevated permissions

- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/prerequisites.yml
- provider-ci/test-providers/acme/.github/workflows/prerequisites.yml
- provider-ci/test-providers/aws/.github/workflows/prerequisites.yml
- provider-ci/test-providers/cloudflare/.github/workflows/prerequisites.yml
- provider-ci/test-providers/docker/.github/workflows/prerequisites.yml
Use the configured Github organization to fetch the schema from the correct location and pass it as an argument to the `schema-tools` check.
> Use the configured Github organization for schema-tools

- .github/workflows/update-workflows.yml
- native-provider-ci/src/action-versions.ts
Moves Node.js dependency to v20
Fixes:
.github/workflows/update-workflows.yml:102:15: the runner of "actions/github-script@v6" action is too old to run on GitHub Actions. update the action's version to fix this issue [action]
> Update actions/github-script to v7

- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/upgrade-provider.yml
- provider-ci/test-providers/acme/.github/workflows/upgrade-provider.yml
- provider-ci/test-providers/aws/.github/workflows/upgrade-provider.yml
- provider-ci/test-providers/docker/.github/workflows/upgrade-provider.yml
Give us a little more control so we can test pre-release versions before rolling out to all providers.
This hasn't deployed to the xyz provider because the xyz provider currently excludes the upgrade-provider workflow. I've set up a manual test instead in the xyz provider:
- https://github.com/pulumi/pulumi-xyz/pull/510
> Allow specifying upgrade-provider version

- .github/workflows/update-workflows.yml
- provider-ci/internal/pkg/templates/bridged-provider/Makefile
- provider-ci/test-providers/acme/Makefile
- provider-ci/test-providers/aws/Makefile
- provider-ci/test-providers/cloudflare/Makefile
- provider-ci/test-providers/docker/Makefile
I noticed while testing https://github.com/pulumi/ci-mgmt/pull/1143 that [the generated PR](https://github.com/pulumi/pulumi-tf-provider-boilerplate/pull/138/files) ignored the repo's configured template and changed it.
- Use values from the config instead of hard coding them
- `--name` defaults to `{config.repository}` or `{config.organization}/pulumi-{config.provider}`
- `--template` defaults to `{config.template}` or otherwise "bridged-provider"
- `--config` defaults to `.ci-mgmt.yaml` so only specify in the update-workflows job where it's checked out into a different directory
- `--out` defaults to `.` so only specify in the update-workflows job where it's checked out into a different directory
> Remove defaultable provider-ci arguments

- provider-ci/providers.json
Push bridge CI changes to the [pulumi-tf-provider-boilerplate](https://github.com/pulumi/pulumi-tf-provider-boilerplate) repo to keep it up to date.
Bridged update test run: https://github.com/pulumi/ci-mgmt/actions/runs/11836293772
Triggered bridge update: https://github.com/pulumi/pulumi-tf-provider-boilerplate/actions/runs/11836296203
GH workflows update test run: https://github.com/pulumi/ci-mgmt/actions/runs/11836374346
CI update PR: https://github.com/pulumi/pulumi-tf-provider-boilerplate/pull/138
> Onboard tf-provider-boilerplate

- provider-ci/internal/pkg/templates/bridged-provider/Makefile
- provider-ci/test-providers/acme/Makefile
- provider-ci/test-providers/aws/Makefile
- provider-ci/test-providers/cloudflare/Makefile
- provider-ci/test-providers/docker/Makefile
Some of the providers binary, like aws, reached critical sizes. `pulumi-resource-aws` is now ~930MB big ([see](https://github.com/pulumi/pulumi-aws/issues/4383#issuecomment-2479294836)).
By stripping debug symbols we save ~300MB for AWS. Panics and stack traces still contain all the necessary information.
In detail this adds the `-s` and `-w` linker flags which strip the symbol table, debug information and DWARF symbol table.
Relates to https://github.com/pulumi/pulumi-aws/issues/4383
> Add linker flags for stripping debug symbols from provider binary

- provider-ci/internal/pkg/migrations/ignoreMakeDir.go
External providers get a generated makefile too, so need the new git-ignore rule for `.make`.
> Apply .gitignore migration to external providers too

- native-provider-ci/providers/aws-native/repo/.goreleaser.prerelease.yml
- native-provider-ci/providers/aws-native/repo/.goreleaser.yml
- native-provider-ci/providers/command/repo/.goreleaser.prerelease.yml
- native-provider-ci/providers/command/repo/.goreleaser.yml
- native-provider-ci/providers/docker-build/repo/.goreleaser.prerelease.yml
- native-provider-ci/providers/docker-build/repo/.goreleaser.yml
- native-provider-ci/providers/google-native/repo/.goreleaser.prerelease.yml
- native-provider-ci/providers/google-native/repo/.goreleaser.yml
- native-provider-ci/providers/kubernetes-cert-manager/repo/.goreleaser.prerelease.yml
- native-provider-ci/providers/kubernetes-cert-manager/repo/.goreleaser.yml
- native-provider-ci/providers/kubernetes/repo/.goreleaser.prerelease.yml
- native-provider-ci/providers/kubernetes/repo/.goreleaser.yml
- native-provider-ci/src/goreleaser.ts
By stripping debug symbols in https://github.com/pulumi/ci-mgmt/pull/1145 we significantly decreased the size of bridged provider binaries (e.g. ~300MB for pulumi-aws). This adds the same optimizations to native providers. Panics and stack traces still contain all the necessary information.
In detail this adds the `-s` and `-w` linker flags which strip the symbol table, debug information and DWARF symbol table.
> Add linker flags for stripping debug symbols from binary

- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/prerequisites.yml
- provider-ci/test-providers/cloudflare/.github/workflows/prerequisites.yml
- provider-ci/test-providers/docker/.github/workflows/prerequisites.yml
https://github.com/pulumi/pulumi-snowflake/issues/752 revealed that we weren't running registry docs build on pull requests.
This addresses that issue. Index docs will now be built on pull requests in CI.
> Run build_registry_docs as part of SDK build

- renovate.json5
https://docs.renovatebot.com/config-presets/#github
Renovate looks for `default.json` by default, but we use `default.json5` for its comment support.
Fixes https://github.com/pulumi/ci-mgmt/issues/1161
> Fix default Renovate config path

- native-provider-ci/providers/aws-native/repo/.github/workflows/run-acceptance-tests.yml
- native-provider-ci/providers/command/repo/.github/workflows/run-acceptance-tests.yml
- native-provider-ci/providers/docker-build/repo/.github/workflows/run-acceptance-tests.yml
- native-provider-ci/providers/google-native/repo/.github/workflows/run-acceptance-tests.yml
- native-provider-ci/providers/kubernetes-cert-manager/repo/.github/workflows/run-acceptance-tests.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/run-acceptance-tests.yml
- provider-ci/internal/pkg/action-versions.yml
The version of `github-status-action-v2` was missing the `v` prefix. This caused failures in sentinel jobs (e.g. https://github.com/pulumi/pulumi-aws-native/actions/runs/12048854301/job/33595172277?pr=1865).
Fixes https://github.com/pulumi/ci-mgmt/issues/1182
> Correct github-status-action-v2 version

- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/build_provider.yml
- provider-ci/test-providers/acme/.github/workflows/build_provider.yml
- provider-ci/test-providers/aws/.github/workflows/build_provider.yml
- provider-ci/test-providers/cloudflare/.github/workflows/build_provider.yml
- provider-ci/test-providers/docker/.github/workflows/build_provider.yml
This PR downloads our `schema-embed.json` artifact to a more appropriate path:
```diff
-provider/cmd/pulumi-resource-foo/schema-embed.json/schema-embed.json
+provider/cmd/pulumi-resource-foo/schema-embed.json
```
The current directory format happens to work due to a quirk of `go:embed`:
> If a pattern names a directory, all files in the subtree rooted at that directory are
> embedded (recursively), except that files with names beginning with ‘.’ or ‘_’
> are excluded.
Normally this is invalid for `[]byte` types, but it succeeds when there is a single file.
Refs https://github.com/pulumi/pulumi-aws/issues/4863
> Don't create a `schema-embed.json` directory

- provider-ci/internal/pkg/templates/bridged-provider/upstream.sh
- provider-ci/test-providers/acme/upstream.sh
- provider-ci/test-providers/aws/upstream.sh
- provider-ci/test-providers/cloudflare/upstream.sh
- provider-ci/test-providers/docker/upstream.sh
Allow the wildcard listing operations to return zero results instead of failing with:
```
error: can't open patch '../patches/*.patch': No such file or directory
Failed to apply *.patch.
```
> Fix checking out upstream without patches

- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/build_provider.yml
- provider-ci/test-providers/acme/.github/workflows/build_provider.yml
- provider-ci/test-providers/aws/.github/workflows/build_provider.yml
- provider-ci/test-providers/cloudflare/.github/workflows/build_provider.yml
- provider-ci/test-providers/docker/.github/workflows/build_provider.yml
All other jobs add a whole load of env vars which happens to include the GITHUB_TOKEN. We don't do this for build_provider because it doesn't need access to any cloud credentials. However, we do need the token to avoid being rate limited when downloading plugins from GitHub's API.
Example failure:
https://github.com/pulumi/pulumi-azuredevops/actions/runs/12141979431/attempts/1
```
.pulumi/bin/pulumi plugin install converter terraform 1.0.16
[converter plugin terraform-1.0.16] installing
E1203 14:43:57.729104    2119 plugins.go:497] GitHub rate limit exceeded for https://api.github.com/repos/pulumi/pulumi-converter-terraform/releases/tags/v1.0.16, try again in 3m28.270902099s. You can set GITHUB_TOKEN to make an authenticated request with a higher rate limit.
```
> Add GITHUB_TOKEN to build_provider workflow

- provider-ci/internal/pkg/config.go
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/main.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/nightly-test.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/prerelease.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/release.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/run-acceptance-tests.yml
- provider-ci/internal/pkg/templates/defaults.config.yaml
Only the Docker provider uses the `webfactory/ssh-agent` action, and that's configured via [`preTest`](https://github.com/pulumi/pulumi-docker/blob/master/.ci-mgmt.yaml#L35-L39) instead of the special-purpose `sshPrivateKey` option.
Nothing else [appears](https://github.com/search?q=org%3Apulumi%20path%3A.ci-mgmt.yml%20sshPrivateKey&type=code) to use this, so we can remove it.
> Remove unused sshPrivateKey config

- provider-ci/internal/pkg/templates/bridged-provider/upstream.sh
- provider-ci/test-providers/acme/upstream.sh
- provider-ci/test-providers/aws/upstream.sh
- provider-ci/test-providers/cloudflare/upstream.sh
- provider-ci/test-providers/docker/upstream.sh
Add instructions for running `./upstream.sh check_in` after fixing conflicts during rebase.
> Add conflict resolution instructions to upstream tool

- native-provider-ci/providers/command/repo/.github/workflows/build.yml
- native-provider-ci/providers/command/repo/.github/workflows/run-acceptance-tests.yml
- native-provider-ci/providers/docker-build/repo/.github/workflows/build.yml
- native-provider-ci/providers/docker-build/repo/.github/workflows/run-acceptance-tests.yml
- native-provider-ci/providers/kubernetes-cert-manager/repo/.github/workflows/build.yml
- native-provider-ci/providers/kubernetes-cert-manager/repo/.github/workflows/run-acceptance-tests.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/build.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/run-acceptance-tests.yml
- native-provider-ci/src/steps.ts
- native-provider-ci/src/workflows.ts
The pulumi-kubernetes provider embeds a minified version of a Pulumi JSON schema in the built binary. This file is not checked into source, only the non minified version is. `golangci-lint` is unable to compile the provider for linting if the file does not exist. This PR ensures that we disable any go:embed directives by doing a simple find/replace.
This is necessary as `golangci-lint` is unable to skip processing files/directories. Instead, the `exclude-dirs/files` directives will still parse those files/directories, but just suppress warnings/errors. If it is not compilable, in this case due to missing embed files, the linter will also fail. See https://golangci-lint.run/welcome/faq/#why-do-you-have-typecheck-errors
Seehttps://github.com/pulumi/pulumi-kubernetes/pull/3355 for example …
> Disarm any go:embed directives before running golangci-lint for native providers

- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/build_provider.yml
- provider-ci/test-providers/acme/.github/workflows/build_provider.yml
- provider-ci/test-providers/aws/.github/workflows/build_provider.yml
- provider-ci/test-providers/cloudflare/.github/workflows/build_provider.yml
- provider-ci/test-providers/docker/.github/workflows/build_provider.yml
This separates the provider build/packaging steps so we can add signatures before uploading.
Signing is done using [Jsign](https://ebourg.github.io/jsign/), which has the advantage of being able run on Ubuntu.
Confirmed the signature is OK on a Windows VM:
Refs https://github.com/pulumi/home/issues/3766
> Sign bridged windows binaries

- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/build_provider.yml
- provider-ci/internal/pkg/templates/bridged-provider/Makefile
- provider-ci/test-providers/acme/.github/workflows/build_provider.yml
- provider-ci/test-providers/acme/Makefile
- provider-ci/test-providers/aws/.github/workflows/build_provider.yml
- provider-ci/test-providers/aws/Makefile
- provider-ci/test-providers/cloudflare/.github/workflows/build_provider.yml
- provider-ci/test-providers/cloudflare/Makefile
- provider-ci/test-providers/docker/.github/workflows/build_provider.yml
- provider-ci/test-providers/docker/Makefile
The addition of signing Windows binaries unconditionally broke the setup for non-Pulumi managed providers:
https://github.com/pulumi/ci-mgmt/pull/1202#issuecomment-2530623379
This PR checks if the signing secrets have been configured and skips the signing step when not configured, as is currently the case for the providers I manage.
This is tested for the `acme` provider:
* [commit](https://github.com/pulumiverse/pulumi-acme/pull/95/commits/16ad22e76f06a89290c19b2a453ba7e019acb708)
* [corresponding run which skips "Sign Windows provider"](https://github.com/pulumiverse/pulumi-acme/actions/runs/12251907770/job/34177631020)
> Only sign the windows binary when the signing secrets are configured

- native-provider-ci/providers/kubernetes-cert-manager/repo/.github/workflows/run-acceptance-tests.yml
- native-provider-ci/src/steps.ts
Fixes https://github.com/pulumi/pulumi-kubernetes-cert-manager/issues/251
> Spin up cluster for cert-manager

- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/main.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/nightly-test.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/prerelease.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/release.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-providers/acme/.github/workflows/main.yml
- provider-ci/test-providers/acme/.github/workflows/prerelease.yml
- provider-ci/test-providers/acme/.github/workflows/release.yml
- provider-ci/test-providers/acme/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-providers/aws/.github/workflows/master.yml
- provider-ci/test-providers/aws/.github/workflows/nightly-test.yml
- provider-ci/test-providers/aws/.github/workflows/prerelease.yml
- provider-ci/test-providers/aws/.github/workflows/release.yml
- provider-ci/test-providers/aws/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-providers/cloudflare/.github/workflows/master.yml
- provider-ci/test-providers/cloudflare/.github/workflows/prerelease.yml
- provider-ci/test-providers/cloudflare/.github/workflows/release.yml
- provider-ci/test-providers/cloudflare/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-providers/docker/.github/workflows/master.yml
- provider-ci/test-providers/docker/.github/workflows/prerelease.yml
- provider-ci/test-providers/docker/.github/workflows/release.yml
- provider-ci/test-providers/docker/.github/workflows/run-acceptance-tests.yml
This might be intentional for the sake of easier debugging of failures, but we're going to start moving some tests around for the sake of sharding and it will be very important to be able to see the exact tests being run. Otherwise we run the risk of accidentally dropping something.
Let's at least turn this on temporarily.
> Always emit verbose test output

- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/publish.yml
- provider-ci/internal/pkg/templates/provider/.github/workflows/verify-release.yml
- provider-ci/test-providers/acme/.github/workflows/publish.yml
- provider-ci/test-providers/acme/.github/workflows/verify-release.yml
- provider-ci/test-providers/aws/.github/workflows/publish.yml
- provider-ci/test-providers/aws/.github/workflows/verify-release.yml
- provider-ci/test-providers/cloudflare/.github/workflows/publish.yml
- provider-ci/test-providers/cloudflare/.github/workflows/verify-release.yml
- provider-ci/test-providers/docker/.github/workflows/publish.yml
- provider-ci/test-providers/docker/.github/workflows/verify-release.yml
Fixes #1219
Extract SDK version after publishing the Python SDK. The SDK is downloaded internally by the pulumi-package-publisher action.
The xyz provider does not have a python example so we will need to manually test this against another provider.
> Verify actual published Python SDK version

- provider-ci/internal/pkg/templates/provider/.github/actions/setup-tools/action.yml
- provider-ci/internal/pkg/templates/provider/.github/workflows/license.yml
- provider-ci/test-providers/acme/.github/actions/setup-tools/action.yml
- provider-ci/test-providers/acme/.github/workflows/license.yml
- provider-ci/test-providers/aws/.github/actions/setup-tools/action.yml
- provider-ci/test-providers/aws/.github/workflows/license.yml
- provider-ci/test-providers/cloudflare/.github/actions/setup-tools/action.yml
- provider-ci/test-providers/cloudflare/.github/workflows/license.yml
- provider-ci/test-providers/docker/.github/actions/setup-tools/action.yml
- provider-ci/test-providers/docker/.github/workflows/license.yml
GitHub cache artifacts are immutable, so the first job to write to the cache "wins" in the sense that all subsequent jobs will start with whatever that job happened to cache.
We currently use `setup-go` in the license check action, but this job is very quick (typically a couple minutes) and doesn't really build any artifacts or download modules. Subsequent jobs then need to re-download and re-compile all the provider's modules.
This PR disables caching for the license check job. This gives the `prerequisites` job an opportunity to more fully populate the cache.
Ideally we would only disable _writing_ to the cache, but there isn't an official way to do that yet (https://github.com/actions/setup-go/issues/316) and manually restoring the cache is fragile.
> Don't populate the Go cache from the license check job

- provider-ci/internal/pkg/templates/provider/.github/actions/setup-tools/action.yml
- provider-ci/test-providers/acme/.github/actions/setup-tools/action.yml
- provider-ci/test-providers/aws/.github/actions/setup-tools/action.yml
- provider-ci/test-providers/cloudflare/.github/actions/setup-tools/action.yml
- provider-ci/test-providers/docker/.github/actions/setup-tools/action.yml
It is valid (and [preferable](https://go.dev/wiki/Modules#should-i-have-multiple-modules-in-a-single-repository)) to have a root-level `go.mod`. If one is present we should use it as a cache key for setup-go.
Additionally since there is some talk of moving the SDK's module down a level we might as well handle that case gracefully as well, even if we're not doing it at the moment.
(I would prefer to use `**/*.sum`, but we don't want Go examples to bust the cache.)
> Allow root-level go.mod for setup-go caching

- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/publish.yml
- provider-ci/internal/pkg/templates/defaults.config.yaml
- provider-ci/test-providers/acme/.github/workflows/publish.yml
- provider-ci/test-providers/aws/.github/workflows/publish.yml
- provider-ci/test-providers/cloudflare/.github/workflows/publish.yml
- provider-ci/test-providers/docker/.github/workflows/publish.yml
Update the version of `pulumi-package-publisher` used to v0.0.21.
It looks like `.Config.Publisher.PublisherAction` hasn't worked in the last 6 months: https://github.com/pulumi/ci-mgmt/pull/1007. Given that it hasn't worked (presumably by accident) and that we have heard no complaints, I'm going to remove the functionality in a follow-up PR.
Fixes https://github.com/pulumi/pulumi-package-publisher/issues/44.
> Update pulumi package publisher to v0.0.21

- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/publish.yml
- provider-ci/internal/pkg/templates/defaults.config.yaml
Follow-up on https://github.com/pulumi/ci-mgmt/pull/1228.
This PR removes the `.Config.Publish.PublisherAction` option. It looks like .Config.Publisher.PublisherAction hasn't worked in the last 6 months: #1007. Given that it hasn't worked (presumably by accident) and that we have heard no complaints, it seems safe to remove the option and reduce the configuration complexity in `ci-mgmt`.
> Remove `.Config.Publish.PublisherAction` in favor of renovate

- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/main.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/nightly-test.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/prerelease.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/release.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-providers/acme/.github/workflows/main.yml
- provider-ci/test-providers/acme/.github/workflows/prerelease.yml
- provider-ci/test-providers/acme/.github/workflows/release.yml
- provider-ci/test-providers/acme/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-providers/aws/.github/workflows/master.yml
- provider-ci/test-providers/aws/.github/workflows/nightly-test.yml
- provider-ci/test-providers/aws/.github/workflows/prerelease.yml
- provider-ci/test-providers/aws/.github/workflows/release.yml
- provider-ci/test-providers/aws/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-providers/cloudflare/.github/workflows/master.yml
- provider-ci/test-providers/cloudflare/.github/workflows/prerelease.yml
- provider-ci/test-providers/cloudflare/.github/workflows/release.yml
- provider-ci/test-providers/cloudflare/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-providers/docker/.github/workflows/master.yml
- provider-ci/test-providers/docker/.github/workflows/prerelease.yml
- provider-ci/test-providers/docker/.github/workflows/release.yml
- provider-ci/test-providers/docker/.github/workflows/run-acceptance-tests.yml
The `permissions` block in a reusable workflow doesn't grant these permissions. These are more used as an early indication of the permissions required by the reusable workflow. The correct permissions still need to be set on the calling side.
See `Reusable workflows` in [this blog article](https://www.kenmuse.com/blog/github-actions-workflow-permissions/).
Follow up to #1214.
Without setting the `permissions` on the calling side, the reusable workflow will not have the correct permissions.
The Pulumiverse runs failed without the required `permissions` block:
https://github.com/pulumiverse/pulumi-acme/actions/runs/12365788538
After adding the `permissions` block on the calling side:
https://github.com/pulumiverse/pulumi-acme/actions/runs/12369028130 …
> Set permissions on the calling side.

- provider-ci/internal/pkg/templates/provider/.github/workflows/license.yml
- provider-ci/internal/pkg/templates/provider/.github/workflows/lint.yml
- provider-ci/test-providers/acme/.github/workflows/license.yml
- provider-ci/test-providers/acme/.github/workflows/lint.yml
- provider-ci/test-providers/aws/.ci-mgmt.yaml
- provider-ci/test-providers/aws/.github/workflows/license.yml
- provider-ci/test-providers/aws/.github/workflows/lint.yml
- provider-ci/test-providers/aws/.github/workflows/test.yml
- provider-ci/test-providers/cloudflare/.github/workflows/license.yml
- provider-ci/test-providers/cloudflare/.github/workflows/lint.yml
- provider-ci/test-providers/docker/.github/workflows/license.yml
- provider-ci/test-providers/docker/.github/workflows/lint.yml
The `provider` template is already intended to be a generic base for other templates, so it shouldn't contain references to "upstream".
This changes the template to use the `prepare_local_workspace` target instead, which includes `upstream` for bridged providers.
Fixes https://github.com/pulumi/ci-mgmt/issues/1133
> Remove two references to `make upstream`

- native-provider-ci/providers/kubernetes-cert-manager/repo/.github/workflows/build.yml
- native-provider-ci/providers/kubernetes-cert-manager/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/kubernetes-cert-manager/repo/.github/workflows/release.yml
- native-provider-ci/providers/kubernetes-ingress-nginx/repo/.github/workflows/build.yml
- native-provider-ci/providers/kubernetes-ingress-nginx/repo/.github/workflows/prerelease.yml
- native-provider-ci/providers/kubernetes-ingress-nginx/repo/.github/workflows/release.yml
- native-provider-ci/providers/kubernetes-ingress-nginx/repo/.github/workflows/run-acceptance-tests.yml
- native-provider-ci/src/steps.ts
We need to create the KinD cluster in all workflows that run tests, not just the `run-acceptance` workflow. For the pulumi-kubernetes provider, we don't need to create a KinD cluster as we create a GKE cluster for testing instead.
Closes: https://github.com/pulumi/pulumi-kubernetes-cert-manager/issues/254
> Always spin up KinD cluster for pulumi-kubernetes-* providers in test step

- native-provider-ci/providers/aws-native/repo/.github/workflows/run-acceptance-tests.yml
- native-provider-ci/providers/command/repo/.github/workflows/run-acceptance-tests.yml
- native-provider-ci/providers/docker-build/repo/.github/workflows/run-acceptance-tests.yml
- native-provider-ci/providers/google-native/repo/.github/workflows/run-acceptance-tests.yml
- native-provider-ci/providers/kubernetes-cert-manager/repo/.github/workflows/run-acceptance-tests.yml
- native-provider-ci/providers/kubernetes-ingress-nginx/repo/.github/workflows/run-acceptance-tests.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/run-acceptance-tests.yml
- native-provider-ci/src/workflows.ts
p-k has a weird bug https://github.com/pulumi/pulumi-kubernetes/issues/3382 where we aren't able to depend on the correct "Sentinel" check.
This updates the native sentinel job to more closely match the bridged one:
https://github.com/pulumi/ci-mgmt/blob/1243b9e2dff8ae4d4391591bcec61a38daeac0af/provider-ci/test-providers/aws/.github/workflows/run-acceptance-tests.yml#L87-L109
Other native providers don't have this problem, so I don't actually think this will resolve the issue, but it should at least help rule out any permission weirdness.
Edit: OK I ran this against p-k here https://github.com/pulumi/pulumi-kubernetes/pull/3383 and suddenly the Sentinel check is available to us! So it does seem there's something wonky about the job's settings.
Before
After
> Update sentinel job for native providers

- provider-ci/internal/pkg/templates/bridged-provider/Makefile
- provider-ci/internal/pkg/templates/bridged-provider/upstream.sh
- provider-ci/test-providers/acme/Makefile
- provider-ci/test-providers/acme/upstream.sh
- provider-ci/test-providers/aws/Makefile
- provider-ci/test-providers/aws/upstream.sh
- provider-ci/test-providers/cloudflare/Makefile
- provider-ci/test-providers/cloudflare/upstream.sh
- provider-ci/test-providers/docker/Makefile
- provider-ci/test-providers/docker/upstream.sh
When running `git pull`, the upstream HEAD will not be updated if recursive submodule checkout is not enabled (as is the default).
1. Add `./upstream.sh file_target` command which just prints the upstream HEAD file path, if it exists (mimicking the existing wildcard statement).
2. Before printing, mark the file as updated if it doesn't match the new desired commit which will then trigger the upstream init to run and update the submodule.
> Fix upstream not refreshing after pull

- provider-ci/internal/pkg/templates/bridged-provider/Makefile
- provider-ci/test-providers/acme/Makefile
- provider-ci/test-providers/aws/Makefile
- provider-ci/test-providers/cloudflare/Makefile
- provider-ci/test-providers/docker/Makefile
Currently both CI and local executions surface errors such as:
```
set -e; \
if [[ "darwin-arm64" = "windows-amd64" && false != "true" ]]; then \
if [[ "|***|***|***|***|" == *"||"* ]]; then \
echo "Can't sign windows binaries as required configuration not set: AZURE_SIGNING_CLIENT_ID, AZURE_SIGNING_CLIENT_SECRET, AZURE_SIGNING_TENANT_ID, AZURE_SIGNING_KEY_VAULT_URI"; \
echo "To rebuild with signing delete the unsigned bin/darwin-arm64/pulumi-resource-aws and rebuild with the fixed configuration"; \
if [[ true == "true" ]]; then exit 1; fi; \
else \
mv bin/darwin-arm64/pulumi-resource-aws bin/darwin-arm64/pulumi-resource-aws.unsigned; \
az login --service-principal \
--username "***" \
--password "***" \
--tenant "***" \
--output none; \
ACCESS_TOKEN=$(az account get-access-token …
```
> Fix errors surfaced from Make

- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/test.yml
- provider-ci/test-providers/acme/.github/workflows/test.yml
- provider-ci/test-providers/aws/.github/workflows/test.yml
- provider-ci/test-providers/cloudflare/.github/workflows/test.yml
- provider-ci/test-providers/docker/.github/workflows/test.yml
Bridged providers no longer use `gotestfmt`, either during tests or during `actions.preTest`, so we no longer need to install `gotestfmt`.
> Don't install `gotestfmt` for bridged providers

- provider-ci/providers.json
In https://github.com/pulumi/ci-mgmt/pull/1278 we added pulumi-eks as a test provider which is good but we also added it to providers.json - it is not quite ready for this since the repo has not been fully onboarded. One observable failure is that ci-mgmt started applying branch protections to the repository and failed to override hand-rolled branch protections. It is better to avoid doing this for now.
> Fix: do not add pulumi-eks yet

- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/prerequisites.yml
- provider-ci/test-providers/eks/.github/workflows/prerequisites.yml
Not only name: but path: also must respect the gen/tfgen distinction.
> Fix path gen/tfgen typo

- provider-ci/internal/pkg/config.go
- provider-ci/internal/pkg/defaults.go
- provider-ci/internal/pkg/generate.go
- provider-ci/internal/pkg/templates/bridged-provider/Makefile
- provider-ci/internal/pkg/templates/provider/.github/actions/setup-tools/action.yml
- provider-ci/test-providers/acme/Makefile
- provider-ci/test-providers/aws/Makefile
- provider-ci/test-providers/cloudflare/Makefile
- provider-ci/test-providers/docker/Makefile
- provider-ci/test-providers/eks/Makefile
Bridged provider Makefile used to assume that `pulumictl` is available in PATH. With this change it will now automatically install it if this is not the case. This is easier to use and also will help `make renovate` targets succeed without having `pulumictl` installed.
The version of the tool is controlled so that it is in sync across the Makefile and CI.
> Automatically install pulumictl

- provider-ci/internal/pkg/templates/provider/.github/workflows/verify-release.yml
This permits providers such as pulumi-awsx to simply state this in .ci-mgmt.yaml:
aws: true
And have release verification authorized for AWS.
Without this change release verification does not work as it lacks credentials.
The template bits got copied from https://github.com/pulumi/ci-mgmt/blob/3beca112a1943089e2fea1e63f7fd9dbb2ec8007/provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/test.yml#L74
> Configure credentials for release verification

- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/main.yml
- provider-ci/test-providers/eks/.github/workflows/master.yml
The generate-coverage-data job is specific to computing examples conversion coverage for bridged providers and is not applicable to NoUpstream providers such as pulumi-awsx. It is flagged off accordingly.
> Remove genrate-coverage-data job for NoUpstream providers

- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/publish.yml
- provider-ci/internal/pkg/templates/provider/.github/workflows/verify-release.yml
- provider-ci/test-providers/acme/.github/workflows/publish.yml
- provider-ci/test-providers/acme/.github/workflows/verify-release.yml
- provider-ci/test-providers/aws/.github/workflows/publish.yml
- provider-ci/test-providers/aws/.github/workflows/verify-release.yml
- provider-ci/test-providers/cloudflare/.github/workflows/publish.yml
- provider-ci/test-providers/cloudflare/.github/workflows/verify-release.yml
- provider-ci/test-providers/docker/.github/workflows/publish.yml
- provider-ci/test-providers/docker/.github/workflows/verify-release.yml
- provider-ci/test-providers/eks/.github/workflows/publish.yml
- provider-ci/test-providers/eks/.github/workflows/verify-release.yml
This makes sure that release verification runs jobs on MacOS as intended.
Example release in https://github.com/pulumi/pulumi-xyz/pull/756 - see https://github.com/pulumi/pulumi-xyz/actions/runs/12817331557
Looks like there were a few bugs in the code:
- different variable naming
- treatment of boolean vs string
- github.event.inputs vs inputs - according to GitHub docs these treat booleans differently (!), but it has to be inputs.* I believe to be available in both workflow_call context and workflow_dispatch context
> Fix release verification to cover Mac OS appropriately

- provider-ci/internal/pkg/config.go
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/test.yml
- provider-ci/internal/pkg/templates/bridged-provider/Makefile
- provider-ci/internal/pkg/templates/defaults.config.yaml
- provider-ci/test-providers/acme/Makefile
- provider-ci/test-providers/aws/Makefile
- provider-ci/test-providers/cloudflare/Makefile
- provider-ci/test-providers/docker/Makefile
- provider-ci/test-providers/eks/.ci-mgmt.yaml
- provider-ci/test-providers/eks/.github/workflows/test.yml
- provider-ci/test-providers/eks/Makefile
This PR rebases @blampe work on sharding for bridged providers https://github.com/pulumi/ci-mgmt/pull/1217 with minor simplifications. An example PR applying this work is found here: https://github.com/pulumi/pulumi-awsx/pull/1487
There should be no visible change for providers unless they opt in with "shards: 3" or similar. For providers that do opt in, the test job will stop splitting the build matrix by language and instead create a build matrix with as many workers as shards requested, and randomly assign integration tests to these workers. This permits better loading as typically language-based strategies end up being heavy on Node tests. It also permits having more workers than languages.
This work is prerequisite to onboarding pulumi-eks to ci-mgmt via the simplified bridge …
> Allow bridged providers to opt into test sharding

- provider-ci/internal/pkg/templates/bridged-provider/Makefile
- provider-ci/test-providers/acme/Makefile
- provider-ci/test-providers/aws/Makefile
- provider-ci/test-providers/cloudflare/Makefile
- provider-ci/test-providers/docker/Makefile
- provider-ci/test-providers/eks/Makefile
Fixes: #1284
In Pulumiverse, all the providers that regenerate their workflows using ci-mgmt via a weekly pull based workflow failed last night.
It is because of a typo in the binary name to `pulumictl`.
Failing runs:
* https://github.com/pulumiverse/pulumi-grafana/actions/runs/12879415221/job/35906884734#step:3:12
* https://github.com/pulumiverse/pulumi-scaleway/actions/runs/12879402782/job/35906853723#step:3:12
* https://github.com/pulumiverse/pulumi-acme/actions/runs/12879415125/job/35906884423#step:3:12
* https://github.com/pulumiverse/pulumi-configcat/actions/runs/12879428726/job/35906918835#step:3:12
* https://github.com/pulumiverse/pulumi-unifi/actions/runs/12879450713/job/35906973576#step:3:12
* https://github.com/pulumiverse/pulumi-talos/actions/runs/12879451646/job/35906975981#st …
> Fix the binary name to `pulumictl`

- native-provider-ci/providers/aws-native/repo/.github/workflows/weekly-pulumi-update.yml
- native-provider-ci/providers/command/repo/.github/workflows/weekly-pulumi-update.yml
- native-provider-ci/providers/docker-build/repo/.github/workflows/weekly-pulumi-update.yml
- native-provider-ci/providers/google-native/repo/.github/workflows/weekly-pulumi-update.yml
- native-provider-ci/providers/kubernetes-cert-manager/repo/.github/workflows/weekly-pulumi-update.yml
- native-provider-ci/providers/kubernetes-coredns/repo/.github/workflows/weekly-pulumi-update.yml
- native-provider-ci/providers/kubernetes-ingress-nginx/repo/.github/workflows/weekly-pulumi-update.yml
- native-provider-ci/providers/kubernetes/repo/.github/workflows/weekly-pulumi-update.yml
- native-provider-ci/providers/pulumistack/repo/.github/workflows/weekly-pulumi-update.yml
- native-provider-ci/src/steps.ts
- native-provider-ci/src/workflows.ts
A recent update to the GitHub CLI introduced a bug that prevents creating PRs in workflows. This change applies a known workaround for this issue (see https://github.com/cli/cli/issues/6485#issuecomment-2560935183).
Fixes workflow P1s for native providers (like https://github.com/pulumi/pulumi-aws-native/issues/1994, https://github.com/pulumi/pulumi-kubernetes-ingress-nginx/issues/88, etc.).
> Fix GH CLI bug breaking weekly pulumi upgrade

- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/build_sdk.yml
- provider-ci/test-providers/acme/.github/workflows/build_sdk.yml
- provider-ci/test-providers/aws/.github/workflows/build_sdk.yml
- provider-ci/test-providers/cloudflare/.github/workflows/build_sdk.yml
- provider-ci/test-providers/docker/.github/workflows/build_sdk.yml
- provider-ci/test-providers/eks/.github/workflows/build_sdk.yml
A local copy of the schema is required when building SDKs using `pulumi package gen-sdk`. This PR ensures that this file is always available when building SDKs.
> Always download schema-embed.json prior to building SDKs

- provider-ci/internal/pkg/config.go
- provider-ci/internal/pkg/generate.go
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/test.yml
- provider-ci/internal/pkg/templates/bridged-provider/Makefile
- provider-ci/internal/pkg/templates/provider/.github/actions/setup-tools/action.yml
This PR contains 2 changes that will not be squashed when merged to maintain their history.
Changes:
- Enable specifying if `kubectl` needs to be installed in a workflow
- Add a configuration option to specify where integration tests are located. Defaults to `examples` if unspecified
> Allow customizing test folder directory and adding kubectl installation

- provider-ci/internal/pkg/templates/provider/.github/workflows/verify-release.yml
- provider-ci/test-providers/acme/.github/workflows/verify-release.yml
- provider-ci/test-providers/aws/.github/workflows/verify-release.yml
- provider-ci/test-providers/cloudflare/.github/workflows/verify-release.yml
- provider-ci/test-providers/docker/.github/workflows/verify-release.yml
- provider-ci/test-providers/eks/.github/workflows/verify-release.yml
On windows Action runners, the actions/checkout action needs extra configuration to be able to handle long file names.
This pull request adds this setting for the release-verification job, which uses both Linux and Windows runners.
While this was discovered while trying to enact release verification for pulumi-gcp, as it is just a configuration setting it's probably worth it to enable nonconditionally (on every provider) so we don't have to re-discover that we need to twist this knob when we enable release verification elsewhere.
Fixes https://github.com/pulumi/ci-mgmt/issues/1322
> Configure Git to checkout files with long names

- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/publish.yml
- provider-ci/test-providers/docker/.github/workflows/publish.yml
Fixes https://github.com/pulumi/pulumi-gcp/issues/2919. 
It looks like when you nest Workflows, you also need to state elevated permissions at the parent Workflow level.
- **Ensure correct id-token permission for GCP auth action**
- **Generate correct GCP auth for docker test provider**
> Configure gcloud auth id-token permissions for nested workflow

- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/main.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/prerelease.yml
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/release.yml
- provider-ci/test-providers/docker/.github/workflows/master.yml
- provider-ci/test-providers/docker/.github/workflows/prerelease.yml
- provider-ci/test-providers/docker/.github/workflows/release.yml
Followup to https://github.com/pulumi/ci-mgmt/pull/1331 which was supposed to fix https://github.com/pulumi/pulumi-gcp/issues/2919 but instead pushed the permissions problem up into the next parent Workflow.
Upshot is that the "invalid Workflow" error happens in a different file: https://github.com/pulumi/pulumi-gcp/actions/runs/13042448162/workflow#L101 
I believe this is all of the places where we need to tell Actions to inherit slightly elevated permissions.
> Set gcloud auth permissions on each publish step 

- provider-ci/internal/cmd/listTemplates.go
- provider-ci/internal/pkg/generate.go
- provider-ci/internal/pkg/templates.go
- provider-ci/internal/pkg/templates/defaults.config.yaml
1. Make it easier to find the key template composition code.
2. Add more documentation around the concepts and content.
> Extract templates function to own file with docs

- .github/ISSUE_TEMPLATE/0-ecosystem-providers.md
Remove the "not managed" label from eks, aws-apigateway and awsx
> Update 0-ecosystem-providers issue template

- infra/providers/package-lock.json
- native-provider-ci/package-lock.json
- provider-ci/go.mod
- provider-ci/go.sum
Combining multiple dependencies PRs into one via `gh combine-prs --skip-pr-check --query "author:app/dependabot"`. Dependabot PRs run read-only and therefore fail CI.
<details>
<summary>Instructions for merging</summary>
* **Use a merge commit**, so that GitHub will mark all original PRs as merged.
* If your repository does not have merge commits enabled, please temporarily enable them in settings. Tick `Allow merge commits` in the repository settings.
* When ready, merge this PR using `Create a merge commit`.
</details>
* Bump the npm_and_yarn group across 2 directories with 2 updates (#1321) @app/dependabot
* Bump golang.org/x/crypto from 0.17.0 to 0.31.0 in /provider-ci in the go_modules group (#1320) @app/dependabot
> Combined dependencies PR

- provider-ci/internal/pkg/config.go
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/upgrade-provider.yml
- provider-ci/internal/pkg/templates/defaults.config.yaml
- provider-ci/test-providers/acme/.github/workflows/upgrade-provider.yml
- provider-ci/test-providers/aws/.github/workflows/upgrade-provider.yml
- provider-ci/test-providers/docker/.github/workflows/upgrade-provider.yml
This PR adds a config `autoMergeProviderUpgrades` which will mark upstream provider upgrades to be auto-merged. I've also moved the upgrade-provider call to use the upgrade-provider action like we do with bridge upgrades.
Related to https://github.com/pulumi/ci-mgmt/issues/1344
> Allow auto-merging upstream provider upgrades

- provider-ci/internal/pkg/templates/bridged-provider/Makefile
- provider-ci/test-providers/acme/Makefile
- provider-ci/test-providers/aws/Makefile
- provider-ci/test-providers/cloudflare/Makefile
- provider-ci/test-providers/docker/Makefile
- provider-ci/test-providers/eks/Makefile
The existing pulumictl mechanism from #1284 is broken as it uses `GOPATH` rather than `GOBIN` which results in addition files being generated into a `pkg` directory within the local repo. But ultimately, it's completely unrequired, so let's delete it!
- Remove `pulumictl` completely.
- Remove no-op translation of `PROVIDER_VERSION` to `VERSION_GENERIC` - just validate versions don't start with "v".
- Remove use of `pulumictl` to download `java-gen` - just use `wget` instead.
> Fix pulumictl install

- provider-ci/internal/pkg/config.go
- provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/upgrade-provider.yml
- provider-ci/internal/pkg/templates/defaults.config.yaml
- provider-ci/test-providers/acme/.github/workflows/upgrade-provider.yml
- provider-ci/test-providers/aws/.github/workflows/upgrade-provider.yml
- provider-ci/test-providers/docker/.github/workflows/upgrade-provider.yml
This config will allow us to opt-out Tier 1 providers and opt-in Tier2+ providers.
Currently defaults to False, will flip to True once we opt-out Tier 1 providers.
Related to https://github.com/pulumi/upgrade-provider/issues/303
> Allow missing docs config

- .github/ISSUE_TEMPLATE/0-ecosystem-providers.md
- provider-ci/providers.json
This pull request removes Civo from the list of managed providers.
Part of https://github.com/pulumi/pulumi-civo/issues/696.
> Remove Civo from provider list

- .github/ISSUE_TEMPLATE/0-ecosystem-providers.md
- provider-ci/providers.json
Part of https://github.com/pulumi/home/issues/3879.
Removes Libvirt from managed CI.
> Removes libvirt from maintained provider list

- provider-ci/internal/pkg/templates/base/.github/workflows/publish.yml
- provider-ci/test-providers/acme/.github/workflows/publish.yml
- provider-ci/test-providers/aws/.github/workflows/publish.yml
- provider-ci/test-providers/cloudflare/.github/workflows/publish.yml
- provider-ci/test-providers/docker/.github/workflows/publish.yml
- provider-ci/test-providers/eks/.github/workflows/publish.yml
Upload to S3 and GH release so it's easily downloadable by systems like the registry and give the option of not requiring it to be committed.
Stacked on #1362
> Include schema-embed in release artifacts

- provider-ci/internal/pkg/templates/base/.github/workflows/prerequisites.yml
- provider-ci/test-providers/acme/.github/workflows/prerequisites.yml
- provider-ci/test-providers/aws/.github/workflows/prerequisites.yml
- provider-ci/test-providers/cloudflare/.github/workflows/prerequisites.yml
- provider-ci/test-providers/docker/.github/workflows/prerequisites.yml
- provider-ci/test-providers/eks/.github/workflows/prerequisites.yml
This ensures the major version always matches the major version generated into the makefile too - based on the .ci-mgmt.yaml config.
This is much more predictable behaviour than inferring from the branch name or PR labels. This utilises the new feature https://github.com/pulumi/provider-version-action/pull/15, released in v1.6.0 of pulumi/provider-version-action
Stacked on #1363
> Pin the major version explicitly in CI

- provider-ci/internal/pkg/templates/defaults.config.yaml
- provider-ci/test-providers/acme/.github/workflows/upgrade-provider.yml
- provider-ci/test-providers/aws/.ci-mgmt.yaml
- provider-ci/test-providers/aws/.github/workflows/upgrade-provider.yml
- provider-ci/test-providers/docker/.github/workflows/upgrade-provider.yml
This PR changes all Tier2+ providers to auto-merge upstream provider upgrades. This will save us a lot of clicking.
Fixes https://github.com/pulumi/ci-mgmt/issues/1344
Tier 1 providers are exempt as the config is explicitly false there:
https://github.com/pulumi/pulumi-gcp/pull/2970
https://github.com/pulumi/pulumi-aws/pull/5192
https://github.com/pulumi/pulumi-azure/pull/3002
https://github.com/pulumi/pulumi-azuread/pull/1876
> Auto-merge provider upgrades

- provider-ci/internal/pkg/templates/defaults.config.yaml
- provider-ci/test-providers/acme/.github/workflows/upgrade-provider.yml
- provider-ci/test-providers/aws/.ci-mgmt.yaml
- provider-ci/test-providers/aws/.github/workflows/upgrade-provider.yml
- provider-ci/test-providers/docker/.github/workflows/upgrade-provider.yml
This PR changes all Tier2+ providers to allow missing resource docs when running a provider upgrade. This is a common issue which happens and we have to manually work around.
Fixes https://github.com/pulumi/upgrade-provider/issues/303
Tier 1 providers are exempt as the config is explicitly false there:
https://github.com/pulumi/pulumi-gcp/pull/2971
https://github.com/pulumi/pulumi-aws/pull/5193
https://github.com/pulumi/pulumi-azure/pull/3003
https://github.com/pulumi/pulumi-azuread/pull/1877
> Allow missing resource docs for Tier2+ providers

- provider-ci/internal/pkg/action-versions.yml
- provider-ci/test-providers/acme/.github/workflows/upgrade-bridge.yml
- provider-ci/test-providers/acme/.github/workflows/upgrade-provider.yml
- provider-ci/test-providers/aws/.github/workflows/upgrade-bridge.yml
- provider-ci/test-providers/aws/.github/workflows/upgrade-provider.yml
- provider-ci/test-providers/cloudflare/.github/workflows/upgrade-bridge.yml
- provider-ci/test-providers/docker/.github/workflows/upgrade-bridge.yml
- provider-ci/test-providers/docker/.github/workflows/upgrade-provider.yml
Thomas spotted some warnings related to some recent changes to upgrade-provider-action: https://github.com/pulumi/pulumi-azuredevops/actions/runs/13382459741/job/37373285196
Looks like we never bumped the version of the action so the `allow-missing-docs` arg was not recognized.
Related to https://github.com/pulumi/ci-mgmt/pull/1379
Related to https://github.com/pulumi/upgrade-provider/issues/303
> Bump upgrade-provider-action

- .github/workflows/update-workflows.yml
This PR updates the update-workflows workflow to ensure we use a Golang version compatible with the respective provider for updating its own workflows. It achieves this by first checking out the targeted provider repository and extracting the Golang version specified in its `.ci-mgmt.yaml` config file. If no version is specified, the workflow defaults to the latest "stable" Go release.  
This change is necessary because our providers use different Go versions, and mismatches can lead to build failures due to incompatible toolchain versions.  
Manual testing was conducted by dispatching the workflow against repositories with and without a defined Go version in their config:  
- **AWS (with Go version specified):** [[Logs](https://github.com/pulumi/ci-mgmt/actions/runs/13444914246/job/375679 …
> ci: use go version from provider to update workflows

- provider-ci/internal/pkg/templates/base/.github/workflows/build_provider.yml
- provider-ci/test-providers/acme/.github/workflows/build_provider.yml
- provider-ci/test-providers/aws/.github/workflows/build_provider.yml
- provider-ci/test-providers/cloudflare/.github/workflows/build_provider.yml
- provider-ci/test-providers/docker/.github/workflows/build_provider.yml
- provider-ci/test-providers/eks/.github/workflows/build_provider.yml
- provider-ci/test-providers/terraform-module/.github/workflows/build_provider.yml
In large providers like AWS we have cache stability issues - we run out of 10GB cache space, and we also have jobs failing when they hit out-of-disk issues on the runners, such as build_provider. One problem is that Go caches are very monolithic with one big file combining all architectures and platforms (in build_provider) job.
This PR looks at breaking down the caches per platform and architecture. Smaller caches should use less disk space on the runner. They also should evict more easily.
Relates https://github.com/pulumi/ci-mgmt/issues/1031
> Split up Go provider build caches by platform-arch

- provider-ci/internal/pkg/templates/base/.github/workflows/publish.yml
- provider-ci/test-providers/acme/.github/workflows/publish.yml
- provider-ci/test-providers/aws/.github/workflows/publish.yml
- provider-ci/test-providers/cloudflare/.github/workflows/publish.yml
- provider-ci/test-providers/docker/.github/workflows/publish.yml
- provider-ci/test-providers/eks/.github/workflows/publish.yml
- provider-ci/test-providers/terraform-module/.github/workflows/publish.yml
publish.yml does not build Go yet it can run out of disk space if the Go cache is too large.
re: https://github.com/pulumi/pulumi-aws/issues/5242
> Do not cache go in publish

- provider-ci/internal/pkg/templates/bridged/.github/workflows/upgrade-bridge.yml
- provider-ci/test-providers/acme/.github/workflows/upgrade-bridge.yml
- provider-ci/test-providers/aws/.github/workflows/upgrade-bridge.yml
- provider-ci/test-providers/cloudflare/.github/workflows/upgrade-bridge.yml
- provider-ci/test-providers/docker/.github/workflows/upgrade-bridge.yml
This came up during investigating bridge downstream checks and in particular:
https://github.com/pulumi/pulumi-mongodbatlas/pull/714
There is an environment variable that affects whether preview resources are included in the schema or not:
https://github.com/pulumi/pulumi-mongodbatlas/blob/1a78223a600a451687b4a0b6ae76a6e21db06a71/.ci-mgmt.yaml#L7
This environment variable is set in all workflows but not in upgrade-bridge.yml. Because it is not set there, the wrong schema/sdk is generated during bridge upgrade. 
This PR suggests to set env vars uniformly. 
Alternatively we may consider wiring this env var into the Go code in mongodbatlas.
> Carry env vars into upgrade-bridge.yml

- provider-ci/internal/pkg/templates/base/.github/workflows/publish.yml
- provider-ci/internal/pkg/templates/base/.github/workflows/verify-release.yml
- provider-ci/test-providers/acme/.github/workflows/publish.yml
- provider-ci/test-providers/acme/.github/workflows/verify-release.yml
- provider-ci/test-providers/aws/.github/workflows/publish.yml
- provider-ci/test-providers/aws/.github/workflows/verify-release.yml
- provider-ci/test-providers/cloudflare/.github/workflows/publish.yml
- provider-ci/test-providers/cloudflare/.github/workflows/verify-release.yml
- provider-ci/test-providers/docker/.github/workflows/publish.yml
- provider-ci/test-providers/docker/.github/workflows/verify-release.yml
- provider-ci/test-providers/eks/.github/workflows/publish.yml
- provider-ci/test-providers/eks/.github/workflows/verify-release.yml
- provider-ci/test-providers/terraform-module/.github/workflows/publish.yml
- provider-ci/test-providers/terraform-module/.github/workflows/verify-release.yml
This PR enables MacOS verification by default for pre-releases as well. Previously, these verifications were skipped due to concerns about MacOS runner exhaustion and the strain on available machine types. Since resource quotas are no longer a concern, this verification can now be enabled by default.
Closes: #1313
> Run MacOS pre-release verification by default

- provider-ci/internal/pkg/templates/base/.github/workflows/lint.yml
- provider-ci/test-providers/acme/.github/workflows/lint.yml
- provider-ci/test-providers/aws/.github/workflows/lint.yml
- provider-ci/test-providers/cloudflare/.github/workflows/lint.yml
- provider-ci/test-providers/docker/.github/workflows/lint.yml
- provider-ci/test-providers/eks/.github/workflows/lint.yml
- provider-ci/test-providers/terraform-module/.github/workflows/lint.yml
The current version fails when used with go 1.24
Native providers seem to manage this in-repo in the ci-mgmt.yml config.
fixes https://github.com/pulumi/ci-mgmt/issues/1432
> Bump golangci-lint version

- provider-ci/internal/pkg/templates/base/.github/workflows/build_provider.yml
- provider-ci/internal/pkg/templates/base/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-providers/acme/.github/workflows/build_provider.yml
- provider-ci/test-providers/acme/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-providers/aws/.github/workflows/build_provider.yml
- provider-ci/test-providers/aws/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-providers/cloudflare/.github/workflows/build_provider.yml
- provider-ci/test-providers/cloudflare/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-providers/docker/.github/workflows/build_provider.yml
- provider-ci/test-providers/docker/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-providers/eks/.github/workflows/build_provider.yml
- provider-ci/test-providers/eks/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-providers/terraform-module/.github/workflows/build_provider.yml
- provider-ci/test-providers/terraform-module/.github/workflows/run-acceptance-tests.yml
A small optimization: when verifying PRs we only use the linux binary for amd64; with this change the runner will stop trying to build the binary for every other architecture and platform in this job.
> Optimize run-acceptance-tests: only build linux binaries

- provider-ci/internal/pkg/action-versions.yml
- provider-ci/internal/pkg/config.go
- provider-ci/internal/pkg/templates/base/.github/workflows/test.yml
- provider-ci/internal/pkg/templates/base/.github/workflows/verify-release.yml
- provider-ci/test-providers/docker/.github/workflows/test.yml
- provider-ci/test-providers/eks/.github/workflows/test.yml
- provider-ci/test-providers/terraform-module/.github/workflows/test.yml
This switches the AWS Access from hardcoded access keys that are pulled from GitHub secrets to use Pulumi ESC environments.
Tested in awsx in this pr https://github.com/pulumi/pulumi-awsx/pull/1563
re [#3731](https://github.com/pulumi/home/issues/3731)
> Switch AWS credentials to esc for base workflow

- provider-ci/internal/pkg/templates/base/.github/workflows/publish.yml
- provider-ci/test-providers/acme/.github/workflows/publish.yml
- provider-ci/test-providers/aws/.github/workflows/publish.yml
- provider-ci/test-providers/cloudflare/.github/workflows/publish.yml
- provider-ci/test-providers/docker/.github/workflows/publish.yml
- provider-ci/test-providers/eks/.github/workflows/publish.yml
Motivated by:
https://github.com/pulumi/pulumi-aws/issues/5337
https://github.com/pulumi/pulumi-aws/issues/5122
I was only able to resolve 5337 that kept failing on the publish_sdk step by clearing caches and a targeted re-run.  The AWS caches are too large. In particular the default Go cache. I think publish_sdk is better off opting out of Go cache just like `publish` is opting out of Go cache as they are not doing any particularly heavy Go compilation, and doing this alleviates the problem of downloading large caches and running out of disk space.
> publish_sdk no longer consults the Go cache

- provider-ci/internal/pkg/templates/base/.github/workflows/verify-release.yml
The `esc-action` will try to automatically install `esc` if it is not
already installed, but it currently does not support installing on
windows runners (see https://github.com/pulumi/esc-action/issues/10).
This adds a step when running on windows to install esc manually.
I tested this configuration here https://github.com/pulumi/pulumi-aws-apigateway/actions/runs/14068439461/job/39396604197
> Fix verify-release on windows

- native-provider-ci/src/goreleaser.ts
- native-provider-ci/src/provider.ts
- native-provider-ci/src/steps.ts
- native-provider-ci/src/workflows.ts
Our goal is for all providers to user provider-ci, and we don't ever plan to hook azure-native back up to the native-provider-ci. This leaves a lot of abandoned code in native-provider-ci that we can remove to hopefully leave that project a little easier to read/update as needed.
> Remove unused paths (mostly azure-native related) from native-provider-ci

- .github/ISSUE_TEMPLATE/0-ecosystem-providers.md
- provider-ci/providers.json
We no longer support this provider: https://github.com/pulumi/pulumi-onelogin. It should be removed from automations.
> Remove Onelogin provider

- provider-ci/internal/pkg/templates/bridged/.github/workflows/upgrade-provider.yml
- provider-ci/test-providers/acme/.github/workflows/upgrade-provider.yml
- provider-ci/test-providers/aws/.github/workflows/upgrade-provider.yml
- provider-ci/test-providers/docker/.github/workflows/upgrade-provider.yml
Fixes https://github.com/pulumi/ci-mgmt/issues/1141
As a concrete example, https://github.com/pulumi/pulumi-gcp/pull/3004 fails because it starts hitting .NET 8.0 issues. This brings us close to violating SLA on upstream upgrades for no good reason.  I do believe we are better off with separate PRs for upstream upgrades vs Pulumi internal dependencies.
> Upgrade provider should be upgrading upstream only

- provider-ci/internal/pkg/templates/base/Makefile
- provider-ci/test-providers/acme/Makefile
- provider-ci/test-providers/cloudflare/Makefile
- provider-ci/test-providers/docker/Makefile
- provider-ci/test-providers/eks/Makefile
This extends the existing allowMissingDocs config to also apply to the `PULUMI_MISSING_DOCS_ERROR` env var error during builds. This is only enabled on T2+ providers.
Follow-up on https://github.com/pulumi/ci-mgmt/pull/1379
> Allow missing resource docs in builds

- provider-ci/internal/pkg/templates/native/.github/workflows/build.yml
- provider-ci/internal/pkg/templates/native/.github/workflows/prerelease.yml
- provider-ci/internal/pkg/templates/native/.github/workflows/release.yml
- provider-ci/internal/pkg/templates/native/.github/workflows/run-acceptance-tests.yml
- provider-ci/internal/pkg/templates/native/.goreleaser.prerelease.yml
- provider-ci/internal/pkg/templates/native/.goreleaser.yml
This enables ci-mgmt to generate the CI for https://github.com/pulumi/pulumi-terraform (post https://github.com/pulumi/pulumi-terraform/pull/769).
The PR does not effect any other providers. To match the CI scripts found in https://github.com/pulumi/pulumi-terraform/pull/769, this PR needs to be stacked on top of #1491 and #1492.
dabadc905acabe096d2a62bd8cc50ab5b35ddd0b is a stack of all the PRs needed to get pulumi-terraform to fully comply with ci-mgmt. Running `make ci-mgmt` in pulumi-terraform on that version yields only the changes shown in <https://github.com/pulumi/pulumi-command/pull/737/files>.
> Add exceptions to support pulumi-terraform

- provider-ci/internal/pkg/action-versions.yml
- provider-ci/internal/pkg/templates/bridged/.github/workflows/upgrade-bridge.yml
- provider-ci/test-providers/acme/.github/workflows/upgrade-bridge.yml
- provider-ci/test-providers/acme/.github/workflows/upgrade-provider.yml
- provider-ci/test-providers/aws/.github/workflows/upgrade-bridge.yml
- provider-ci/test-providers/aws/.github/workflows/upgrade-provider.yml
- provider-ci/test-providers/cloudflare/.github/workflows/upgrade-bridge.yml
- provider-ci/test-providers/docker/.github/workflows/upgrade-bridge.yml
- provider-ci/test-providers/docker/.github/workflows/upgrade-provider.yml
This PR propagates the patch-release option to all upgrade-bridge workflows in providers. I still need to bump the upgrade-provider-action version after that PR is merged and released.
Related to https://github.com/pulumi/pulumi-upgrade-provider-action/pull/38
Part of https://github.com/pulumi/pulumi-terraform-bridge/issues/2267
> Add patch release option

- .github/workflows/close-pulumi-bot-prs.yml
- .github/workflows/lint-actions.yml
- .github/workflows/merge-dependabot.yml
- .github/workflows/refresh-gh-branch-protection.yml
- .github/workflows/test-provider-ci.yml
- .github/workflows/update-bridge-ecosystem-providers.yml
- .github/workflows/update-bridge-single-ecosystem-provider.yml
- .github/workflows/update-workflows-ecosystem-providers.yml
- .github/workflows/update-workflows-single-bridged-provider.yml
- .github/workflows/update-workflows.yml
These changes migrate this repo's GitHub Actions Workflows to use ESC secrets instead of GitHub Secrets.
The changes are largely mechanical:
- Common configuration for all ESC actions within a workflow is added to the workflow's environment variables
- Permissions are expanded as necessary for workflows that do not grant `id-token: write` permissions
- `read-all` permissions are replaced with the union of all explicit read permissions and `id-token: write`
- Default permissions are replaced with `write-all`, which is the equivalent of all explicit write permissions and
`id-token: write`
- Explicit permissions are modified to grant `id-token: write`
- A step that fetches ESC secrets and populates environment variables is added to each step that reads secrets
- Direct references to secrets …
> Use ESC secrets

- renovate.json5
We're still using v1.x of golangci-lint, so we need to keep the action on v6.x for now.
> Fix golangci-lint bumps

- .github/workflows/close-pulumi-bot-prs.yml
- .github/workflows/export-repo-secrets.yml
- .github/workflows/lint-actions.yml
- .github/workflows/merge-dependabot.yml
- .github/workflows/refresh-gh-branch-protection.yml
- .github/workflows/test-provider-ci.yml
- .github/workflows/update-bridge-ecosystem-providers.yml
- .github/workflows/update-bridge-single-ecosystem-provider.yml
- .github/workflows/update-workflows-ecosystem-providers.yml
- .github/workflows/update-workflows-single-bridged-provider.yml
- .github/workflows/update-workflows.yml
This repository has repository-specific secrets that need to be migrated to ESC. These changes replace the usage of the common GHA ESC environment with the repository-specific environment.
> Use repo-specific ESC environment

- provider-ci/internal/pkg/templates/base/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-providers/acme/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-providers/aws/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-providers/cloudflare/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-providers/docker/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-providers/eks/.github/workflows/run-acceptance-tests.yml
- provider-ci/test-providers/terraform-module/.github/workflows/run-acceptance-tests.yml
This pull request changes the `default_branch` input to schema-tools to use the base branch of the pull request that the PR is being made against.
This means schema-tools can compare changes on a feature branch, or a stack of PRs, and only show incremental changes, rather than only comparing against the repository default branch.
> Use pull request base as ref for schema-tools

- provider-ci/Makefile
- provider-ci/actionlint.yml
This newer version includes "ignore" support, which will become relevant for https://github.com/pulumi/ci-mgmt/issues/1481. Specifically, we will be using ESC to populate a bunch of dynamic outputs. These are normally flagged by actionlint, but in our case they will be expected.
I also removed the redundant config so now `.github/actionlint.yml` is the singular source of truth.
> Upgrade actionlint, consolidate config

- provider-ci/internal/pkg/templates/internal-bridged/.github/workflows/main-post-build.yml
- provider-ci/test-providers/aws/.github/workflows/main-post-build.yml
- provider-ci/test-providers/cloudflare/.github/workflows/main-post-build.yml
- provider-ci/test-providers/docker/.github/workflows/main-post-build.yml
There's nothing special about this directory, and it's more work than necessary to handle this using ESC.
`${{ runner.temp }}` is tied to the lifecycle of the job, so it is stable for the duration of `generate_coverage_data`.
> Remove an unnecessary secret

- provider-ci/internal/pkg/config.go
- provider-ci/internal/pkg/templates/defaults.config.yaml
This will make it possible for a provider to request their own ESC environment,
and it will enable us to move repo-specific secrets out of `.ci-mgmt.yaml`'s
`env:` key.
Refs https://github.com/pulumi/ci-mgmt/issues/1481
> Expose ESC config to ci-mgmt.yaml

- .github/workflows/update-java.yml
Continuing to iterate on update-java job. This fix makes sure jq formats the JSON payload on one line, which fixes a bug where the payload would not pass.
> Compact JSON

- provider-ci/internal/pkg/templates/bridged/.github/workflows/upgrade-java.yml
- provider-ci/test-providers/acme/.github/workflows/upgrade-java.yml
- provider-ci/test-providers/aws/.github/workflows/upgrade-java.yml
- provider-ci/test-providers/cloudflare/.github/workflows/upgrade-java.yml
- provider-ci/test-providers/docker/.github/workflows/upgrade-java.yml
- provider-ci/test-providers/xyz/.github/workflows/upgrade-java.yml
This attempts to address an issue that java update PRs have the wrong owner and do not trigger tests properly: https://github.com/pulumi/ci-mgmt/issues/1605#issuecomment-3081399781
> Propagate GH_TOKEN

- provider-ci/internal/pkg/templates/internal/.github/workflows/comment-on-stale-issues.yml
- provider-ci/test-providers/aws-native/.github/workflows/comment-on-stale-issues.yml
- provider-ci/test-providers/aws/.github/workflows/comment-on-stale-issues.yml
- provider-ci/test-providers/cloudflare/.github/workflows/comment-on-stale-issues.yml
- provider-ci/test-providers/command/.github/workflows/comment-on-stale-issues.yml
- provider-ci/test-providers/docker-build/.github/workflows/comment-on-stale-issues.yml
- provider-ci/test-providers/docker/.github/workflows/comment-on-stale-issues.yml
- provider-ci/test-providers/eks/.github/workflows/comment-on-stale-issues.yml
- provider-ci/test-providers/kubernetes-cert-manager/.github/workflows/comment-on-stale-issues.yml
- provider-ci/test-providers/kubernetes-coredns/.github/workflows/comment-on-stale-issues.yml
- provider-ci/test-providers/kubernetes-ingress-nginx/.github/workflows/comment-on-stale-issues.yml
- provider-ci/test-providers/kubernetes/.github/workflows/comment-on-stale-issues.yml
- provider-ci/test-providers/xyz/.github/workflows/comment-on-stale-issues.yml
We've discussed this a few times, but never quite pulled the trigger. This picks up the last PR: [[DO NOT MERGE] Create stale_issues.yaml · pulumi-aws/5366](https://github.com/pulumi/pulumi-aws/pull/5366) which tested this workflow against AWS. For this PR, I've kept the logic identical to that test, just moving it to ci-mgmt and running it on a cron: 
The action is configured to look for kind/bug issues that have not been updated in the last and have fewer than 2 upvotes. It would comment on these issues with the text:
>  Unfortunately, it looks like this issue hasn't seen any updates in a while. If you're still experiencing this issue, could you leave a quick comment to let us know so we can prioritize it?
and add the awaiting-feedback label. If a non-pulumi user replies, the issue will …
> Add a github workflow to comment on stale provider bugs

- provider-ci/internal/pkg/config.go
- provider-ci/internal/pkg/templates/internal/.github/workflows/comment-on-stale-issues.yml
- provider-ci/test-providers/aws-native/.github/workflows/comment-on-stale-issues.yml
- provider-ci/test-providers/aws/.ci-mgmt.yaml
- provider-ci/test-providers/cloudflare/.github/workflows/comment-on-stale-issues.yml
- provider-ci/test-providers/command/.github/workflows/comment-on-stale-issues.yml
- provider-ci/test-providers/docker-build/.github/workflows/comment-on-stale-issues.yml
- provider-ci/test-providers/docker/.github/workflows/comment-on-stale-issues.yml
- provider-ci/test-providers/eks/.github/workflows/comment-on-stale-issues.yml
- provider-ci/test-providers/kubernetes-cert-manager/.github/workflows/comment-on-stale-issues.yml
- provider-ci/test-providers/kubernetes-coredns/.github/workflows/comment-on-stale-issues.yml
- provider-ci/test-providers/kubernetes-ingress-nginx/.github/workflows/comment-on-stale-issues.yml
- provider-ci/test-providers/kubernetes/.github/workflows/comment-on-stale-issues.yml
- provider-ci/test-providers/xyz/.github/workflows/comment-on-stale-issues.yml
I thought I'd pushed this change before landing [Add a github workflow to comment on stale provider bugs · ci-mgmt/1633](https://github.com/pulumi/ci-mgmt/pull/1633), but I hadn't, so we blasted out a lot of comments at once. 😬 
This change will flip the stale issues workflow to dry-run for all providers, so we can try again with the gradual approach.
> Default to dryrun for stale issues workflow and add a config flag so we can roll it gradually

- provider-ci/internal/pkg/config.go
- provider-ci/internal/pkg/templates/defaults.config.yaml
These configs have been orphaned with regard to provider Workflows.
They do not exist in the bridge.
This pull request cleans up the references. Note there was a claim that pulumi-alicloud uses this setting: it is also orphaned there.
Closes https://github.com/pulumi/ci-mgmt/issues/1634.
> Remove Extra Mapping and Missing Mapping Errors from config

- provider-ci/internal/pkg/templates/native/.github/workflows/prerelease.yml
- provider-ci/internal/pkg/templates/native/.github/workflows/release.yml
- provider-ci/test-providers/aws-native/.github/workflows/prerelease.yml
- provider-ci/test-providers/aws-native/.github/workflows/release.yml
- provider-ci/test-providers/command/.github/workflows/prerelease.yml
- provider-ci/test-providers/command/.github/workflows/release.yml
- provider-ci/test-providers/docker-build/.github/workflows/prerelease.yml
- provider-ci/test-providers/docker-build/.github/workflows/release.yml
- provider-ci/test-providers/kubernetes-cert-manager/.github/workflows/prerelease.yml
- provider-ci/test-providers/kubernetes-cert-manager/.github/workflows/release.yml
- provider-ci/test-providers/kubernetes-coredns/.github/workflows/prerelease.yml
- provider-ci/test-providers/kubernetes-coredns/.github/workflows/release.yml
- provider-ci/test-providers/kubernetes-ingress-nginx/.github/workflows/prerelease.yml
- provider-ci/test-providers/kubernetes-ingress-nginx/.github/workflows/release.yml
- provider-ci/test-providers/kubernetes/.github/workflows/prerelease.yml
- provider-ci/test-providers/kubernetes/.github/workflows/release.yml
- provider-ci/test-providers/pulumi-provider-boilerplate/.github/workflows/prerelease.yml
- provider-ci/test-providers/pulumi-provider-boilerplate/.github/workflows/release.yml
A follow-up to https://github.com/pulumi/ci-mgmt/pull/1656
Updates the publish tasks to use the gradle command, since the setup-gradle action doesn't support it.
Also updates the publish tasks to use Gradle 7.6 for consistency.
> Gradle v4 redux

- provider-ci/internal/pkg/templates/defaults.config.yaml
- provider-ci/internal/pkg/templates/internal/.github/workflows/export-repo-secrets.yml
- provider-ci/test-providers/aws-native/.github/workflows/export-repo-secrets.yml
- provider-ci/test-providers/aws/.github/workflows/export-repo-secrets.yml
- provider-ci/test-providers/cloudflare/.github/workflows/export-repo-secrets.yml
- provider-ci/test-providers/command/.github/workflows/export-repo-secrets.yml
- provider-ci/test-providers/docker-build/.github/workflows/export-repo-secrets.yml
- provider-ci/test-providers/docker/.ci-mgmt.yaml
- provider-ci/test-providers/docker/.github/workflows/export-repo-secrets.yml
- provider-ci/test-providers/eks/.github/workflows/export-repo-secrets.yml
- provider-ci/test-providers/kubernetes-cert-manager/.github/workflows/export-repo-secrets.yml
- provider-ci/test-providers/kubernetes-coredns/.github/workflows/export-repo-secrets.yml
- provider-ci/test-providers/kubernetes-ingress-nginx/.github/workflows/export-repo-secrets.yml
- provider-ci/test-providers/kubernetes/.github/workflows/export-repo-secrets.yml
- provider-ci/test-providers/xyz/.github/workflows/export-repo-secrets.yml
This adds a new "Export secrets to ESC" workflow to our internal providers. The
workflow itself is copy-pasted from Pat's prior work. This workflow is
necessary in cases where the provider relies on repo-specific secrets. It may
need to be run at most once per provider, and we can remove this later when all
secrets have been migrated.
Confirmed working on docker-build:
```
❯ esc env get pulumi/github-secrets/pulumi-pulumi-docker-build
Value
{
"environmentVariables": {
...
}
}
Definition
imports:
- imports/github-secrets
values:
environmentVariables:
CODECOV_TOKEN:
...
DOCKER_HUB_PASSWORD:
...
```
Refs https://github.com/pulumi/ci-mgmt/issues/1481
> Add a provider workflow to export repo secrets

- provider-ci/internal/pkg/templates/base/Makefile
- provider-ci/test-providers/cloudflare/Makefile
- provider-ci/test-providers/docker/Makefile
This pull request addresses an oversight, where the generating of registry docs (the top-level provider landing page, under `docs/_index.md`) did not happen on the Make targets that `upgrade-provider` calls, resulting in issues such as https://github.com/pulumi/pulumi-docker/issues/1343.
Fixes #1667.
> Generate registry docs on appropriate targets

- provider-ci/internal/pkg/templates/native/.github/workflows/build.yml
- provider-ci/internal/pkg/templates/native/.github/workflows/prerelease.yml
- provider-ci/internal/pkg/templates/native/.github/workflows/release.yml
- provider-ci/test-providers/aws-native/.github/workflows/build.yml
- provider-ci/test-providers/aws-native/.github/workflows/prerelease.yml
- provider-ci/test-providers/aws-native/.github/workflows/release.yml
- provider-ci/test-providers/command/.github/workflows/build.yml
- provider-ci/test-providers/command/.github/workflows/prerelease.yml
- provider-ci/test-providers/command/.github/workflows/release.yml
- provider-ci/test-providers/docker-build/.github/workflows/build.yml
- provider-ci/test-providers/docker-build/.github/workflows/prerelease.yml
- provider-ci/test-providers/docker-build/.github/workflows/release.yml
- provider-ci/test-providers/kubernetes-cert-manager/.github/workflows/build.yml
- provider-ci/test-providers/kubernetes-cert-manager/.github/workflows/prerelease.yml
- provider-ci/test-providers/kubernetes-cert-manager/.github/workflows/release.yml
- provider-ci/test-providers/kubernetes-coredns/.github/workflows/build.yml
- provider-ci/test-providers/kubernetes-coredns/.github/workflows/prerelease.yml
- provider-ci/test-providers/kubernetes-coredns/.github/workflows/release.yml
- provider-ci/test-providers/kubernetes-ingress-nginx/.github/workflows/build.yml
- provider-ci/test-providers/kubernetes-ingress-nginx/.github/workflows/prerelease.yml
- provider-ci/test-providers/kubernetes-ingress-nginx/.github/workflows/release.yml
- provider-ci/test-providers/kubernetes/.github/workflows/build.yml
- provider-ci/test-providers/kubernetes/.github/workflows/prerelease.yml
- provider-ci/test-providers/kubernetes/.github/workflows/release.yml
- provider-ci/test-providers/pulumi-provider-boilerplate/.github/workflows/build.yml
- provider-ci/test-providers/pulumi-provider-boilerplate/.github/workflows/prerelease.yml
- provider-ci/test-providers/pulumi-provider-boilerplate/.github/workflows/release.yml
We only need these to sign the binary. Native providers do this during the goreleaser step, and bridged providers do it as part of `make provider`.
Refs #1481.
> Remove Azure signing secrets from the global environment

- provider-ci/internal/pkg/generate.go
- provider-ci/internal/pkg/templates/internal/.github/actions/esc-action/action.yaml
- provider-ci/internal/pkg/templates/internal/.github/actions/esc-action/index.js
- provider-ci/test-providers/aws-native/.github/actions/esc-action/action.yaml
- provider-ci/test-providers/aws-native/.github/actions/esc-action/index.js
- provider-ci/test-providers/aws/.github/actions/esc-action/action.yaml
- provider-ci/test-providers/aws/.github/actions/esc-action/index.js
- provider-ci/test-providers/cloudflare/.github/actions/esc-action/action.yaml
- provider-ci/test-providers/cloudflare/.github/actions/esc-action/index.js
- provider-ci/test-providers/command/.github/actions/esc-action/action.yaml
- provider-ci/test-providers/command/.github/actions/esc-action/index.js
- provider-ci/test-providers/docker-build/.github/actions/esc-action/action.yaml
- provider-ci/test-providers/docker-build/.github/actions/esc-action/index.js
- provider-ci/test-providers/docker/.github/actions/esc-action/action.yaml
- provider-ci/test-providers/docker/.github/actions/esc-action/index.js
- provider-ci/test-providers/eks/.github/actions/esc-action/action.yaml
- provider-ci/test-providers/eks/.github/actions/esc-action/index.js
- provider-ci/test-providers/kubernetes-cert-manager/.github/actions/esc-action/action.yaml
- provider-ci/test-providers/kubernetes-cert-manager/.github/actions/esc-action/index.js
- provider-ci/test-providers/kubernetes-coredns/.github/actions/esc-action/action.yaml
- provider-ci/test-providers/kubernetes-coredns/.github/actions/esc-action/index.js
- provider-ci/test-providers/kubernetes-ingress-nginx/.github/actions/esc-action/action.yaml
- provider-ci/test-providers/kubernetes-ingress-nginx/.github/actions/esc-action/index.js
- provider-ci/test-providers/kubernetes/.github/actions/esc-action/action.yaml
- provider-ci/test-providers/kubernetes/.github/actions/esc-action/index.js
- provider-ci/test-providers/xyz/.github/actions/esc-action/action.yaml
- provider-ci/test-providers/xyz/.github/actions/esc-action/index.js
This adds a small actions which has the same "interface" as ESC, but
which works with our existing CI environments. The action is trivial and
implemented as vanilla JavaScript to eliminate packaging pitfalls. (Only
JavaScript actions support the dynamic outputs we need.)
The action takes the CI job's environment and makes it available as an
output on the step, in the same way we will eventually consume secrets
as outputs from the esc-action step.
A new template method, `renderESCStep`, is also introduced which allows
us to toggle between the shim action and the actual ESC action. This
will allow us to roll out ESC gradually, and without needing to
introduce ESC conditionals around all of our steps.
This is a no-op. A subsequent PR will actually consume the new action.
Refs …
> Add an ESC shim action

- provider-ci/internal/pkg/templates/base/.github/workflows/verify-release.yml
- provider-ci/test-providers/aws/.github/workflows/verify-release.yml
- provider-ci/test-providers/xyz/.github/workflows/verify-release.yml
Some providers run a small program as part of the verify release workflow. That program might need credentials, so we can pass the same environment we use for tests to it.
Fixes https://github.com/pulumi/pulumi-azure/issues/3276.
Refs https://github.com/pulumi/ci-mgmt/issues/1481.
> Pass credentials to the verify release step

- provider-ci/internal/pkg/generate.go
- provider-ci/internal/pkg/templates/external/.github/workflows/resync-build.yml
- provider-ci/test-providers/acme/.github/workflows/publish.yml
- provider-ci/test-providers/acme/.github/workflows/resync-build.yml
- provider-ci/test-providers/acme/.github/workflows/verify-release.yml
- provider-ci/test-providers/pulumi-provider-boilerplate/.github/workflows/resync-build.yml
Fixes: #1738
In #1736, I changed some code so a set of environment variables was only added for Pulumi managed providers. In that set of environment variables, I missed these contain the secrets to publish to the various package registries.
I tweaked it now that these secrets are always set, but only more are added for Pulumi managed providers.
Tested manually on `pulumiverse/pulumi-grafana`:
* Before the fix: https://github.com/pulumiverse/pulumi-grafana/actions/runs/17937299375
* After the fix: https://github.com/pulumiverse/pulumi-grafana/actions/runs/17968917504
> Fix publish external providers

- provider-ci/internal/pkg/templates/base/Makefile
- provider-ci/test-providers/eks/Makefile
Bridged providers use Pulumi CLI to generate the Java SDK now, but this needs to be implemented separately in component providers.
This pull request adds an if/esle to the Makefile template so that CI updates to those providers can succeed for now, until those providers' codegen binaries can handle Pulumi CLI javagen also.
Fixes #1751
> Except eks, awsx, and apigateway from pulumi-cli-based javagen

- provider-ci/internal/pkg/migrations/maintain_golangci_config.go
- provider-ci/internal/pkg/templates/internal/.github/workflows/comment-on-stale-issues.yml
- provider-ci/test-providers/aws-native/.github/workflows/comment-on-stale-issues.yml
- provider-ci/test-providers/aws/.github/workflows/comment-on-stale-issues.yml
- provider-ci/test-providers/cloudflare/.github/workflows/comment-on-stale-issues.yml
- provider-ci/test-providers/command/.github/workflows/comment-on-stale-issues.yml
- provider-ci/test-providers/docker-build/.github/workflows/comment-on-stale-issues.yml
- provider-ci/test-providers/docker/.github/workflows/comment-on-stale-issues.yml
- provider-ci/test-providers/eks/.github/workflows/comment-on-stale-issues.yml
- provider-ci/test-providers/kubernetes-cert-manager/.github/workflows/comment-on-stale-issues.yml
- provider-ci/test-providers/kubernetes-coredns/.github/workflows/comment-on-stale-issues.yml
- provider-ci/test-providers/kubernetes-ingress-nginx/.github/workflows/comment-on-stale-issues.yml
- provider-ci/test-providers/kubernetes/.github/workflows/comment-on-stale-issues.yml
- provider-ci/test-providers/pulumi-provider-boilerplate/.github/workflows/comment-on-stale-issues.yml
- provider-ci/test-providers/xyz/.github/workflows/comment-on-stale-issues.yml
Some providers don't have golangci-lint configured at all, and we don't want migrations to fail in those cases. This changes the config migration to best-effort.
Fixes https://github.com/pulumi/ci-mgmt/issues/1754.
> Ignore golangci-lint migrate errors

- provider-ci/internal/pkg/templates/base/.github/workflows/build_sdk.yml
- provider-ci/test-providers/acme/.github/workflows/build_sdk.yml
- provider-ci/test-providers/aws/.github/workflows/build_sdk.yml
- provider-ci/test-providers/cloudflare/.github/workflows/build_sdk.yml
- provider-ci/test-providers/docker/.github/workflows/build_sdk.yml
- provider-ci/test-providers/eks/.github/workflows/build_sdk.yml
- provider-ci/test-providers/xyz/.github/workflows/build_sdk.yml
The library we use for `git-status-check` (picomatch) does not match
dotfiles by default unless a `.` is explicitly defined in the pattern
> Fix ignoring mise.lock in git-status-check
