provider-ci/generate-provider.ts
provider-ci/lib/action-versions.js
provider-ci/lib/workflows.js
provider-ci/providers/tailscale/repo/.github/workflows/main.yml
provider-ci/providers/tailscale/repo/.github/workflows/master.yml
provider-ci/providers/tailscale/repo/.github/workflows/prerelease.yml
provider-ci/providers/tailscale/repo/.github/workflows/release.yml
provider-ci/providers/tailscale/repo/.github/workflows/update-bridge.yml
provider-ci/src/workflows.ts

Part of https://github.com/pulumi/home/issues/933
This PR should allow us to generate a Workflow for building on a default branch named `main`.
I changed the class name as well to better illustrate the purpose of addressing a repo's default branch.

Allow for 'main' as branch name value

---

README.md

This summarizes my current understanding of how this repo works. Please let me know if something's missing!

Add a general purpose TL;DR overview to README

---

.github/workflows/update-all-providers.yml

This has to be merged to the main branch before it can be tested in the
context of GHA.

First pass at all-providers workflow.

---

.github/workflows/update-all-providers.yml
scripts/generate_providers_list.py

Complete all-providers GHA workflow.

---

provider-ci/src/goreleaser.ts

This is a backfill for the changes rolled out in https://github.com/pulumi/release-bot/issues/13.
@stack72 let me know if I'm missing something obvious 😅

adjust changelog generation for goreleaser

---

provider-ci/lib/new-workflows.js
provider-ci/lib/workflows.js
provider-ci/src/workflows.ts

We should not run a test suite on a plain documentation check

Skip tests on markdown changes only

---

provider-ci/src/goreleaser.ts

Fixes: https://github.com/pulumi/platform-providers-team/issues/9

Ensure we exclude non-changelog worthy commits from changelog

---

.github/workflows/deploy-all-providers.yml
.github/workflows/deploy-single-provider.yml
provider-ci/generate-provider.ts
provider-ci/lib/workflows.js
provider-ci/providers/alicloud/config.yaml
provider-ci/providers/alicloud/repo/.github/workflows/update-upstream-provider.yml
provider-ci/providers/yandex/repo/.github/workflows/update-upstream-provider.yml
provider-ci/src/workflows.ts

Add settings and config overrides, generate 2 providers to canary test
before generating workflow files for all providers in a future commit.

Use new tfgen settings, part 1.

---

provider-ci/providers/fastly/config.yaml
provider-ci/providers/fastly/repo/.goreleaser.prerelease.yml
provider-ci/providers/fastly/repo/.goreleaser.yml

To be merged after https://github.com/pulumi/pulumi-fastly/pull/152

Update fastly major version to 4

---

.github/workflows/update-workflows-all-providers.yml
.github/workflows/update-workflows-single-provider.yml

Repository input needs full path to repo.

Use full repo path

---

provider-ci/providers/artifactory/repo/.github/workflows/update-bridge.yml

First commit for the purpose of testing flow in single provider before updating more widely.

Try updating bridge with single provider

---

.github/workflows/update-bridge-single-provider.yml

Adding this because I wanted to use it for [#1896](https://github.com/pulumi/home/issues/1896) and thought it might be useful from time to time.

Add update-bridge-single-provider.yml

---

native-provider-ci/providers/google-native/repo/.github/workflows/build.yml
native-provider-ci/providers/google-native/repo/.github/workflows/prerelease.yml
native-provider-ci/providers/google-native/repo/.github/workflows/release.yml
native-provider-ci/providers/google-native/repo/.github/workflows/run-acceptance-tests.yml
native-provider-ci/providers/kubernetes/repo/.github/workflows/build.yml
native-provider-ci/providers/kubernetes/repo/.github/workflows/prerelease.yml
native-provider-ci/providers/kubernetes/repo/.github/workflows/release.yml
native-provider-ci/providers/kubernetes/repo/.github/workflows/run-acceptance-tests.yml
native-provider-ci/src/steps.ts

Copied from https://github.com/pulumi/pulumi-google-native/pull/655

Install gke-cloud-auth-plugin in gnative CI env

---

provider-ci/providers/newrelic/config.yaml
provider-ci/providers/newrelic/repo/.goreleaser.prerelease.yml
provider-ci/providers/newrelic/repo/.goreleaser.yml
provider-ci/providers/newrelic/repo/Makefile

Update Newrelic refs to v5

---

native-provider-ci/providers/aws-native/repo/.github/workflows/build.yml
native-provider-ci/providers/aws-native/repo/.github/workflows/prerelease.yml
native-provider-ci/providers/aws-native/repo/.github/workflows/release.yml
native-provider-ci/providers/azure-native/repo/.github/workflows/build.yml
native-provider-ci/providers/azure-native/repo/.github/workflows/prerelease.yml
native-provider-ci/providers/azure-native/repo/.github/workflows/release.yml
native-provider-ci/providers/command/repo/.github/workflows/build.yml
native-provider-ci/providers/command/repo/.github/workflows/prerelease.yml
native-provider-ci/providers/command/repo/.github/workflows/release.yml
native-provider-ci/providers/google-native/repo/.github/workflows/build.yml
native-provider-ci/providers/google-native/repo/.github/workflows/prerelease.yml
native-provider-ci/providers/google-native/repo/.github/workflows/release.yml
native-provider-ci/providers/kubernetes/repo/.github/workflows/build.yml
native-provider-ci/providers/kubernetes/repo/.github/workflows/prerelease.yml
native-provider-ci/providers/kubernetes/repo/.github/workflows/release.yml
native-provider-ci/src/workflows.ts

It looks like the new workflow inadvertently included some of the general publishing steps.

Fix Java publishing workflow

---

provider-ci/providers/tailscale/config.yaml
provider-ci/providers/tailscale/repo/.github/workflows/update-upstream-provider.yml

https://github.com/tailscale/terraform-provider-tailscale/releases/tag/v0.13.5

Switch the upstream org for tailscale which has migrated

---

provider-ci/src/make-bridged-provider-2.ts
provider-ci/src/make-bridged-provider.ts

See https://github.com/pulumi/pulumi-terraform-bridge/blob/master/pkg/tfgen/main.go#L182-L185

--overlays doesn't do anything in tfgen

---

provider-ci/providers/docker/config.yaml
provider-ci/providers/docker/repo/.goreleaser.prerelease.yml
provider-ci/providers/docker/repo/.goreleaser.yml
provider-ci/providers/docker/repo/Makefile

Upgrades Docker major version to v4.
Related work: https://github.com/pulumi/pulumi-docker/pull/429

Docker provider major version upgrade

---

provider-ci/providers/azure/config.yaml
provider-ci/providers/azure/repo/.github/workflows/main.yml
provider-ci/providers/azure/repo/.github/workflows/master.yml
provider-ci/providers/azure/repo/.github/workflows/prerelease.yml
provider-ci/providers/azure/repo/.github/workflows/release.yml

- [failure with parallelism 2](https://github.com/pulumi/pulumi-azure/actions/runs/3644901904)
- [success with parallelism 1](https://github.com/pulumi/pulumi-azure/actions/runs/3651086786)

Reduce goreleaser parallelism for pulumi-azure due to OOM

---

provider-ci/providers/akamai/config.yaml
provider-ci/providers/akamai/repo/.goreleaser.prerelease.yml
provider-ci/providers/akamai/repo/.goreleaser.yml
provider-ci/providers/akamai/repo/Makefile

Followup to https://github.com/pulumi/pulumi-akamai/pull/121.

Upgrade Akamai major version to 4

---

provider-ci/providers/fastly/config.yaml
tools/sourcemigrator/index.ts

Depends on https://github.com/pulumi/pulumi-fastly/pull/201

Fastly: v5 to v6

---

provider-ci/providers/venafi/config.yaml
provider-ci/providers/venafi/repo/.github/workflows/command-dispatch.yml
provider-ci/providers/venafi/repo/.github/workflows/main.yml
provider-ci/providers/venafi/repo/.github/workflows/master.yml
provider-ci/providers/venafi/repo/.github/workflows/prerelease.yml
provider-ci/providers/venafi/repo/.github/workflows/pull-request.yml
provider-ci/providers/venafi/repo/.github/workflows/release.yml
provider-ci/providers/venafi/repo/.github/workflows/resync-build.yml
provider-ci/providers/venafi/repo/.github/workflows/run-acceptance-tests.yml
provider-ci/providers/venafi/repo/.github/workflows/update-upstream-provider.yml

Aligns the Venafi provider's config with the latest upgrade PR:
- https://github.com/pulumi/pulumi-venafi/pull/83

migrate Venafi to new secrets

---

.github/workflows/rollout-native-provider-workflows.yml
.github/workflows/rollout-single-native-provider-workflow.yml
.github/workflows/update-workflows-bridged-providers.yml
.github/workflows/update-workflows-single-bridged-provider.yml

Fixes issue such as this one:
https://github.com/pulumi/ci-mgmt/actions/runs/4107036664

Install go 1.19 as source code migrator requires it for go mod tidy

---

infra/providers/index.ts
infra/providers/package-lock.json
infra/providers/package.json

Before deleting branch protections we don't want to manage, mark them as retainOnDelete so that Pulumi does not actually make changes to those repos.

Use retain on delete

---

.github/workflows/update-gh-branch-protection.yml
infra/providers/index.ts

Testing what would happen on a subsequent pulumi up on this stack.. testing on one provider only..

Limit to venafi

---

provider-ci/providers/azure/config.yaml
provider-ci/providers/azure/repo/Makefile

https://github.com/pulumi/pulumi-azure/pull/1197 made a change to the Makefile in pulumi-azure; but the Makefile is generated here, so the change would be overwritten by any subsequent push. This updates the config.yaml for pulumi-azure so that the generated Makefile has the change made locally.

Copy local change to pulumi-azure

---

provider-ci/providers/docker/config.yaml
provider-ci/providers/docker/repo/.github/workflows/command-dispatch.yml
provider-ci/providers/docker/repo/.github/workflows/main.yml
provider-ci/providers/docker/repo/.github/workflows/master.yml
provider-ci/providers/docker/repo/.github/workflows/prerelease.yml
provider-ci/providers/docker/repo/.github/workflows/pull-request.yml
provider-ci/providers/docker/repo/.github/workflows/release.yml
provider-ci/providers/docker/repo/.github/workflows/resync-build.yml
provider-ci/providers/docker/repo/.github/workflows/run-acceptance-tests.yml
provider-ci/providers/docker/repo/.github/workflows/update-upstream-provider.yml
provider-ci/src/steps.ts
provider-ci/src/workflows.ts

https://github.com/pulumi/pulumi-docker/pull/505

add gcloud auth setup to docker provider for docker gcp tests

---

.github/workflows/update-bridge-ecosystem-providers.yml

Mirrors https://github.com/pulumi/ci-mgmt/blob/master/.github/workflows/update-workflows-bridged-providers.yml specifically for team-ecosystem-maintained providers

Add update-bridge-ecosystem-providers workflow

---

provider-ci/providers/fastly/config.yaml
provider-ci/providers/fastly/repo/.goreleaser.prerelease.yml
provider-ci/providers/fastly/repo/.goreleaser.yml
provider-ci/providers/fastly/repo/Makefile

Need https://github.com/pulumi/pulumi-fastly/pull/225 to land first

Upgrade fastly provider to v7

---

provider-ci/providers/aiven/config.yaml
provider-ci/providers/aiven/repo/.goreleaser.prerelease.yml
provider-ci/providers/aiven/repo/.goreleaser.yml
provider-ci/providers/aiven/repo/Makefile

Wait for https://github.com/pulumi/pulumi-aiven/pull/260 to merge

Upgrade aiven provider to v6

---

provider-ci/providers/docker/repo/Makefile
provider-ci/src/make-bridged-provider.ts

Fixes https://github.com/pulumi/pulumi-docker/actions/runs/4471134859/jobs/7855608608?pr=557#step:9:305

Respect already set dependencies for Hybrid Providers

---

provider-ci/providers/newrelic/config.yaml
provider-ci/providers/newrelic/repo/.goreleaser.prerelease.yml
provider-ci/providers/newrelic/repo/.goreleaser.yml
provider-ci/src/config.ts
provider-ci/src/goreleaser.ts

Fixes https://github.com/pulumi/pulumi-newrelic/issues/361

Allow user agent to be set via ldflags for `pulumi-newrelic`

---

provider-ci/providers/rancher2/config.yaml
provider-ci/providers/rancher2/repo/.goreleaser.prerelease.yml
provider-ci/providers/rancher2/repo/.goreleaser.yml
provider-ci/providers/rancher2/repo/Makefile

Part of https://github.com/pulumi/pulumi-rancher2/pull/202

Update rancher2 to v4

---

provider-ci/providers/linode/config.yaml
provider-ci/providers/linode/repo/.goreleaser.prerelease.yml
provider-ci/providers/linode/repo/.goreleaser.yml
provider-ci/providers/linode/repo/Makefile

Part of https://github.com/pulumi/pulumi-linode/pull/253

Upgrade pulumi-linode to v4

---

provider-ci/providers/fastly/config.yaml
provider-ci/providers/fastly/repo/.goreleaser.prerelease.yml
provider-ci/providers/fastly/repo/.goreleaser.yml
provider-ci/providers/fastly/repo/Makefile

Part of https://github.com/pulumi/pulumi-fastly/pull/270

Upgrade `pulumi-fastly` to v8

---

provider-ci/providers/gitlab/config.yaml
provider-ci/providers/gitlab/repo/.goreleaser.prerelease.yml
provider-ci/providers/gitlab/repo/.goreleaser.yml
provider-ci/providers/gitlab/repo/Makefile

Part of https://github.com/pulumi/pulumi-gitlab/pull/282

Upgrade `pulumi-gitlab` to v6

---

provider-ci/providers/oci/config.yaml
provider-ci/providers/oci/repo/.goreleaser.prerelease.yml
provider-ci/providers/oci/repo/.goreleaser.yml
provider-ci/providers/oci/repo/Makefile

Part of https://github.com/pulumi/pulumi-oci/pull/149

Upgrade `pulumi-oci` major version to v2

---

provider-ci/providers/rancher2/config.yaml
provider-ci/providers/rancher2/repo/.goreleaser.prerelease.yml
provider-ci/providers/rancher2/repo/.goreleaser.yml
provider-ci/providers/rancher2/repo/Makefile

Part of https://github.com/pulumi/pulumi-rancher2/pull/229

Bump rancher2 major version

---

provider-ci/providers/artifactory/config.yaml
provider-ci/providers/artifactory/repo/.goreleaser.prerelease.yml
provider-ci/providers/artifactory/repo/.goreleaser.yml
provider-ci/providers/artifactory/repo/Makefile

Followup for Artifactory major release update

Update pulumi-artifactory to v4

---

provider-ci/providers/gcp/config.yaml
provider-ci/providers/gcp/repo/Makefile

This reflects the change made in https://github.com/pulumi/pulumi-gcp/pull/1141.

Add `http` as a dependency of `gcp`

---

infra/providers/package-lock.json
infra/providers/package.json
native-provider-ci/package-lock.json
provider-ci/go.mod
provider-ci/go.sum

Combining multiple dependencies PRs into one.
<details>
<summary>Instructions for merging</summary>
* **Use a merge commit**, so that GitHub will mark all original PRs as merged.
* If your repository does not have merge commits enabled, please temporarily enable them in settings. Tick `Allow merge commits` in the repository settings.
* When ready, merge this PR using `Create a merge commit`.
</details>
* Bump word-wrap from 1.2.3 to 1.2.4 in /native-provider-ci (#481) @app/dependabot
* Bump semver from 5.7.1 to 5.7.2 in /infra/providers (#479) @app/dependabot
* Bump @grpc/grpc-js and @pulumi/pulumi in /infra/providers (#475) @app/dependabot
* Bump golang.org/x/crypto from 0.0.0-20191011191535-87dc89f01550 to 0.1.0 in /provider-ci (#455) @app/dependabot
* Bump yaml from 2.0.0-5 to 2.2.2 in …

Combined dependencies PR

---

provider-ci/providers/mongodbatlas/config.yaml
provider-ci/providers/mongodbatlas/repo/Makefile

Corresponding to https://github.com/pulumi/pulumi-mongodbatlas/pull/261

Upgrade MongoDBAtlas's Java version

---

provider-ci/providers/ec/config.yaml
provider-ci/providers/ec/repo/Makefile

This is from https://github.com/pulumi/pulumi-ec/pull/128

Bump pulumi-ec's java version

---

provider-ci/providers/akamai/config.yaml
provider-ci/providers/akamai/repo/.goreleaser.prerelease.yml
provider-ci/providers/akamai/repo/.goreleaser.yml
provider-ci/providers/akamai/repo/Makefile

This also bumps the java version.

Bump akamai major version

---

provider-ci/providers/vault/config.yaml
provider-ci/providers/vault/repo/Makefile

See https://github.com/pulumi/pulumi-vault/pull/296 for details.

Incorporate the changes made in pulumi-vault#296

---

provider-ci/providers/aws/config.yaml
provider-ci/providers/aws/repo/.github/workflows/main.yml
provider-ci/providers/aws/repo/.github/workflows/master.yml
provider-ci/providers/aws/repo/.github/workflows/prerelease.yml
provider-ci/providers/aws/repo/.github/workflows/release.yml
provider-ci/providers/aws/repo/.github/workflows/run-acceptance-tests.yml

Reflects the changes made in https://github.com/pulumi/pulumi-aws/pull/2768.

Always run `go_shim_test`

---

provider-ci/providers/aws/config.yaml

Apply https://github.com/pulumi/pulumi-aws/pull/2772 to `aws/config.yaml`.

Add code coverage for aws custom test

---

provider-ci/providers/aws/config.yaml
provider-ci/providers/aws/repo/.github/workflows/main.yml
provider-ci/providers/aws/repo/.github/workflows/master.yml
provider-ci/providers/aws/repo/.github/workflows/prerelease.yml
provider-ci/providers/aws/repo/.github/workflows/release.yml
provider-ci/providers/aws/repo/.github/workflows/run-acceptance-tests.yml

Follow up on https://github.com/pulumi/ci-mgmt/pull/547.

Regenerate workflows

---

provider-ci/providers/vault/config.yaml
provider-ci/providers/vault/repo/.github/workflows/command-dispatch.yml
provider-ci/providers/vault/repo/.github/workflows/main.yml
provider-ci/providers/vault/repo/.github/workflows/master.yml
provider-ci/providers/vault/repo/.github/workflows/prerelease.yml
provider-ci/providers/vault/repo/.github/workflows/pull-request.yml
provider-ci/providers/vault/repo/.github/workflows/release.yml
provider-ci/providers/vault/repo/.github/workflows/resync-build.yml
provider-ci/providers/vault/repo/.github/workflows/run-acceptance-tests.yml

In repo PR is https://github.com/pulumi/pulumi-vault/pull/309.

Enable vault testing

---

.github/workflows/update-workflows-bridged-providers.yml
.github/workflows/update-workflows-single-bridged-provider.yml
provider-ci/internal/pkg/templates/bridged-provider/Makefile
provider-ci/providers/aws/config.yaml
provider-ci/providers/aws/repo/.github/workflows/main.yml
provider-ci/providers/aws/repo/.github/workflows/master.yml
provider-ci/providers/aws/repo/.github/workflows/prerelease.yml
provider-ci/providers/aws/repo/.github/workflows/release.yml
provider-ci/providers/aws/repo/Makefile
provider-ci/providers/gcp/config.yaml
provider-ci/providers/gcp/repo/.github/workflows/main.yml
provider-ci/providers/gcp/repo/.github/workflows/master.yml
provider-ci/providers/gcp/repo/.github/workflows/prerelease.yml
provider-ci/providers/gcp/repo/.github/workflows/release.yml
provider-ci/providers/gcp/repo/Makefile
provider-ci/providers/random/config.yaml
provider-ci/providers/random/repo/.github/workflows/main.yml
provider-ci/providers/random/repo/.github/workflows/master.yml
provider-ci/providers/random/repo/.github/workflows/prerelease.yml
provider-ci/providers/random/repo/.github/workflows/release.yml
provider-ci/providers/random/repo/Makefile
tools/sourcemigrator/index.ts

Experimenting here, will run through a few providers before rolling out to the rest.
The Makefile edit has to go together with resources.go edit and regenerating Python files atomically in one PR this is a bit tricky.

Wheels for bridged providers

---

provider-ci/providers/gcp/config.yaml
provider-ci/providers/gcp/repo/.github/workflows/main.yml
provider-ci/providers/gcp/repo/.github/workflows/master.yml
provider-ci/providers/gcp/repo/.github/workflows/nightly-test.yml
provider-ci/providers/gcp/repo/.github/workflows/prerelease.yml
provider-ci/providers/gcp/repo/.github/workflows/release.yml
provider-ci/providers/gcp/repo/.github/workflows/run-acceptance-tests.yml
provider-ci/providers/gcp/repo/.github/workflows/update-bridge.yml

This works around a recent failure of nightly cron.

Use a more powerful runner for GCP workflows

---

provider-ci/providers/tls/config.yaml
provider-ci/providers/tls/repo/.github/workflows/main.yml
provider-ci/providers/tls/repo/.github/workflows/master.yml
provider-ci/providers/tls/repo/.github/workflows/prerelease.yml
provider-ci/providers/tls/repo/.github/workflows/release.yml
provider-ci/providers/tls/repo/Makefile

Rolls out the Python wheels feature to the TLS provider.

Enable wheels for the TLS provider

---

provider-ci/providers/hcloud/config.yaml
provider-ci/providers/hcloud/repo/Makefile
provider-ci/providers/local/config.yaml
provider-ci/providers/local/repo/Makefile

Followup for Java upgrades.
Part of #506 as well.
- local: update javaGenVersion to v0.9.5
- hcloud: update javaGenVersion to v0.9.5

Java upgrades for hcloud and local

---

provider-ci/providers/equinix-metal/config.yaml
provider-ci/providers/equinix-metal/repo/Makefile
provider-ci/providers/kong/config.yaml
provider-ci/providers/kong/repo/Makefile

What it says on the box. Part of #506.
- kong: update javaGenVersion to v0.9.5
- equinix-metal: update javaGenVersion to v0.9.5

Java upgrades for kong and equinix-metal

---

provider-ci/providers/cloudinit/config.yaml
provider-ci/providers/cloudinit/repo/Makefile

What it says on the title.
Part of #506.

cloudinit: update javaGenVersion to v0.9.5

---

provider-ci/providers/external/config.yaml
provider-ci/providers/external/repo/Makefile
provider-ci/providers/github/config.yaml
provider-ci/providers/github/repo/Makefile
provider-ci/providers/http/config.yaml
provider-ci/providers/http/repo/Makefile

Working through a few provider upgrades and syncing workflows.

Updates from Sep 20

---

provider-ci/providers/dnsimple/config.yaml
provider-ci/providers/dnsimple/repo/Makefile

What it says on the title.
Part of #506.

dnsimple: update javaGenVersion to v0.9.5

---

.github/workflows/update-native-provider-workflows.yml
.github/workflows/update-workflows.yml

Fixes https://github.com/pulumi/ci-mgmt/issues/615
Failing run (scheduled):
https://github.com/pulumi/ci-mgmt/actions/runs/6308264372
Succeeding run with these changes applied:
https://github.com/pulumi/ci-mgmt/actions/runs/6313820033/job/17142756858

Fix update-native-provider-workflows

---

.github/workflows/update-workflows-ecosystem-providers.yml

Here is the overnight run that failed:
https://github.com/pulumi/ci-mgmt/actions/runs/6308256708
Here is the run with this change that gets past the failure:
https://github.com/pulumi/ci-mgmt/actions/runs/6313368335/job/17141279074

Fix update-workflows-ecosystem-providers

---

.github/workflows/lint-ecosystem-providers.yml

Part of #344.
We'll have to merge this first and then see if it does what we want because Actions need to be merged to default.

Run make lint providers as part of CI

---

tools/sourcemigrator/index.ts

Fixes #624 
This should fix https://github.com/pulumi/ci-mgmt/issues/624 generically. Running a test on one of the providers.
https://github.com/pulumi/pulumi-alicloud/pull/455
If we merge it should roll out overnight to all bridged providers at least.

Add sdk/python/env to .gitignore files across the board.

---

provider-ci/Makefile

Following up on PR feedback with a comment.

Comment unusual choice of git commands

---

provider-ci/providers/ns1/config.yaml
provider-ci/providers/ns1/repo/Makefile
provider-ci/providers/okta/config.yaml
provider-ci/providers/okta/repo/Makefile
provider-ci/providers/slack/config.yaml
provider-ci/providers/slack/repo/Makefile

Reset the versions to what's actually found in these repositories, to unblock workflow rollout.

Sync Java versions

---

scripts/generate_native_providers_list.py

Kubernetes is in sync with ci-mgmt, let's keep it that way!

Add kubernetes to the autogenerated workflow PRs

---

provider-ci/providers/spotinst/config.yaml

This reflects the changes made in https://github.com/pulumi/pulumi-spotinst/pull/430.

Upgrade spotinist's java version to v0.9.5

---

provider-ci/providers/azuread/config.yaml

Pairs with https://github.com/pulumi/pulumi-azuread/pull/485

Update java for azuread

---

.github/workflows/update-workflows.yml

Example PR is https://github.com/pulumi/pulumi-external/pull/29.
Example workflow is https://github.com/pulumi/ci-mgmt/actions/runs/6422787003/job/17439993108.

Enable auto-merge when set

---

provider-ci/internal/pkg/templates/bridged-provider/Makefile
provider-ci/test-workflows/aws/Makefile
provider-ci/test-workflows/cloudflare/Makefile
provider-ci/test-workflows/docker/Makefile

I have tested this locally and it works as expected.

Scope HOME to pulumi download

---

provider-ci/internal/pkg/templates/bridged-provider.config.yaml
provider-ci/test-workflows/aws/.github/workflows/upgrade-bridge.yml
provider-ci/test-workflows/aws/.github/workflows/upgrade-provider.yml
provider-ci/test-workflows/cloudflare/.github/workflows/upgrade-bridge.yml
provider-ci/test-workflows/cloudflare/.github/workflows/upgrade-provider.yml
provider-ci/test-workflows/docker/.github/workflows/upgrade-bridge.yml
provider-ci/test-workflows/docker/.github/workflows/upgrade-provider.yml

Upgrade upgrade-provider-action to v0.0.7

---

provider-ci/providers/equinix-metal/config.yaml

Part of https://github.com/pulumi/pulumi-equinix-metal/issues/136.

Remove equinix-metal as no longer maintained by Pulumi

---

.github/workflows/update-workflows-ecosystem-providers.yml

PoC to try out new Actions OUTPUT and also fix reading in the provider list

Fix up update-bridge workflow

---

.github/workflows/update-bridge-ecosystem-providers.yml

We have merged all workflow updates, so this will work.

Apply automerge to bridge updates

---

provider-ci/Makefile
provider-ci/internal/pkg/templates/bridged-provider/scripts/upstream.sh
provider-ci/test-workflows/aws/scripts/upstream.sh
provider-ci/test-workflows/cloudflare/scripts/upstream.sh
provider-ci/test-workflows/docker/scripts/upstream.sh

Fix rebase target

---

provider-ci/internal/pkg/templates/bridged-provider.config.yaml
provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/upgrade-bridge.yml
provider-ci/test-workflows/aws/.github/workflows/upgrade-bridge.yml
provider-ci/test-workflows/aws/.github/workflows/upgrade-provider.yml
provider-ci/test-workflows/cloudflare/.github/workflows/upgrade-bridge.yml
provider-ci/test-workflows/cloudflare/.github/workflows/upgrade-provider.yml
provider-ci/test-workflows/docker/.github/workflows/upgrade-bridge.yml
provider-ci/test-workflows/docker/.github/workflows/upgrade-provider.yml

Companion to https://github.com/pulumi/pulumi-upgrade-provider-action/pull/21

Support --target-pulumi-version

---

.github/ISSUE_TEMPLATE/0-ecosystem-providers.md

Remove a deprecated provider from our list of all providers.

Remove deprecated provider

---

native-provider-ci/providers/aws-native/repo/.github/workflows/weekly-pulumi-update.yml
native-provider-ci/providers/azure-native/repo/.github/workflows/weekly-pulumi-update.yml
native-provider-ci/providers/command/repo/.github/workflows/weekly-pulumi-update.yml
native-provider-ci/providers/google-native/repo/.github/workflows/weekly-pulumi-update.yml
native-provider-ci/providers/kubernetes/repo/.github/workflows/weekly-pulumi-update.yml
native-provider-ci/src/provider.ts
native-provider-ci/src/steps.ts

Fixes https://github.com/pulumi/pulumi-command/issues/297
Tested in https://github.com/pulumi/pulumi-command/pull/299

Native providers: Allow empty modules update

---

provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/license.yml
provider-ci/test-workflows/aws/.github/workflows/license.yml
provider-ci/test-workflows/cloudflare/.github/workflows/license.yml
provider-ci/test-workflows/docker/.github/workflows/license.yml

Enables https://github.com/pulumi/pulumi-artifactory/actions/runs/6741486245/job/18326159928?pr=502.

Add allowed test

---

scripts/merge_dependabot.sh

The long term plan is to fully automate this job. We could either:
- Put a cron job in each repo, triggering weekly to update it's own dependencies.
- Run a cron from this repo that updates dependencies in every provider.
This manual script is a stop-gap solution, but I believe it is worth checking in as is.

Add bulk merge script dependabot

---

provider-ci/internal/pkg/templates/bridged-provider/Makefile
provider-ci/test-workflows/aws/Makefile
provider-ci/test-workflows/cloudflare/Makefile
provider-ci/test-workflows/docker/Makefile

I missed this in https://github.com/pulumi/ci-mgmt/pull/718. Necessary to avoid any conflicts with actual files.

Add provider_no_deps to phony

---

scripts/monitor_versions.sh

Checking in a quick script to monitor latest provider releases to find out which dependency versions they have.

Version monitoring script

---

.github/workflows/merge-dependabot.yml

Call `./scripts/merge_dependabot.sh` every 4 days.

Merge dependabot cron

---

provider-ci/internal/pkg/templates/bridged-provider.config.yaml
provider-ci/test-workflows/aws/.github/workflows/command-dispatch.yml
provider-ci/test-workflows/aws/.github/workflows/license.yml
provider-ci/test-workflows/aws/.github/workflows/lint.yml
provider-ci/test-workflows/aws/.github/workflows/master.yml
provider-ci/test-workflows/aws/.github/workflows/nightly-test.yml
provider-ci/test-workflows/aws/.github/workflows/prerelease.yml
provider-ci/test-workflows/aws/.github/workflows/pull-request.yml
provider-ci/test-workflows/aws/.github/workflows/release.yml
provider-ci/test-workflows/aws/.github/workflows/resync-build.yml
provider-ci/test-workflows/aws/.github/workflows/run-acceptance-tests.yml
provider-ci/test-workflows/cloudflare/.github/workflows/command-dispatch.yml
provider-ci/test-workflows/cloudflare/.github/workflows/license.yml
provider-ci/test-workflows/cloudflare/.github/workflows/lint.yml
provider-ci/test-workflows/cloudflare/.github/workflows/master.yml
provider-ci/test-workflows/cloudflare/.github/workflows/prerelease.yml
provider-ci/test-workflows/cloudflare/.github/workflows/pull-request.yml
provider-ci/test-workflows/cloudflare/.github/workflows/release.yml
provider-ci/test-workflows/cloudflare/.github/workflows/resync-build.yml
provider-ci/test-workflows/cloudflare/.github/workflows/run-acceptance-tests.yml
provider-ci/test-workflows/docker/.github/workflows/command-dispatch.yml
provider-ci/test-workflows/docker/.github/workflows/license.yml
provider-ci/test-workflows/docker/.github/workflows/lint.yml
provider-ci/test-workflows/docker/.github/workflows/master.yml
provider-ci/test-workflows/docker/.github/workflows/prerelease.yml
provider-ci/test-workflows/docker/.github/workflows/pull-request.yml
provider-ci/test-workflows/docker/.github/workflows/release.yml
provider-ci/test-workflows/docker/.github/workflows/resync-build.yml
provider-ci/test-workflows/docker/.github/workflows/run-acceptance-tests.yml

According to [pypi](https://pypi.org/help/):
```
To use an API token:
* Set your username to __token__
* Set your password to the token value, including the pypi- prefix
```
Fixes https://github.com/pulumi/ci-mgmt/issues/751
I tested this end to end in pulumi-mysql: https://github.com/pulumi/pulumi-mysql/actions/runs/7350064841/job/20011366694.

PyPi switch to API Token

---

infra/providers/index.ts
infra/providers/package-lock.json
infra/providers/package.json

This PR seperates protection management between native and bridged providers. Bridged providers are setup to comply with new bridged PR standards. Expect changes across all providers:
- required checks is reduced to "sentinel" and "Update Changelog"
- requiredApprovingReviewCount is set to 0, removing the requirement.
This is follow-up for https://github.com/pulumi/ci-mgmt/pull/773. Right now, most of our providers require an approving review to merge, which is part of the reason we have 60 "Update Github Workflows." PRs open.

Correctly apply infra to bridged providers

---

provider-ci/internal/pkg/templates/bridged-provider.config.yaml
provider-ci/test-workflows/aws/.github/workflows/master.yml
provider-ci/test-workflows/aws/.github/workflows/nightly-test.yml
provider-ci/test-workflows/aws/.github/workflows/prerelease.yml
provider-ci/test-workflows/aws/.github/workflows/release.yml
provider-ci/test-workflows/aws/.github/workflows/resync-build.yml
provider-ci/test-workflows/aws/.github/workflows/run-acceptance-tests.yml
provider-ci/test-workflows/cloudflare/.github/workflows/master.yml
provider-ci/test-workflows/cloudflare/.github/workflows/prerelease.yml
provider-ci/test-workflows/cloudflare/.github/workflows/release.yml
provider-ci/test-workflows/cloudflare/.github/workflows/resync-build.yml
provider-ci/test-workflows/cloudflare/.github/workflows/run-acceptance-tests.yml
provider-ci/test-workflows/docker/.github/workflows/master.yml
provider-ci/test-workflows/docker/.github/workflows/prerelease.yml
provider-ci/test-workflows/docker/.github/workflows/release.yml
provider-ci/test-workflows/docker/.github/workflows/resync-build.yml
provider-ci/test-workflows/docker/.github/workflows/run-acceptance-tests.yml

Routine upgrade, hoping the new version  has better features.

Upgrade jaxxstorm/action-install-gh-release to v1.10.0

---

provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/main.yml
provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/prerelease.yml
provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/release.yml
provider-ci/providers/aws/config.yaml
provider-ci/test-workflows/aws/.github/workflows/master.yml
provider-ci/test-workflows/aws/.github/workflows/nightly-test.yml
provider-ci/test-workflows/aws/.github/workflows/prerelease.yml
provider-ci/test-workflows/aws/.github/workflows/release.yml
provider-ci/test-workflows/aws/.github/workflows/run-acceptance-tests.yml
provider-ci/test-workflows/cloudflare/.github/workflows/master.yml
provider-ci/test-workflows/cloudflare/.github/workflows/prerelease.yml
provider-ci/test-workflows/cloudflare/.github/workflows/release.yml
provider-ci/test-workflows/docker/.github/workflows/master.yml
provider-ci/test-workflows/docker/.github/workflows/prerelease.yml
provider-ci/test-workflows/docker/.github/workflows/release.yml

addresses the comment in https://github.com/pulumi/ci-mgmt/pull/833

Pin free disk space action version

---

provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/main.yml
provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/prerelease.yml
provider-ci/test-workflows/aws/.github/workflows/master.yml
provider-ci/test-workflows/aws/.github/workflows/prerelease.yml
provider-ci/test-workflows/cloudflare/.github/workflows/master.yml
provider-ci/test-workflows/cloudflare/.github/workflows/prerelease.yml
provider-ci/test-workflows/docker/.github/workflows/master.yml
provider-ci/test-workflows/docker/.github/workflows/prerelease.yml

The typo was introduced in https://github.com/pulumi/ci-mgmt/pull/834

Fix free-disk-spacev typo

---

provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/main.yml
provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/prerelease.yml
provider-ci/test-workflows/aws/.github/workflows/master.yml
provider-ci/test-workflows/aws/.github/workflows/prerelease.yml
provider-ci/test-workflows/cloudflare/.github/workflows/master.yml
provider-ci/test-workflows/cloudflare/.github/workflows/prerelease.yml
provider-ci/test-workflows/docker/.github/workflows/master.yml
provider-ci/test-workflows/docker/.github/workflows/prerelease.yml

Today I learned that you cannot pin a partial version in github actions: https://github.com/orgs/community/discussions/39519.

Fix typo take 2

---

provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/release.yml
provider-ci/test-workflows/aws/.github/workflows/release.yml
provider-ci/test-workflows/cloudflare/.github/workflows/release.yml
provider-ci/test-workflows/docker/.github/workflows/release.yml

Finish the work started in https://github.com/pulumi/ci-mgmt/pull/837
Fixes https://github.com/pulumi/ci-mgmt/issues/841

Fix typo in free-disk-space action in release.yml

---

native-provider-ci/providers/aws-native/repo/.github/workflows/build.yml
native-provider-ci/providers/aws-native/repo/.github/workflows/prerelease.yml
native-provider-ci/providers/aws-native/repo/.github/workflows/release.yml
native-provider-ci/providers/azure-native/repo/.github/workflows/build.yml
native-provider-ci/providers/azure-native/repo/.github/workflows/prerelease.yml
native-provider-ci/providers/azure-native/repo/.github/workflows/release.yml
native-provider-ci/src/steps.ts
native-provider-ci/src/workflows.ts

Only run disk cleaner for ubuntu/linux runners

---

provider-ci/internal/pkg/templates/bridged-provider.config.yaml
provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/main.yml
provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/release.yml
provider-ci/providers.json

The new config should allow us to test ci-mgmt on xyz.
This will happen in a follow-up

Add xyz provider and config for testing

---

native-provider-ci/src/steps.ts
provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/main.yml
provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/nightly-test.yml
provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/prerelease.yml
provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/release.yml
provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/run-acceptance-tests.yml

Fixes #872
End to end testing now with https://github.com/pulumi/pulumi-kafka/pull/381.

Switch `docker-compose` to `docker compose`

---

native-provider-ci/providers/command/repo/.github/workflows/build.yml
native-provider-ci/providers/command/repo/.github/workflows/run-acceptance-tests.yml
native-provider-ci/providers/dockerbuild/config.yaml
native-provider-ci/providers/dockerbuild/repo/.github/workflows/build.yml
native-provider-ci/providers/dockerbuild/repo/.github/workflows/command-dispatch.yml
native-provider-ci/providers/dockerbuild/repo/.github/workflows/prerelease.yml
native-provider-ci/providers/dockerbuild/repo/.github/workflows/pull-request.yml
native-provider-ci/providers/dockerbuild/repo/.github/workflows/release.yml
native-provider-ci/providers/dockerbuild/repo/.github/workflows/run-acceptance-tests.yml
native-provider-ci/providers/dockerbuild/repo/.github/workflows/weekly-pulumi-update.yml
native-provider-ci/providers/kubernetes/config.yaml
native-provider-ci/providers/kubernetes/repo/.github/workflows/build.yml
native-provider-ci/providers/kubernetes/repo/.github/workflows/command-dispatch.yml
native-provider-ci/providers/kubernetes/repo/.github/workflows/prerelease.yml
native-provider-ci/providers/kubernetes/repo/.github/workflows/pull-request.yml
native-provider-ci/providers/kubernetes/repo/.github/workflows/release.yml
native-provider-ci/providers/kubernetes/repo/.github/workflows/run-acceptance-tests.yml
native-provider-ci/providers/kubernetes/repo/.github/workflows/weekly-pulumi-update.yml
native-provider-ci/src/steps.ts

This PR allows https://github.com/pulumi/pulumi-command/pull/396 to go forward.
Followup PRs:
- https://github.com/pulumi/pulumi-kubernetes/pull/2946
- https://github.com/pulumi/pulumi-dockerbuild/pull/25

Leave golangci-lint timeout for individual repos

---

provider-ci/internal/pkg/templates/bridged-provider.config.yaml
provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/main.yml
provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/prerelease.yml
provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/release.yml
provider-ci/test-workflows/aws/.github/workflows/master.yml
provider-ci/test-workflows/aws/.github/workflows/prerelease.yml
provider-ci/test-workflows/aws/.github/workflows/release.yml
provider-ci/test-workflows/cloudflare/.github/workflows/master.yml
provider-ci/test-workflows/cloudflare/.github/workflows/prerelease.yml
provider-ci/test-workflows/cloudflare/.github/workflows/release.yml
provider-ci/test-workflows/docker/.github/workflows/master.yml
provider-ci/test-workflows/docker/.github/workflows/prerelease.yml
provider-ci/test-workflows/docker/.github/workflows/release.yml

Add version input with value fetched from the new provider-version-aciton.
Related to:
- https://github.com/pulumi/pulumi/issues/16086

Upgrade pulumi-package-publisher version

---

provider-ci/internal/pkg/templates/bridged-provider/devbox.json
provider-ci/test-workflows/aws/devbox.json
provider-ci/test-workflows/cloudflare/devbox.json
provider-ci/test-workflows/docker/devbox.json

This is required to download pulumi in the makefile

Add curl to devbox

---

native-provider-ci/providers/aws-native/repo/.github/workflows/nightly-sdk-generation.yml
native-provider-ci/providers/azure-native/repo/.github/workflows/nightly-sdk-generation.yml
native-provider-ci/src/steps.ts

Fixes failures such as https://github.com/pulumi/pulumi-aws-native/issues/1514

Fix nightly SDK gen for aws-native

---

provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/main.yml
provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/prerelease.yml
provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/release.yml
provider-ci/test-workflows/aws/.github/workflows/master.yml
provider-ci/test-workflows/aws/.github/workflows/prerelease.yml
provider-ci/test-workflows/aws/.github/workflows/release.yml
provider-ci/test-workflows/cloudflare/.github/workflows/master.yml
provider-ci/test-workflows/cloudflare/.github/workflows/prerelease.yml
provider-ci/test-workflows/cloudflare/.github/workflows/release.yml
provider-ci/test-workflows/docker/.github/workflows/master.yml
provider-ci/test-workflows/docker/.github/workflows/prerelease.yml
provider-ci/test-workflows/docker/.github/workflows/release.yml

Related to: https://github.com/pulumi/pulumi-aws/issues/3915

Set PROVIDER_VERSION in publish

---

.github/ISSUE_TEMPLATE/0-ecosystem-providers.md
README.md

- Add notes about provider status.
- Add links to provider repos.
- Add instruction to update issue template for new providers.

Add missing providers to issue template

---

.github/workflows/pull-request.yml
.github/workflows/update-workflows.yml

Fixes https://github.com/pulumi/ci-mgmt/issues/926

Skip waiting for pull request if it wasn't created

---

.github/actionlint.yaml
.github/workflows/pull-request.yml
native-provider-ci/Makefile
native-provider-ci/providers/aws-native/repo/.github/workflows/prerelease.yml
native-provider-ci/providers/aws-native/repo/.github/workflows/release.yml
native-provider-ci/providers/command/repo/.github/workflows/prerelease.yml
native-provider-ci/providers/command/repo/.github/workflows/release.yml
native-provider-ci/providers/docker-build/repo/.github/workflows/prerelease.yml
native-provider-ci/providers/docker-build/repo/.github/workflows/release.yml
native-provider-ci/providers/google-native/repo/.github/workflows/prerelease.yml
native-provider-ci/providers/google-native/repo/.github/workflows/release.yml
native-provider-ci/providers/kubernetes-cert-manager/repo/.github/workflows/prerelease.yml
native-provider-ci/providers/kubernetes-cert-manager/repo/.github/workflows/release.yml
native-provider-ci/providers/kubernetes/repo/.github/workflows/prerelease.yml
native-provider-ci/providers/kubernetes/repo/.github/workflows/release.yml
native-provider-ci/src/workflows.ts

tag_sdk no longer exists and has been replaced by pubish_go_sdk

Fix docs dependency in native release

---

provider-ci/providers.json

Add https://www.pulumi.com/registry/packages/sdwan/

Add SD-WAN provider

---

infra/providers/index.ts

Remove native provider branch aliases

---

provider-ci/internal/pkg/templates/bridged-provider/Makefile
provider-ci/test-workflows/aws/Makefile
provider-ci/test-workflows/cloudflare/Makefile
provider-ci/test-workflows/docker/Makefile

Fixes #959.
Verified this works as expected via https://github.com/pulumi/pulumi-openstack/pull/604

Set missing docs error to true in the Makefile

---

provider-ci/internal/pkg/templates/bridged-provider.config.yaml
provider-ci/test-workflows/aws/.github/workflows/master.yml
provider-ci/test-workflows/aws/.github/workflows/prerelease.yml
provider-ci/test-workflows/aws/.github/workflows/release.yml
provider-ci/test-workflows/cloudflare/.github/workflows/master.yml
provider-ci/test-workflows/cloudflare/.github/workflows/prerelease.yml
provider-ci/test-workflows/cloudflare/.github/workflows/release.yml
provider-ci/test-workflows/docker/.github/workflows/master.yml
provider-ci/test-workflows/docker/.github/workflows/prerelease.yml
provider-ci/test-workflows/docker/.github/workflows/release.yml

Fixes https://github.com/pulumi/pulumi-artifactory/issues/771

Upgrade pulumi/pulumi-package-publisher to v0.0.18

---

provider-ci/providers.json

This will opt xyz into more of our automation.

Add xyz as a provider

---

provider-ci/internal/pkg/templates/bridged-provider.config.yaml

Document current options, their purpose, and their usage.

Document provider-ci config options

---

scripts/generate_native_providers_list.py

I recently fixed up google-native so it will run with the latest CI workflows. Let's keep it that way (at least until we're able to officially deprecate and archive it!)

Keep google native ci up to date

---

tools/sourcemigrator/index.ts

This has been applied to all providers.

Disable respectSchemaVersion migration

---

provider-ci/internal/pkg/templates/bridged-provider.config.yaml
provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/publish.yml
provider-ci/test-providers/aws/.ci-mgmt.yaml
provider-ci/test-providers/aws/.github/workflows/master.yml
provider-ci/test-providers/aws/.github/workflows/prerelease.yml
provider-ci/test-providers/aws/.github/workflows/publish.yml
provider-ci/test-providers/aws/.github/workflows/release.yml
provider-ci/test-providers/aws/.github/workflows/run-acceptance-tests.yml
provider-ci/test-providers/cloudflare/.github/workflows/publish.yml
provider-ci/test-providers/docker/.github/workflows/publish.yml

This dependency upgrade propagates a fix to Java publishing made in pulumi-package-publisher.

Upgrade pulumi-package-publisher to 0.0.20

---

provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/upgrade-bridge.yml
provider-ci/test-providers/aws/.github/workflows/upgrade-bridge.yml
provider-ci/test-providers/cloudflare/.github/workflows/upgrade-bridge.yml
provider-ci/test-providers/docker/.github/workflows/upgrade-bridge.yml

The upgrade-provider tool needs all the dependencies set up.
will fix https://github.com/pulumi/pulumi-aws/issues/4431

Run setup tools when uprading the bridge

---

provider-ci/internal/pkg/templates/pulumi-provider/.github/workflows/command-dispatch.yml
provider-ci/test-providers/aws/.github/workflows/command-dispatch.yml
provider-ci/test-providers/cloudflare/.github/workflows/command-dispatch.yml
provider-ci/test-providers/docker/.github/workflows/command-dispatch.yml

Fixes https://github.com/pulumi/ci-mgmt/issues/291

Upgrade slash-command-dispatch to v4

---

provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/upgrade-provider.yml
provider-ci/test-providers/acme/.github/workflows/upgrade-provider.yml
provider-ci/test-providers/aws/.github/workflows/upgrade-provider.yml
provider-ci/test-providers/cloudflare/.github/workflows/upgrade-provider.yml
provider-ci/test-providers/docker/.github/workflows/upgrade-provider.yml

Use `.Config.languages` to only set up the tools for the configured SDK languages.

Only install tools for the configured SDK languages

---

provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/publish.yml
provider-ci/test-providers/acme/.github/workflows/publish.yml
provider-ci/test-providers/aws/.github/workflows/publish.yml
provider-ci/test-providers/cloudflare/.github/workflows/publish.yml
provider-ci/test-providers/docker/.github/workflows/publish.yml

Upgrade to v2 of the Github action which is Node 20 compatible

---

provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/run-acceptance-tests.yml
provider-ci/test-providers/cloudflare/.ci-mgmt.yaml
provider-ci/test-providers/cloudflare/.github/workflows/master.yml
provider-ci/test-providers/cloudflare/.github/workflows/prerelease.yml
provider-ci/test-providers/cloudflare/.github/workflows/release.yml
provider-ci/test-providers/cloudflare/.github/workflows/run-acceptance-tests.yml

Part of https://github.com/pulumi/ci-mgmt/issues/1147.

Fix typo: `.Config.setupScript` -> `.Config.SetupScript`

---

provider-ci/internal/pkg/templates/bridged-provider/Makefile
provider-ci/test-providers/acme/Makefile
provider-ci/test-providers/aws/Makefile
provider-ci/test-providers/cloudflare/Makefile
provider-ci/test-providers/docker/Makefile

We need the plugins available at runtime of tfgen for generating examples etc.
Found while trying to repro #1197

Ensure plugins are installed before running tfgen

---

provider-ci/providers.json

Following up on https://github.com/pulumi/pulumi-awsx/pull/1471 where the workflows are now ci-mgmt workflows.
This in particular should reset branch protections to expected ones managed by ci-mgmt.

Onboard AWSX

---

.github/ISSUE_TEMPLATE/0-ecosystem-providers.md
provider-ci/providers.json

Part of https://github.com/pulumi/home/issues/3878.

Remove RKE from provider list

---

.github/ISSUE_TEMPLATE/0-ecosystem-providers.md
provider-ci/providers.json

Removes Local provider from CI management.
Part of https://github.com/pulumi/home/issues/3880.

Remove Local provider package

---

provider-ci/providers.json

We want https://github.com/pulumi/pulumi-terraform-module to fully participate in being up-to-date with ci-mgmt changes and have branch protections and the like managed by ci-mgmt.

Finish onboarding terraform-module provider

---

provider-ci/internal/pkg/templates/base/.github/workflows/run-acceptance-tests.yml
provider-ci/test-providers/acme/.github/workflows/run-acceptance-tests.yml
provider-ci/test-providers/aws/.github/workflows/run-acceptance-tests.yml
provider-ci/test-providers/cloudflare/.github/workflows/run-acceptance-tests.yml
provider-ci/test-providers/docker/.github/workflows/run-acceptance-tests.yml
provider-ci/test-providers/eks/.github/workflows/run-acceptance-tests.yml
provider-ci/test-providers/terraform-module/.github/workflows/run-acceptance-tests.yml

Improves: #1430 
Supersedes: #1451

Adding Windows build to verify whether platform specific Go packages are used.

---

native-provider-ci/providers/aws-native/repo/.github/workflows/nightly-sdk-generation.yml
native-provider-ci/src/workflows.ts

Fixes https://github.com/pulumi/pulumi-aws-native/issues/2145.

Add pull request and contents Write permissions to the nightly SDK gen job for AWS Native

---

provider-ci/internal/pkg/generate.go

I was trying to add a new test-provider and it blew up here because there was no .github/workflows folder yet. Extracted this bit as a helper function and handled the `NotExist` error.

Handle test-providers that don't have a .github/workflows folder when generating

---

provider-ci/internal/pkg/templates/base/Makefile
provider-ci/test-providers/acme/Makefile
provider-ci/test-providers/aws/Makefile
provider-ci/test-providers/cloudflare/Makefile
provider-ci/test-providers/docker/Makefile
provider-ci/test-providers/eks/Makefile

Small fix for makefile dependencies - lint should not depend on the provider build.

fix lint makefile target deps

---

native-provider-ci/src/steps.ts
provider-ci/internal/pkg/templates/base/.github/workflows/test.yml
provider-ci/internal/pkg/templates/base/.github/workflows/verify-release.yml
provider-ci/internal/pkg/templates/native/.github/workflows/build.yml
provider-ci/internal/pkg/templates/native/.github/workflows/prerelease.yml
provider-ci/internal/pkg/templates/native/.github/workflows/release.yml
provider-ci/test-providers/docker/.github/workflows/test.yml
provider-ci/test-providers/kubernetes/.github/workflows/build.yml
provider-ci/test-providers/kubernetes/.github/workflows/prerelease.yml
provider-ci/test-providers/kubernetes/.github/workflows/release.yml

chore: add GCP artifact registry auth

---

native-provider-ci/src/steps.ts
provider-ci/internal/pkg/templates/base/.github/workflows/test.yml
provider-ci/internal/pkg/templates/base/.github/workflows/verify-release.yml
provider-ci/internal/pkg/templates/native/.github/workflows/build.yml
provider-ci/internal/pkg/templates/native/.github/workflows/prerelease.yml
provider-ci/internal/pkg/templates/native/.github/workflows/release.yml
provider-ci/test-providers/docker/.github/workflows/test.yml
provider-ci/test-providers/kubernetes/.github/workflows/build.yml
provider-ci/test-providers/kubernetes/.github/workflows/prerelease.yml
provider-ci/test-providers/kubernetes/.github/workflows/release.yml

The list of registries should be comma separated.
Closes: #1501

fix: registries should be comma separated

---

provider-ci/internal/pkg/templates/base/.github/workflows/publish.yml
provider-ci/test-providers/acme/.github/workflows/publish.yml
provider-ci/test-providers/aws/.github/workflows/publish.yml
provider-ci/test-providers/cloudflare/.github/workflows/publish.yml
provider-ci/test-providers/docker/.github/workflows/publish.yml
provider-ci/test-providers/eks/.github/workflows/publish.yml
provider-ci/test-providers/terraform-module/.github/workflows/publish.yml

Reverts pulumi/ci-mgmt#1561
Looks like there is an issue with this version
https://github.com/softprops/action-gh-release/issues/628
re https://github.com/pulumi/pulumi-xyz/issues/1067

Revert "Update softprops/action-gh-release digest to d5382d3"

---

provider-ci/internal/pkg/templates/bridged/.github/workflows/upgrade-provider.yml
provider-ci/test-providers/acme/.github/workflows/upgrade-provider.yml
provider-ci/test-providers/aws/.github/workflows/upgrade-provider.yml
provider-ci/test-providers/docker/.github/workflows/upgrade-provider.yml
provider-ci/test-providers/xyz/.github/workflows/upgrade-provider.yml

Followup to #1651. Refs #1481.

Add GH_TOKEN to relevant upgrade-provider steps

---

provider-ci/internal/pkg/templates/all/.config/mise.toml
provider-ci/test-providers/acme/.config/mise.toml
provider-ci/test-providers/aws-native/.config/mise.toml
provider-ci/test-providers/aws/.config/mise.toml
provider-ci/test-providers/cloudflare/.config/mise.toml
provider-ci/test-providers/command/.config/mise.toml
provider-ci/test-providers/docker-build/.config/mise.toml
provider-ci/test-providers/docker/.config/mise.toml
provider-ci/test-providers/eks/.config/mise.toml
provider-ci/test-providers/kubernetes-cert-manager/.config/mise.toml
provider-ci/test-providers/kubernetes-coredns/.config/mise.toml
provider-ci/test-providers/kubernetes-ingress-nginx/.config/mise.toml
provider-ci/test-providers/kubernetes/.config/mise.toml
provider-ci/test-providers/pulumi-provider-boilerplate/.config/mise.toml
provider-ci/test-providers/terraform-module/.config/mise.toml
provider-ci/test-providers/xyz/.config/mise.toml

There seems to be an issue when installing yarn with the default `vfox`.
See https://github.com/jdx/mise/discussions/6527
Trying out installing with npm

Switch to installing yarn with npm
